apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shoko-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 2cbdda56bdce43738548c84f6d7dd9f7c904d6ef31bd2933d49930d40151a1fc
spec:
    secretTemplates:
        - name: shoko-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:B2pQmgFiIt8H/ncG+CEGHs4esIsTwNTuFkTY3IlnHYRSlt6UpyPZRHdbR7d9/zJuixeqUXe8AnmtbzJlP2Xrmlqcx7Y+frC/,iv:v82RdyLDQaQ0mEkTQ7fx64KPvYGuc4rTWPcVeYFwsfk=,tag:PkXLXrrNQ5Zqd8xvLvHONg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R1B3UmJIQzVUaVJmZ05y
            c2tCZ0hpUmdvdmxqL0hJbVNGQTJNK0s5NzJRCkNGM3oxSEplMjkxZnFrWmhiTnR4
            eVVVaHcxcWJkSTBub3ZQeGkzTFo1MFkKLS0tIHJhNGdMQnR4MDBNdDhoQnZINkdP
            TExEclE0bXlmNFAvSC9sYTdETlBYYUUK7ry9lhLB5DdpMIc/1yRtYgRWxhzVigy8
            ubYMgkmGv4vmzk5ULILv07sne38jvg1mJmU6s2KZqiFJ3JmeVDZ3LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:33:00Z"
    mac: ENC[AES256_GCM,data:aHFLclQ92TSN9NJ0zgpif7lTbPLxKc8+xMm5x1l3SXZsc9TmkAAnNM5Pn0MhK8ui68/NR+m8OwF1FY67kus/4II3lPd3/gB+wDdtJTdMFALyVrGnjLW7bKdlrdFIxuMM+ezZrOJhlbAj7CmF4qGe95OJ14/9Mrup6oUiy2KEqck=,iv:mthht1H5V0fFJTRU5TM5oW2t38mEHBnzC3oA1klmmfs=,tag:2RmbGQPyVMBm4dVYnvvJbQ==,type:str]
    version: 3.13.3
