apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shoko-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 2cbdda56bdce43738548c84f6d7dd9f7c904d6ef31bd2933d49930d40151a1fc
spec:
    secretTemplates:
        - name: shoko-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:7QCcAdy++c+ReB6tAX740/GaHj4PWyZLpCTUg10O/7MYBAcDr4xl9aX0it+z2L1LUjQUkBMKq164OMI4CEzwYFJAsdiKByK7,iv:D3tkS6sLGQ4N6DxXfJGfF6ieFs8qKg6PPwfMjQcZFOU=,tag:eG3rl46n9fVQmB7c9SPMuw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQTdJS0FrM3hxeTMzUU1w
            Smw4MHFuTkQxNEdnTkhTRUFjZnBYWjlZOFJrCmlhVkZudFkwdCt0WTAreXpCUFpX
            YWdUSHV2TnY3S2JtTFRoZ0JrZkxhQzQKLS0tIG9FVUNkbzM5SlVaVlRtNnlLcURP
            QVRGbExGL0dEKytPTThYak10dkVpdFkK7BSVE5ZQpRXckjROUG8vFNcpxyNUSNDM
            HOOzxzBik8o+xQ6b6dXCzdHG34YwZo/OWcxumb7AACq1MRremor6fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T23:47:54Z"
    mac: ENC[AES256_GCM,data:cGqwRjbquqtLMHxdRBhWRChXUCV2ERE66nLtYJBpWhRI20xifNFMDoCKgCzhaBSernlLMT45Rkk9yAEGjcnDPeCXHV+09YsSMHrN5MMaKrk8y3hxr94J+b4X5OTq91hY4XostR0dVsjQTsUCtFjCI4sodgn78CY6OX66TEZdYYs=,iv:nyWO3hYSGZk241A4ZDb2/D4FbOWcnP1cr5BV6RrqnBw=,tag:LxH2+Vd4fBopg/7AAPQopw==,type:str]
    version: 3.13.1
