apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-kubesystem-gateway-to-cert-manager-tls
  namespace: certs
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: gateways
  to:
    - group: ""
      kind: Secret
      name: json64-dev-wildcard-tls
