apiVersion: v1
data:
  config: '{"masqLinkLocal":false,"nonMasqueradeCIDRs":"{172.20.0.0/16,172.21.0.0/16,fd64:0:2::/64,fd64:0:3::/64}"}'
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
