apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: b59808b699ec5cef375a19ad78f475846a7f1edc85b4b4e97b35dd7b3b0a7384
  name: hubble-ui-oidc-client-secret
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcGJ2d2JqZTRlYlEweUZG

      UWtSTi92bnJ3MzRXMXpmblRZc25sUUFrV3pnClpOcUFTSGR4NHhubzFwVGRJdzFG

      ZVdVZ0ZnYjM4em54NnMxOEZZQ2wrTG8KLS0tIGgxaFFzOVo1Zkt4ZmloU3RJczZG

      TWFFNFFGalhlNGVuUm9qNFAvcm05d00KJYMxsx6VRjoKq26CNOzJuKwQ02o4vghm

      M9d4XYjJyqQtWSPFEfkxBEcab8h/smWxiaUvbSJRBy2ETP0tpUdh1g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-04T22:38:08Z'
  mac: ENC[AES256_GCM,data:f9OAg3PcAKgKhOJ8rWPlyAU5TdsC02bzeIlkhiYo5U3bQQqXjh8r7pMKXRjMbOCRojb7YE5lIixYhDDOYCukWu2dyHN65qnViH5Yur3+5WBiexNPm2uBE9cgWMhYAvHEJd0BxWKYd/ja228ZIGpuR24gvlPBnb1GTZr5pQoz978=,iv:PqrwxcPeWPTeiGehhE0TYhdDriCuVOiOhG2lpBQZA4w=,tag:uJuETuL3Z0lnWK03qTjdgg==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: hubble-ui-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:v1CTYh/Eb9vcWVJahL2m3kzuCay+GHY3BeUG9fo6tP0PYpJmt9ohaik/MNCyFSiC8PXG9Mz3bNAkKolUfsxXWdBai/9Y+QcZ,iv:JaJXrJeJGFTSZ0DHBCgOfzEXb/VDh63NtbeO+MzPP1Q=,tag:6Nh/WhSTBv5O7Z4h4prO5g==,type:str]
    type: Opaque
