apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/manifests/prod-axon/kube-prometheus-stack
    repoURL: https://github.com/sini/nix-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
