apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpackerr
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/manifests/prod-axon/unpackerr
    repoURL: https://github.com/sini/nix-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
