apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hindsight-pg
  namespace: argocd
spec:
  destination:
    namespace: ai
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/manifests/prod-axon/hindsight-pg
    repoURL: https://github.com/sini/nix-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
