apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-pg-dsn
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: 4786be73fef7c2138eb2553073a63961ace27db850769bd0433df288c67d43a2
spec:
    secretTemplates:
        - name: coder-pg-dsn
          stringData:
            url: ENC[AES256_GCM,data:kKDuXspxbAsuzseWVXmgmFAm239i4UZBZc6ik4fxKwOHPIpNLxPI07+cLUYSy4YElbbsyF//NkFb+PE98mf0vZyU4ITIIayhVYLtMkV4I9/tLAUQ70jgRvmVOcxCAxoFbz4+cUHwlkPx8UWcLjWIXUCLwnYlz1Xei20kGNdHDH0OXh0rKww=,iv:4cx+tRkftKcRMSUjuMA46NZ99ErnI5l9sJyUHRTTEi4=,tag:jHHd84sZ4/QQQw3CV6D55g==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Qjc1cHVac09lclhqL0E2
            RTA2cjZJQVl5UDJ3bE1QUGNmakhYVTZiK2pVCmxHYVN6Zmoyb3AwVi92WDl5RDVK
            REFVVHBvd1BWSlFVK2FiM0RIOVd5L1UKLS0tIGZKd1dwN0FoS0JVUEFoNUZ2amgw
            K2oyMHJkTzlnUnp4ellEY2xrbTdFK1EKVQ+RUoXpcjX5iKsxmcs5EwS7W5nkBmBE
            S2ir2mMNuEf0rYkx6Gza3cTfzjj/0bNRMU8ZaOoBNDyKMqbmkPQFnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T03:07:10Z"
    mac: ENC[AES256_GCM,data:va9JwY3qTjYnqs7YkKjL9uXZXaMjnz+KRygA94RnpKVQtxHDcWmaGMnjQmFgpUha3RXEz6Hs9e2bz4DdT4bbL3o++BfYSArHwEvxJ7MZ7fUu86ElLnW/nXYHW6uy0XgxwIO6Jx7XfO3QiHD/GUZLVJPpXjd7SKUc3dySmSn51Qk=,iv:9JahiH82O7j47yJ9akdE1lw5IyuI9Zrh8bs4y0d1gcM=,tag:LBaRkZwdx8ycV7QBeCGuAw==,type:str]
    version: 3.13.1
