apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-pg-dsn
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: 4786be73fef7c2138eb2553073a63961ace27db850769bd0433df288c67d43a2
spec:
    secretTemplates:
        - name: coder-pg-dsn
          stringData:
            url: ENC[AES256_GCM,data:A0I5fwwy3DN9Mr1+So8iDuihGW4WUdiUYz/oUUb2fkzN8YfkUMqQf6yEEuU0LN28iTqd/4/o27emWIn1gAs/jV4I3HlfRuINiBZ4aIC/Ub17zPSN9pup0lHZSM/vPB858X/FD/jaSAQFH/4PPfEZFiwGUHyEkv7rUQxWOIzQGdbNynaslM0=,iv:3PVSsfoL/x+Dme1ISrQXPCfC84FIV7Hr+m13XwMLai0=,tag:sByz68miSZjijvcGNf3epw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVktXdlczQ1B3dUloZlhl
            MzhCSzNnL1I1QXVlRmsvTVdWN25keGN6ZDNZCm10YUpWbEJub0hTV1V6ZjJLK3Uy
            dzZhem95ZUI1REFMNXdXQ2hScjNOMjQKLS0tIGlLOWlueWpCQlFKRHRHdm9McFFK
            SHJlT0I3UjlZWW9qaURraWlJYTZEWVUKO5Zw+qW3wT6P/e+6XoCpS4cuLTAW9N1D
            aEZV45/BdpPn/1lZ7c/31UubbiwiypVz328qfJCbconCJXJ7x/Hsrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:53Z"
    mac: ENC[AES256_GCM,data:Tf+G6K30TOpYWN9oiQLyrCFgxkSEBYZmVPVYjgwjHhCDuyOtQZhJIUY4AVjNFqIYXoBdml91YcG+7T24wsRaqdmy69F25lfdaB3YdlfT5cYcQAfYmpWPQi9t3VxsZg4c0V0CfCtPW5/roYmIBYBBOALhrKyWIK9NMaNfkKDUQyI=,iv:qSmSpjdQK8459eAwh4Jzs0pUPNhb2x6Cpwhk85NXV0w=,tag:0pKg4t9FX7SeuKyWzObkgA==,type:str]
    version: 3.13.3
