apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-pg-coder-password
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: 9334481301613626e2361c8746fec6ee06de6340af785082a5ca9d6e2071a3be
spec:
    secretTemplates:
        - name: coder-pg-coder-password
          stringData:
            password: ENC[AES256_GCM,data:tp3UVYOT8inmJtEjk1RmbJTE97k1y8Dgx5MOYsovG7mRcWjOg4ZgyFp/oXWkj+8InjED8ZvAZ8bEDbEGvk2KxB0MX1gTN4in,iv:hfRJpH6sC5XkEqdorg8/9wcNMPAYxze/9+bvSOtRX7I=,tag:/L8YWvqOwVlqSNKNtCaCgg==,type:str]
            username: ENC[AES256_GCM,data:zSOw7FI=,iv:HOh30Sh+/RJMn964IztlVklLVsCnLe6fo2OyasEDdzo=,tag:jaXyjcQ+Y7AOjdPDZ7wcSw==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia0t6UVpPMjIrYUpkMWtv
            UC84QkZzNWhaU0srbzhqenY0OW5qU09tWUVzCkwxNFJUVFg1YXJ4UUxCMnpsbm03
            aFV1OUdvMmIvdENLOW9XYlY4bHVsUDAKLS0tIFZ3aWwxNTFOVk9HZkp2VXVvRXRQ
            c2lJMXFhTEcxMmJEalE0K2NjNW5wMlUKX0Tx0jVhzk8+4feoAmw1yU4h87Apvy7i
            oJ+kUOOHHibpRxHHOF2twRfeSFym9EJhwGFU1CzLFfFUq90GtmtIbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:53Z"
    mac: ENC[AES256_GCM,data:QjD8EzBDN/9qgIbRFJ0IGOjtYTORtn6yqpzoG1rfyI7bqGxadP3SqwTFyC8gSnE9lk8vrcGxmAKHzphxqSxDRXkZnPzAs1uIx2K8BkCsqPzXFA4BKkayfzNNA2Z+q6NtJJNuctLikJePVgG6FM3EAMnin+9OqZ1g0luBsJq5aiQ=,iv:7EfXaKTFybsn4ljUHDqE4QTvgz5rxS/WtqwLXGPQfBU=,tag:3pe/HCr/URLdIjFjHHkXMA==,type:str]
    version: 3.13.3
