apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-pg-coder-password
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: 9334481301613626e2361c8746fec6ee06de6340af785082a5ca9d6e2071a3be
spec:
    secretTemplates:
        - name: coder-pg-coder-password
          stringData:
            password: ENC[AES256_GCM,data:rdeuxn3aEVPfu4IVvGugR6Te41NvYYsyqQh+c/CXHsKn22J8+rOk3NtxXZeabNctqPmWw/0mOAZN5sMc6Nzfav5ar18l6Vbr,iv:SnvufYngKKjitIzSsLolBhGcsEyOaPXXQzmZknoloXY=,tag:NIot/9ygplW/9jCcRFwTKw==,type:str]
            username: ENC[AES256_GCM,data:6slqTr8=,iv:LwGMb8ePeanNLiZUmP6gqvyRsSOiL12Wqz41gM36zNc=,tag:rg6HevUtYI4ax7EViqeGyQ==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYzltRUlDemVBc1g1NkN2
            NktsU1U1cGprU2I1TVBmMzltVTltMHQ0NWxZCkwzY0lQTVAyalQ4ejRLaGt0eENC
            T2t6RjNWczZjT3Yrc0tPM3duWFlFMzgKLS0tIFhqTVpsMStOMC9hQTViM3dkdGxV
            dVhJcHFnWVBnTERqa0tYbTFGYmpSYzgK7cwtfAKpjlwKQQgl9Wfv6xJbrOarX7Sd
            D/IFR17T9bb9+htudxxYC+3JgAFZS385x7suWWY9OxEItvV9WwTqVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T01:50:24Z"
    mac: ENC[AES256_GCM,data:T/NoOq4lUVynDd6KlqwReB8pnhi1EcFv/wE38YEdsqcVi2vFciSmLzvB3+BsFA8VsCiZZgnDK+zI5xGqgcbV684S3h+lSFFH+yUVd+ls8tCwVm9+P16dJfnd6VAjZS8kOXTjers4dGi9/XBGphr9iq4ug4tW/RDvfmZ4EnFXYVM=,iv:fs6tJzc21jAz2qOM0G2E1NUkngtP80qGFW5Wyr2O+2w=,tag:yMn6XTDj3oZ0YgQWYQrX8g==,type:str]
    version: 3.13.1
