apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: coder-pg-coder-password
  namespace: coder
spec:
  secretTemplates:
    - name: coder-pg-coder-password
      stringData:
        password: ref+sops:///nix/store/7rsvns85vkvf6wh1qclsphs7b6g6j4yn-source/.secrets/clusters/axon/sops/coder-pg.enc.yaml#coder
        username: coder
      type: kubernetes.io/basic-auth
