apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: coder-pg-dsn
  namespace: coder
spec:
  secretTemplates:
    - name: coder-pg-dsn
      stringData:
        url: postgres://coder:ref+sops:///nix/store/7rsvns85vkvf6wh1qclsphs7b6g6j4yn-source/.secrets/clusters/axon/sops/coder-pg.enc.yaml#coder@coder-pg-rw.coder:5432/coder?sslmode=require
      type: Opaque
