apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hindsight-pg-hindsight-password
    namespace: ai
    annotations:
        secrets.json64.dev/plaintext-sha256: 6a80310a1f26da3d7467461e9adde6eb896ce11558d93a0416272194a6f268fc
spec:
    secretTemplates:
        - name: hindsight-pg-hindsight-password
          stringData:
            password: ENC[AES256_GCM,data:mUcI+8llVhIIL9TZ4+5O7PdJYuWoY2PkrGYvl+v4LHrc++MGiGG/X+RLx1USNPJv+ZD2/PMU7876svHWgApB35t0jSdQ3584,iv:JffSOznBOvh9gydjyebALoP0oY3GRSv7uz4/cxQuHwU=,tag:TkMZUgfQRFf6xbW6I5HuFA==,type:str]
            username: ENC[AES256_GCM,data:bvkVj3WfgFns,iv:FiTxzC0ogbi6K0+H2s5Dn1OSmENtbRNu6qRuWkhqDgY=,tag:KAhSQM+GyL2hE18qUjMCfg==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMnN2M1orK2Z3N08ySHBt
            MVNGenFOdys1K3ExRkkxYWVjYjNpSFZGN0hrCk01MmhqcEFqcHE5VGlSenQrQmJz
            aXNGZ3hpSk9FTW0rTnBrbnl1Sm1oWXcKLS0tIE5MS0taODEyM1A1cmRYY3Qrelcz
            ZFBFUXBTL3MvM3JFQ1kzQThmeE5NVm8KS9bIoovD9LQQMROGSfB9toUAQbRf3/tn
            ztDPU/LK1rEM3AUvSg66+JQiV+0fZ8+1Pq+YvLHJ4ps3mJ8edGLUAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T20:40:52Z"
    mac: ENC[AES256_GCM,data:enojssj8dcKwOHAnqQNQzdbSX95eHn3mTlQ/4ziX/GXCeotcmyqU5JgxSLwViydUj+zuYbyv/VsTgFZBUmLiFyWDpuRz5tc7rXQeqpjyinz7odiNenBRtBPShw0G7OtAxPfXp3HezNc+zwf0wTubt5ulfCgytBUH1O1yquxxSTE=,iv:A7WFJKkLfiMW6sZn6eBZ6KXFC60R9DLpOXa8GWUWCus=,tag:7PZoF7QIz93Uw8GLn1gVxQ==,type:str]
    version: 3.13.3
