apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hindsight-pg-dsn
    namespace: ai
    annotations:
        secrets.json64.dev/plaintext-sha256: fa588b66ff6a7bded25c7dc02923bd264b5330787e94c72076b6c2e747a21467
spec:
    secretTemplates:
        - name: hindsight-pg-dsn
          stringData:
            url: ENC[AES256_GCM,data:0ptSOiJmTk39nuNcwZsa3lyeiSKUTmaZG9CZ55gpcAu1QonOABxAwCCHYPRtg6W1EIicrjHcce4gnVfuApRMzySg+YKnU1nvUox7V0UUNWLdRXClu1XIX6C+hnA8cUQrAipfBZveo+nSLgaR3ZaLqZhr9+TFKQWbWnD/S5VxbEW08LEe1K8aZs4S4Ar0KU4BQn1IpYQjeWsPYLJppeaKm5jsFw==,iv:X2mOqeU3OIHDZ8S8V53xSCg1QAFHLwfHfB3j408p/Mw=,tag:h20sqNM/hiiCkQ+6CNH43A==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VGVtc0tOS0VNMmNiT1Zx
            OGVrN1hQSHRBVSthN3dRUUhjSHRnQVVPckZjCk0vL2s1ZUdmVmk1MnRxZXBDY3Y5
            L2RvWkwrZWJzK0czVGVVV0VCa3hNZTQKLS0tIDVOSG1jeDVtSmVwOXRpNGNxalFJ
            c25aQUhPQWo2UTgyTldiMmtZYTdTbFUKdrhA8TWMQ3VABApoxClygMcqUdYAhTaV
            mHb+ljk97MBiUtrmk5BUS2wO4cllwb6y/VnjArazJspCjPPH6aWD0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T22:19:24Z"
    mac: ENC[AES256_GCM,data:vVSbY4XoYrKCQzMWyVPlmgqSbrBUN2aTXgWOVCM4F871eElacxSFT/KRk7z8/rrktIB1QuXD1k2tCKxV1yUwBwT9X11nSEJRYXXIK9abPTuf+ZQYwgH0V0Bxpd6u/zFmmGLRjXhUAhkpvv+Vz1+ssHChzExEIO3gniHObArqPxw=,iv:XgzsvpjIhZkhq4yc9WhLCGwMXzKylsDXDZ41d5yeMwg=,tag:ug2F3ZV2RN8gCInG/PeOeQ==,type:str]
    version: 3.13.3
