apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hindsight-pg-dsn
    namespace: ai
    annotations:
        secrets.json64.dev/plaintext-sha256: 409fc33cec98f7ffc19526972e9ff0e1d2c05128c294846266de08a1cc27ef51
spec:
    secretTemplates:
        - name: hindsight-pg-dsn
          stringData:
            url: ENC[AES256_GCM,data:HvCU3jvGwZAATTRXLzi/0JOtcvLci1eCJ2IiNCyB5V0YrB/hcIITbEZQx1I4BA4FePSyksnTvaF6CM+bxsptipNOTbKNF8tPv0M+TNmSRnHoLEtMKI9mvfgF4slnKTs7N7Sc6meqR86nRTclN/H4uRtW/u+uA93g9L48smHzu8DFPZNO1FGGgoDuVQtE2YFLNw==,iv:aiLk35kCsZlWERMyR0brUOBkIpPQ1l5wlbIUh/5/Npo=,tag:BahgoGz7UDYiLBvJHSbiPg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZSsvQmhEU20yY1VJS2xU
            M2ZjRm85VnNQdU5Scm9YMFhTUW1DM3Y0bVNRCllCS3d5WGNiVzhQMEFhZ25JVGZ3
            RGZuVm1MWjhsQ0dUU0x1WUJ2Q0tPUDQKLS0tIC9sOVBNZ0JON2xKbTRWYy9oNTJF
            Vm1hWncrZWpaQzgxbHUzcXNRTW1rNEUKSKqKWjhq7hWHeTD1C8evCAWpcpBuSDLn
            DEfZiOc9wf97PhxFo9HLUA52tSAi3uAqKfe+pfpU719LbqN4FY4N3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T20:40:52Z"
    mac: ENC[AES256_GCM,data:a3nJDJ6JC8WF4SU8yjQ+gL7NXG5sKo8nRHvpicocvfMrGALQ6ghaxx2Z1Xex9KvnN2XezmbOYluT2w72xtlVbn5XHOCOurM0N004UXKwENrfqM7aEUlC+4/RAq3G40CodKhAnipYQCrquCj1rf4CKdqTt5QVZwTG7aliFMF0O2E=,iv:nLP+rQlCfCVd3Y1cAcWMdsAufetms6JzydSkUVW/pd4=,tag:kPEY+SWw7inVj12A7ECjLA==,type:str]
    version: 3.13.3
