# =============================================================================
# Cilium BGP Configuration for Production Cluster
#
# This configuration properly integrates with the thunderbolt-mesh and cilium-bgp
# NixOS modules to provide BGP-based load balancing and service advertisement.
#
# Architecture:
# 1. Each Kubernetes node runs FRR (via thunderbolt-mesh.nix) for inter-node BGP
# 2. Each node also runs Cilium BGP that peers with the local FRR daemon
# 3. Cilium advertises pod CIDRs, service CIDRs, and LoadBalancer IPs
# 4. FRR redistributes these routes to other nodes via the thunderbolt mesh
# =============================================================================

---
# Shared peer configuration for all nodes
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: local-frr-peer
  namespace: kube-system
spec:
  # Peer with local FRR daemon via loopback interface
  ebgpMultihop: 4
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 30
    keepAliveTimeSeconds: 10

  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "cilium-routes"

---
# Axon-01 BGP Configuration
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-01
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-01
  bgpInstances:
    - name: "local-frr-instance"
      localASN: 65001 # Matches host BGP ASN
      peers:
        - name: "local-frr-daemon"
          peerASN: 65001 # Peer with local FRR using same ASN (iBGP)
          peerAddress: "172.16.255.1" # Local thunderbolt loopback IP
          peerConfigRef:
            name: "local-frr-peer"

---
# Axon-02 BGP Configuration
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-02
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-02
  bgpInstances:
    - name: "local-frr-instance"
      localASN: 65002 # Matches host BGP ASN
      peers:
        - name: "local-frr-daemon"
          peerASN: 65002 # Peer with local FRR using same ASN (iBGP)
          peerAddress: "172.16.255.2" # Local thunderbolt loopback IP
          peerConfigRef:
            name: "local-frr-peer"

---
# Axon-03 BGP Configuration
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-03
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-03
  bgpInstances:
    - name: "local-frr-instance"
      localASN: 65003 # Matches host BGP ASN
      peers:
        - name: "local-frr-daemon"
          peerASN: 65003 # Peer with local FRR using same ASN (iBGP)
          peerAddress: "172.16.255.3" # Local thunderbolt loopback IP
          peerConfigRef:
            name: "local-frr-peer"

---
# Advertisement Policy: Pod CIDR
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
  namespace: kube-system
  labels:
    advertise: cilium-routes
spec:
  advertisements:
    - advertisementType: PodCIDR

---
# Advertisement Policy: Service ClusterIPs
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: service-cluster-ips
  namespace: kube-system
  labels:
    advertise: cilium-routes
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - ClusterIP
      # Advertise all ClusterIP services
      selector:
        matchExpressions:
          - key: service.kubernetes.io/headless
            operator: DoesNotExist

---
# Advertisement Policy: LoadBalancer IPs
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: loadbalancer-ips
  namespace: kube-system
  labels:
    advertise: cilium-routes
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
          - ExternalIP
      # Advertise all LoadBalancer services
      selector:
        matchExpressions:
          - key: service.kubernetes.io/headless
            operator: DoesNotExist

---
# LoadBalancer IP Pool (matches environment configuration)
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-lb-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: "10.11.0.0/16" # Matches prod environment loadBalancerRange
  serviceSelector:
    matchLabels: {} # Apply to all LoadBalancer services by default

---
# Node-specific router ID overrides (offset by +10 to avoid FRR conflicts)
# Note: CiliumBGPNodeConfigOverride resources are named after the node they target
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-01 # Must match the node name
  namespace: kube-system
spec:
  bgpInstances:
    - name: "local-frr-instance"
      routerID: "172.16.255.11" # FRR uses .1, Cilium uses .11

---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-02 # Must match the node name
  namespace: kube-system
spec:
  bgpInstances:
    - name: "local-frr-instance"
      routerID: "172.16.255.12" # FRR uses .2, Cilium uses .12

---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-03 # Must match the node name
  namespace: kube-system
spec:
  bgpInstances:
    - name: "local-frr-instance"
      routerID: "172.16.255.13" # FRR uses .3, Cilium uses .13
