apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: whisparr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 1f967f1a1a008e186a3248e9f26232ca88135f6143a3097d11e76f744db02a51
spec:
    secretTemplates:
        - name: whisparr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:kxCQNXIICx4+3eEJOUsJ7iQ8W/3eCzza8yA1fynSYxxf0CsZ9EY/IdcUvyYVnvFNuACi7Stz6P3VYzOusypgUI7b7P1A4bAq,iv:kDcUdraJt4377q6JN06UvDsgxnfnfojeEz9bOr+eTrM=,tag:YtSi3uJz1b57hCO8lhNmZg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcFdyOExOSHNoZUcybFkv
            OHpyUmlkcUhXNERmS2ZoQ0pxbzVKNjUrQWdnCjFBYXZuTGRqQjlTalIrSlNOa291
            ZEdKRUpoZUhvUEU4RWlIWVNxTmRZQk0KLS0tIEJaOHlWdW1GekxQQnplWm1JcW9E
            eG52dkRDdW1ZdFJmazhUUDVVdEdXeW8KQkUVC8cfcLunf5N3guBtv3HN8VtHV79k
            hH9TM4ERDS3b6N3vSmjXxDHbVnPl0EGSHKNnNZ+vtYJyY99mDOgSjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:48Z"
    mac: ENC[AES256_GCM,data:sn/LfqNUxPcUz9xsAeA0tOLvqWtZpv5GTjCFKoXdYFxokLd1ekaKMcYDmqzPJfrSHROu3wltP5oUhQdDcY/GBPiZoG9qySIEkNIgtibo7n4gazlFVWYdZoANm8WCup780xdwkZfpQCyu0Y9WBJEQiMTXVal21tk11mZzZh1gr6k=,iv:SUuqT4WAoB0+PDrtHnE6nKsckLaaP/XfXZUeVW9e5rE=,tag:GpkW+CFxEv3twwXHTtuO+Q==,type:str]
    version: 3.13.1
