apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: whisparr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 1f967f1a1a008e186a3248e9f26232ca88135f6143a3097d11e76f744db02a51
spec:
    secretTemplates:
        - name: whisparr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:hP/H/twHTJPZGqkaOKtnlDX8/OASN/7ehs56aJLYeuN2HR7TGM7tuAG9KxjaHEaCTqt8Xr5vinbLAQ9tATL5jBkB8JMnwidV,iv:4r1SxBPoFxWMSNGeTsmrb9CDg8LExwrYQc4spc7oQ54=,tag:4Tj47qqTkN23N4TLIbXdxg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPejU4Vmk3ZWtiWTlCMHpR
            SXdnSjl5cUxBaU9IN1VHYVFyZWxUZ2VWUkFzCk0rR2x1cTNUWnlOYnpEL2pudXFU
            RmxmL2pFQ0N1WlFtcW9kSGE0VXYvMjgKLS0tIEJrTHcvb2IzMVFmaFJRLzFiMVlL
            aTM2RkFmTTYrd0RkbmQ5Zmd6bXJkNDQKa+AwHD7p//KT0ZH76GYlSXaJvVkH6UJx
            LyunBXHsEe4HwPE7Qal+0qgFLs/nkaVJfV/HWH+gh+weD32Hd8yIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:33:00Z"
    mac: ENC[AES256_GCM,data:1hXGTVtlK+KYhZ+g84CSZtrpPfQk8uusv6lP1mVodzjQQ8JJRC+1YVpD81CoTp6dRuWzDbREa53/Mwiz/22mlsjHBEh9h6QzR+rk4BjzJ1hPkLowRXqS/wBZLvs/bFBFpg/rtrJ1LZ/5QUvbfhIWGrD87fbOFGfOfEc5yBOwXUk=,iv:Vd4qC40LjLdohwBqwtJfxq3ymcb4RBWHRv0hLz4VrXs=,tag:lDgdDvdxrxDCKV6dpMNO+Q==,type:str]
    version: 3.13.3
