apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: komga-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: b6f2275ebb8d81ae47a075bd41224b550fa3443e2273032102e87318ede80c1b
spec:
    secretTemplates:
        - name: komga-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:ueXT8pf+6DOJUvp43867t+ZBaAKokLcRdlktDcfBZPC42Kc2xgl8hfqFSatigDEJxELdj6nEGghcutQq1WNBKuIRAw8GNq+e,iv:SQBtBsyCs8TTX7+krP3gtH3NMzZlBc8luF3YMSh85bk=,tag:m/xPAB8vRI7kze8zmfuBLw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveDNmdXlrNDN2MFluSjYy
            Q0VmTVB4Z0dvK2F2RWc3N0VCTjZXWFBDeW5ZClZldmE0RXF1c3dkeWluU3l5dUx6
            T2c0VGttc0NISlZ5U21zbG9WdHdRTWsKLS0tIFpGTFVWdUJBRlZ4MTlvQjhaaWJ2
            TWt3NnBRTkl3OStCVU1HTXp1TmVVMUUKbr9vU00wD0NrlZUmZtXj27TMQTqThCIq
            joApX3kW+pGdklixgxbjW0pfzRK35Z1Bpw8/HroQ18lBPkYoNBh5SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:55Z"
    mac: ENC[AES256_GCM,data:A6Ue9B+djKUMTVybadXRFhXj3eD5hSJbzLxCvXUvw5L9r/uKs0jhOKOJUU4sNYY0RJjGV9fdaE7/jrZ7vRWPNQ58W6B8W2GfTNKueshljZWj0614Iap6V0rKhvSTit51+yzOuIkd1bF17Btkfx7eblWhNiW71QG7Iaw9uqUWYE4=,iv:NMKB161hBuHqHow/NNyjT6OEMg/SODZXcK8vy7A6UBo=,tag:aZyCn412o2LLu7STRoSSTQ==,type:str]
    version: 3.13.3
