apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: komga-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: b6f2275ebb8d81ae47a075bd41224b550fa3443e2273032102e87318ede80c1b
spec:
    secretTemplates:
        - name: komga-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:6hJVFcEwhRm/Tg2+7f67Y3+gKMesru4atPvKN2Zg8YVHbSzd9jRE2YM8WjLS9jkUyege5O/t0RfJ1Sd0OzKGhM7kQbtRS4xz,iv:IGP8Y8j38aTME9zhVNHddoIcPPMAvOZFLBc9VBdvlQA=,tag:6Mjf6vyhDs1lYDfAOuURNA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaHFJRk9QS2s0L3ZBaVEr
            aWloYy9JNjhxVEMzSnhWQXdkMURJekdBMWlFCmU0WVZ4WnlRcktZdXBIcTBlMG50
            czNMUHlCK0htd01FVmN2NnFYYjJ1dzQKLS0tIDFxUGQ1ekwycXQvVzgrbGd0NUJs
            cG9XakJrREgyQ2drcEd5b0l2Z0kwNTQKkLbCAQz4CubNyga2AGSg/yIhem7e0VSM
            Bx5nsRx6ri8q11JC0AYk2nPbhlgT5BtlKB5QKHbQhoTbAh4CqveYcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:a9mmF0rQkLCXrSfsDTUjnpyL/qPdTfAET2oEDbLH40+Ag1P7QnsqQAHI+0WdY4S9E7I/iiXXDWJppkwqrOmw/WKLFyOluFncmngLAFJVO8Ii38/r2PWqu/ellapAdk/TT2uemgPX8XdZYuhxRf4T4uZh9xDYyEOPW6k8dZ7tzCc=,iv:TvtHVUkFGkpVaHMDNB8F8il9xr29jR45cEGzZnB0ExY=,tag:KFMRQslNvIx+ScIniHuZBQ==,type:str]
    version: 3.13.1
