apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: site-qvr-sh
  namespace: garage
spec:
  clusterRef:
    name: garage
  globalAlias: qvr.sh
  website:
    enabled: true
    errorDocument: 404.html
    indexDocument: index.html
