apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/nix-config # TODO: Replace with actual repo URL
    targetRevision: HEAD
    path: k8s/nixidy/manifests/dev # Path where nixidy will output manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default # ArgoCD will create namespaces as needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  description: "Applications for cluster infrastructure"
  sourceRepos:
    - "https://github.com/your-org/nix-config" # TODO: Replace with actual repo URL
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
