apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 7b957bd5bc1e67f38c7359804683813a84d9e2bc936eeb7f494430ac1942b00a
  name: longhorn-oidc-client-secret
  namespace: longhorn-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dk45QTZxTFhFeERKaHZw

      ZllwelM2SUFrbmZ1ZE1KVTdNK1FJTlpJaUM4CnpsaGsrRWhEbVg0VEs4WU92citn

      N3Rza1FUU2p4NDhnYTNycXNXY0pjNVkKLS0tIFA5NmtpSEdkN2lScXZkOTQvUGNv

      QytENzNoMk00R0ZiV3lIVjlCMDhiQ2sKDyzrp592PYKfsBFipA8BpqFz1sZ3GN6A

      V/XSigyGfXhVsBypq4SlAnBWLkd0adD+wiXuHqbQ3+Opaz5FDTrP+w==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-12T00:25:37Z'
  mac: ENC[AES256_GCM,data:dwXNfmjT5OKBeuFa7LTd5qKpu05e6PcMiFHUMy1RtYHIuxlMhGEfBy5lrBuLntRxPXl06FlY/H3N1GtKZ4ph3eP2B+n3AKLGe/NlzX1X7hqceUBK3HVyqfHXPYKxxYeRLRApP1X6/Rhy2/SjyVx7Z8cNT3LJctKvp0ZyNoe4s9o=,iv:DiMGWquZUUHwAinaxAtjUCOcV5T6rUCNNebst1cv3A4=,tag:ZVfMQfyvAeF0iw2vWxvaKQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: longhorn-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:0rnpH0jaT7CMJMsb+9+TcUePP67m0LtlbelmwwRyzs4DBDecUw26FvwskUT5Co+Q4ifUYPj/VD9eUB8kkOY6QlxJtb3c5Kfw,iv:TlM6e6Hp4VsoHPpTRdRXcrDkmgLkeWvq9KHt2T3pKOQ=,tag:3tgthpSh3mleNXQ1X+0C8A==,type:str]
    type: Opaque
