apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/media-config: enabled
  name: romm-userdata
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
