apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: romm-redis
    app.kubernetes.io/name: valkey
  name: romm-redis
  namespace: media
