apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 9ba1da9c5ff96f30596d5bf237f9744d69f128bd2a4f1c77a25d2fbca1d36072
spec:
    secretTemplates:
        - name: romm-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:gu7M4+hHz89Y0x/IH1QpK/Btwh0wI3Uy8lPGjmgYkkehzd7kjIY/6L67tA1dKaFSyBo184BIzVKFcDy8pge8lRnIichhddcn,iv:y7ziMF0XvnmXf+0tIeSYWdC5Su6pPvShV4A9VO236bA=,tag:cBiDoXT8QAupiHjEESX/IQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMm1OWnNLY0I1NFF6ZmJR
            ak10ZFl1WStRZ0JaSkFQMDNEYVJ2bDJ4Q21NClV1YWNYMkR0VnlmZUpPVUhHSnhu
            RWxlZldyRE0wVk9XM1VHRllFSmZPTmMKLS0tIGgzd20zbWEra0dFSzROODhlQWZN
            aW03aGJlVnJYZGE0cDM5ZHh5SXVSSjQKoyKvMTbayAZu1/ar+8LKPDSR5OkhO5n0
            Rckjy0oHbQJq8HWvFlmJTwcf4dGrjAUzI1DnqW1XAzfveGFFsK46RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:48Z"
    mac: ENC[AES256_GCM,data:QKK1v2lm3Q1c6YTSEjdspzowHY50byRQBDAgAGyhKvdpay8xQ+sJQ5VCfLgt2yDaww5Ikg8H0rXo9uAeqa6Oidb4xScBLVM4CjzzX3nnpDapMRbLKS7KF2brpc5sxPqYVMPpLSAcN+z1K+Vu+LxdLpSpe92m5fPWJP3MT9JlBxo=,iv:uxJ8uxdkiQQ7UxCxjUt+OtcEt7KNeRz+o5buijdmb48=,tag:4r8P8ERpE93+5ti3k9VegA==,type:str]
    version: 3.13.1
