apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-romm-metadata
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: b74f927635bef3b5790340973917e4c29b28577a34b2699cb5f4449dddb45b04
spec:
    secretTemplates:
        - name: media-romm-metadata
          stringData:
            igdb-client-id: ENC[AES256_GCM,data:L08jOOTiQZCoDJW/dTv54Zn+inbyCw7Ull8ACkT4,iv:HzX9Fx/BLn4t5XeQcZW7To5lAACHGngDz4RS7Dscn+A=,tag:ZRN0m6xP5NQpyzymXyrqzA==,type:str]
            igdb-client-secret: ENC[AES256_GCM,data:QoR89TnMn77eWAKxYdbRtzueeMXefr47zRAZ7MX4,iv:Mo5JxudNGhJxO2hJJFcouMA8gy72aHSPTUYYNqsjZOA=,tag:tQqBx/4eb9KwWn8vfDa3dQ==,type:str]
            retroachievements-api-key: ENC[AES256_GCM,data:o2RcS2gExFJzarX4KAC7A2wMvlxf5sNANm4ROQSNFoc=,iv:dIaUIph46aJOa1IaYTKJAyEd8r44imaK15P3rsJ4Kmk=,tag:vdLy/pHOyli0AkABCCR4ZA==,type:str]
            steamgriddb-api-key: ENC[AES256_GCM,data:FhxoNqiudy8Ec7tiWW25oseLTM1d6B9guAqBiLYyYdA=,iv:9iiiag0LsMxU0xBtJMnBTlvXH6TNKF7GxfYr0Jctx90=,tag:rqBmU57dECo6ai0w4AnR7A==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyalgyellFWFB2K2ZXYW1s
            TWZzbGlUb2dCZzliYXlHM3czaFNjT3N4akZFCkRhZlZIU204VFJ1VGlhT3VuVVl3
            VWdiMm83cDFtUFd2Wk4vZXFFZGpOQzgKLS0tIDd4blpwWmhSUE1zUlU1U0tIRWV6
            T1VnRVgyYXFvMmcrbG0vUHB3cytaUjgKyVuWwuSQYDdLdNbw0inlbFW69jY6KkkH
            GgGnXfXumc0lRqvvOSWBS7eA90OJxIR7geSTLMRNLPFG/kKRJaw1XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:59Z"
    mac: ENC[AES256_GCM,data:aT/CyfkCRauovjPwj6J8f9V0ifb9d+ImTE3ywUP0+0z76QUtnoTkLLlUz7W96mNPCFdQG/7G+Sj/u8QIKIlJkeY7nU9lDRv8iIJG7UuUuSGi0a/1tuXXNzOlvxsbZ+opHW3WAML6R4MtuACfNPe81/R2vQt8A/gf3MFuq9OP6b0=,iv:fffTqKElBNT728kXQ17ck3Lie1RvFgECEqcyjRVHy9g=,tag:HM1EL44ieUJ8dpF3kAboRg==,type:str]
    version: 3.13.3
