apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-romm-metadata
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: b74f927635bef3b5790340973917e4c29b28577a34b2699cb5f4449dddb45b04
spec:
    secretTemplates:
        - name: media-romm-metadata
          stringData:
            igdb-client-id: ENC[AES256_GCM,data:4pVR4VddngPB8guQwETIoXCWAVvh4MDtZtgvO1V3,iv:SdM+vfMtOS4DCmYBeiWZS9V8apBcmB6DUy5iWno/RE8=,tag:MSXiAH7fwHwnuQMmhqmVtw==,type:str]
            igdb-client-secret: ENC[AES256_GCM,data:IH69DQMsUMXLntS9HyPo+Ic9yYSNKtomgKw3KLJT,iv:P7pBrIbsx9JH8Y4VAB6w5Sz+vr9YrW534H3WGyULHC4=,tag:3nIIQx+CjqDW7F0SWnyyjA==,type:str]
            retroachievements-api-key: ENC[AES256_GCM,data:res5Z5DY6UDmz2j6/4uYNuLCEVBpRbAr569lHfVaIeM=,iv:8ybzW3htQvaVU2ANomK5yWbTfeETheE/Y96mhZZnrss=,tag:mYyvi2ef13gIdx886Nz0aw==,type:str]
            steamgriddb-api-key: ENC[AES256_GCM,data:ALr5IeQVQiJlfULcAsj/fpcuMecV5us/ZB54qLlfvic=,iv:7AeDItT9QRsJ7pjReh8wXKpEuXknOE/Z2S69jb8vx3k=,tag:9ZuCoiekCCrgvsR/iVSorw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYzlSOHVXVVpZcTEwYzlr
            SWtCNUpEcmJiOXVRdFZ1enU2SkxrNE82MkVzCnh3ME0rb1JzSTBVK3VIRnFhMmNW
            Z3JyUEdoSmpmQlNVN2w3VjR2dDMrNkkKLS0tIHpNMCt6MEMwZ2ZxVCsydTRwcDJq
            RzRBdmdUdm5ieTZtM3FuVkFlbmQrZVkKvqsxSpAilsk43s8e5gWxWWzIV4X2yTMG
            IPmJ+I4cvYPpnBO+XOdrviG9/1ho5tM4t5lO0/KQHkP9L/29k4zWRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T19:58:31Z"
    mac: ENC[AES256_GCM,data:ie+AN7DdPGDvXKpaQY63BgXIMLw3AIqWoQbhOn48kG/jre+wsHMGiGugdLIaZfZ8vVllxkHtPnPVjlv0W7fCB2pTyzU9dL7sGKa0Ke0jhoj8YVQ5IdNLEsTaxppgfqAWGtpwDai5VHzn2AZpMa7R54uzlE0RcPI3EM2ayA71Nik=,iv:JKH2BjKH5d4hxehp2tD6rzTXRA1RiSIZqEqZ2+8oEzw=,tag:0t6LhZD1mUOExAVw1WNnWw==,type:str]
    version: 3.13.1
