apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-romm
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 98b70dc92fbd8048713e04727388f40d42dcbf68b2d1dadb44fc2c52156953a9
spec:
    secretTemplates:
        - name: media-romm
          stringData:
            auth-secret-key: ENC[AES256_GCM,data:x6iPMEWCm6tYptiYUwtoWNlF4VvaM6Pod3fmqfG/LN3i6HCvQcwqMci9a3bNeoZ5z9+35G5qZUlo3jbI3mPO4Q==,iv:BdknFBalDS03JEMTZrd/pjxgDQEQNc+YmQDX2y2uVkQ=,tag:FtihrvKQtcE4OE6zgv+Tyw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWUvTURlLzlnNVJTeVFQ
            S3h4MHoyTjkyWG9iWnJHSFhnaDdMZHdHTDJNCllCZ1lPZTBEb1FwSmVaVUZzaWR2
            WlNjUXFkVXlMNWY3c005QjF1RlF5bGsKLS0tIDNTbmduRW9BVW5jT2Q0cWdIQXZH
            cVU5M3N6cVZKWGx4aTdNd1NBckVreHcKpb6CqKd+3CfeC7mZURMtTHtxWSR+LZDR
            dioR8MGxge6dz2F4rCKb/btxw0K8A0Y4P3wCO0BmQPK+J7IgoZoJig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:47Z"
    mac: ENC[AES256_GCM,data:CC9KIGu5DetahQJw45CF1bQA2sBbDshEoOfS6BtqAm5Fw9s0jQJ0tIGI4absygaFL1lF/ldvWtGbggQPvGxOxJ7stEz7kRUoD8IT3lFEY4uzxWvt0Guk/JgWspbDMesuUzdAK1HlFYCv6T/uC1KArmtjdVHRdu5emvzO3IH3rTU=,iv:DC3qqHIcRGzocAEzRwHt+YrGhhxgN88sIJQCp84Y6iI=,tag:uY8lNgMbwMaXZmCmf4gKlA==,type:str]
    version: 3.13.1
