apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-romm
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 4b3d4d2e335575abc71d0daa3adc5660a9d9d6841afb564fffb952a29c1dafea
spec:
    secretTemplates:
        - name: media-romm
          stringData:
            auth-secret-key: ENC[AES256_GCM,data:fA6lTdBmlY8KU6KjH6D8Lk1C0PxEltSBzbE6DPyO9o7CqHE3sBE0/l713a1qSnlJKeEWfr7dF9Coq/ILcp+8vg==,iv:tq476YyMSCXbVCJBj6Wy+ctyYmepF7eTc6CjAy4heR0=,tag:+5ND3JEmCMc8DNo5klxKQw==,type:str]
            redis-password: ENC[AES256_GCM,data:T8pJijw7l4q5eE0NRLml9FPS8fHN/POsL7TUjP6e4DP6fgT94Q4wChJz9i1qcIxf,iv:HMU7YNA2d8pBsNZ9WwOYxsXv9wInyV/s/qoXvKU79J8=,tag:mA2DoRE5/S6FUd9kzwqqGA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZzVEVGcvUys1S1l2aERr
            c29YK3EvbUdMRjBwVkUremVzaXBhUHZkVlZNCnN2a3pVZjEvNkEwRk5QdEJMY0hz
            ejFoL083cmdyMWtnWnpiN2RyemNMRUUKLS0tIG96NzAyQ1d3a2NlcHQrZWc3ZzV0
            VzNMdHEycXJNb0ZKdXFXTzRVL3ovY2sKcCxBRJFxVMD5A5LLH34aEBEcHeaitIDk
            ImWkuoURZlwNPuFOp0gCidTIlBwubeqpKeZDKu9znhxdNO9PUM0NZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T21:47:50Z"
    mac: ENC[AES256_GCM,data:bjSz80WwDN4jWMTL2KAfn5VYNu5eNDk5lWb8dtnf2k8Qo23AL+MQW9eWD/+K8ngI9/xYmVkt6ReCCuTDc10zpV00IHzpgWgdpwn7oUZY6vDvdLE/PVE0vMpzalEmvm6du5Ojfg8WjD1axc7BX+VFXc8BrSmBUXD8myw2Hm+cxH4=,iv:TQqFhJrkTmUAoKIIP3nM7iS3dPkLJEoSjOKmi17SYBE=,tag:1QksRM+GG2K8BeXgHQjBZA==,type:str]
    version: 3.13.1
