apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 9ba1da9c5ff96f30596d5bf237f9744d69f128bd2a4f1c77a25d2fbca1d36072
spec:
    secretTemplates:
        - name: romm-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:aj1tn7h2cbUAVRfuXcs5WdftbCtgd9DAuRsezJV3apOuXwXc8g/FDVSmONObmCr1C62l6RMsVB7vwBSXqYbecnx2sfQtChQF,iv:DPL52x9rUVSxReSc14smJObc4fKrrQJgmtZTjFnjhis=,tag:H3b4ECr8k1NoU0ln3xJ0rQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMHpuMkFML2RHR3k3V1Vw
            YVJJVnNXb054Z1liV0FTYWZVbmNRcnhlSGtvCjJoRG0wTi82Q3FkMC9jWGRWOEIy
            TlZWaEZjUWVZVjJxdkNzakpmL1ZZWlUKLS0tIEFMUXR2SUN6VGxVWXVybUJkYVZW
            VXpzc2l2Z3FmaVBaaTBuWnRISWQyamsKdcy8XVTFHeX21SqcSaBU2y3kRqfzk/48
            nQy4HFAehk/0T17RzMBL2DV4UMUzglIMJOs2omyjw5BfsclgfMHPrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:59Z"
    mac: ENC[AES256_GCM,data:IObJ90A4iqoVS6bZwx4anbZVJHeihke9e+WIMi71uP2QP0DjLgRZ8JMPJ/OsZf05fvW8Kj25nHxBk/Pf2gwO/qaL0SAhbx7vLOPw9s+8hORkLfoy1i+Ic1Z2i6XPUyxCEZkrwkYY39+kWmzL70hN2kX/rqqLRsbR5ONVTpBLsTs=,iv:GCE9A5aXGXKREWdNAhzNnaFmon9VxTJmA2GoY/wQISM=,tag:letjQIN7mA4VYFRqda6ujw==,type:str]
    version: 3.13.3
