apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: a8718c624db12597eb542b3f9912d20166c879c6aa51de0ed9ef0e090935153f
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN3AwWkFHK0ZSQjZjQXkv

      b1JTWUwrR2NIK2diRVl4by9PeXltdXA3QXpzCnc3NjJmTDFQVGttNCtBVDlvZFY2

      d0h4eXdHYjQ2QTFCN3ltTjJKVHlaU1EKLS0tIHplbExBSnFXTkFGQzVPMklnQ2c0

      OFQxTFl5VWdvZndGQ1JLNnBEUDNOeEkKml+vPsBQ2edSXIy3kICLw+zsU0sZ34qj

      maOgTpOuPaqSPlvPalIo6DA+XvcGGk+VYDteI0CizHtVSGVfo3lAQQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-16T21:53:49Z'
  mac: ENC[AES256_GCM,data:NOdGY18MWk4+XnIiWAjPiPe9GT7XRcmE7DS6KAyb3FZgrX2D56ty1Yo8CPJ8spxgbmY+Y/gjgKY+iZlw+7Maqo+UR36a7EDfST6CdQ8SH51h2+T5BFVdmgLHnaLP70tFmZMB63BwvBHMAvcq5JS6LsS1RIeiwzZemc9PDcOYK1o=,iv:BVu9kk2uWAJbDJRDpgIaZ0urm5vE+yB/gI7tN9KD+x0=,tag:tpnyHh2emS3Y0nftND8KrQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:sfJCMVnmZdxCRHHw+p73ceMo1QZbrMSSqM6Iso+ZwsXpMBJ+qDUkuFRjALKPPWlQ,iv:2UQYkpBhczWmdowLalS+j/O7fQP9UwqtqIWJFO5dzGw=,tag:NrtDUiM9+EWz/QxKqOugGA==,type:str]
    type: Opaque
