apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 1955372c933e1fcdfe8002aaee8735c828f018d88fd2ea548af5fe1e5f6989df
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1VzUTNvalNTVmprYzMx

      b2l1QitvYXg0OWd5bjFnaVM4RFdNbEhGdkJZClgyUUtnNmYzbG1nY3UzK1o5N0Ru

      QlBrYVZnd1lzVmtuaE9YenR0eXJmRFUKLS0tIExCTEdzcE1CaC96bGladm83YWNq

      Y1NDbHdDQk9KMnhidS92bFd0dEpldXcKOFl7NY8wVovC6IChoYU3tK0oZX3NcJsV

      GhEjSrvr4z4QnF+1GZI9PpdBkKi5O8mYGqgimYBNuYSXHLuNJJM2mA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-16T21:53:47Z'
  mac: ENC[AES256_GCM,data:hvjnkOMWNEWGnpWzOAr8MEvOVnH2AhPqKV0D3gzum7hmBN2KTzO5sLMLO+TxfPqpciTyseJkBfup0a1x1peNlVL+tYK1JLTJre0GOYzuyDdWOcTbxkpCbLtDbPpsc5NHcRd5gA1i0Nkpv9XxTQvTA1U4pl+oqx8RfjXCnHmN7kA=,iv:d3hhGa5wj6y9QurrW08PTX439UC6xPM2nMuqgldcMgU=,tag:txxdmWA3UJCpY6fXYRAF9Q==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:ktGCDAbf+4ciDgVvv1cQOrm9PpBhWEPiMVVm/oBO+rPEWWdKpbIrbt/0eifenrJoVQ==,iv:lHh2Js94KkvjdZrCRnu6z9fI7I13iSlawCZnaCp7eVQ=,tag:yzU2613jTWJ8K3LoENMkGg==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:phb1m4msAe7ipHFHsS9xgSkTERB4ReAAtgbaGVBktGTBy9HeuINohPyzLMbSUYR3zyIo3inuZUDn96Q2waVk8u9kI8rwGxTR,iv:l3iLaNLXASfo8LzTsjSUnD/2BipFinwpKxNolbBaaTI=,tag:AJ8XJpSCbGWYAzXYO3XDNQ==,type:str]
      server.secretkey: ENC[AES256_GCM,data:udFeIVyy+/+YoCmM9uikia34n0OeieTQ9MysdWxG0zg5oO11k/ZhbHvaj40=,iv:d4jAW34cJJmCz8pAdH9dJPFvQgR9E49irku1TO2mnds=,tag:qbPGn6XAqX0U/W+aFui4nw==,type:str]
    type: Opaque
