apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 9fb462381f2837b319a43dc08f1be786abe6383f0dc0de4652c8ead3ba738794
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWm5wK0NLRnBINnJCRGF3

      RitLU2U5bkVVYVY5VHJMdFhKVzZqTVN6WjFjCktibUpnK2pFdVBFMTdiamJ2ZGhY

      R0lXaHNiN3lqd29IdGl1RjJZZWNvNXcKLS0tIHovU0V0QWhKYXNZZSs5V0JCR1lu

      N0hESWxDK2EyNEdiV1AyRWY2OUhOc2MKkveUBiXjP6JgDI0m4UDzFttkizRo1+nk

      U3IAfdZmlth/A9tdIVdPQ5WZZRMQ641ulhKAS3gyv0n7mTEnhTbG0g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-18T03:33:28Z'
  mac: ENC[AES256_GCM,data:r4QNdcpebIh0tbpUtX1UNAkghS2CuxD5dwfDI4rVuvubr7oWIdR3hbCvSsYqVzBzO4ZxfmNpSVNkTyJRAR5GGIH1Zrs916gB4xlwVpuG5wg0uwFMr9WMwnj27zxzmT4iuKJCqi4CkvKsrfqTVfg5aEy7NVRmV8XtVFx4UoiVbYQ=,iv:lY3gAlhypxrKjZ/pcIc9GsGsxnnAACBVGWxdfN/UNuA=,tag:Hr1+bGGnNoxcVwESPY13bQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:yRQzZiLjWC3qkW8IE9S0f/lIUgBpIiWE/xacmfpQWcCB5QH+xIWY9JJ9bYpwn0e05A==,iv:tvuXCiIzZo/e2zqJPN3fRYGZiCblBu7wI70qciJRges=,tag:UcLM5x8keMDxQGFRvzszEA==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:cYy7OU0sjgUZCoeGlPYdtnOmscGnAw==,iv:LgZgtGFyXXHPJkoTov2QV1utdziWpzoPdeQUf/8arrs=,tag:tPIdJ22TNVay8fBOVUlbQg==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:NArmABGUe9tKMivYcbh1p9ONSkCYNrLw5Aw5ETUqLYvc/hXMh3MNzJiiuVV4R/banQHZDtSbkkiyFa2tl65JmehieoRuUSWM,iv:Gxb8NOvu+F3NQ8X5a4wr68jZFvlS/hYeJQPECY1uz9E=,tag:gqspycnPMjDTCHc/ALWXzA==,type:str]
      server.secretkey: ENC[AES256_GCM,data:yD4/apvH2evUbyyNZqOSWDZkBNQ5s6Q1mWPoHVY/JSAUkbs7wf3Bj5g6ww8=,iv:cUnYAYTUkuaqfsWfVvSV0nF86GYiYFcCLtsKHC2yhVM=,tag:OiQlg2CCSd3RkGnR1yTAYw==,type:str]
    type: Opaque
