apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    annotations:
        secrets.json64.dev/plaintext-sha256: c380cde02455e046c9ff20f979b743cdbfdaf629664dae0053e4152aaf78b19a
spec:
    secretTemplates:
        - name: argocd-secret
          stringData:
            admin.password: ENC[AES256_GCM,data:HinFPxaWZWczhywBW2TB/k98wNRoDSLrWh3qsdD+47yrFARliv/Ebrgu1YQH12I=,iv:uIKbSkV6nBarcfYqi7DxBFK/QKbwM1KvnwSNNFDrTGk=,tag:LIb5TFgk5tFQkoLo1ruEMQ==,type:str]
            admin.passwordMtime: ENC[AES256_GCM,data:jCt2lw2YLcwRTgu/9R3e3oTEU6jASg==,iv:B+t2F47cgr+hyZ8JsQt29yVpAMYYJPBFSny8aNtBDdk=,tag:Qjcqgg6Ttzg7JWPpyf9Hhg==,type:str]
            oidc.clientSecret: ENC[AES256_GCM,data:wG993eCk3HxtKFm+agp1ZrUTduWKVvHbKYDboI4W7FQPp+821TXQFJdRjLMqTKd9ng3w99HmYd0q6Lxpcw2/yBb/r1G3St61,iv:R7pGoWao81ogLjlNuko3UasJqN6Da9IxSeUBagBnr04=,tag:5splA7lWc+sC3WwFhsNULw==,type:str]
            server.secretkey: ENC[AES256_GCM,data:BL17uzu5kz4UFBiK82fcOpWT4M8ztIEBTFYxER6dgIz0rZMCuPlN/QZNg7o=,iv:CSzfPWFl56jF62H/GO0Vb56d9Wmq+cnX8nwp2Q5FpfU=,tag:w3WhkwySd2w9selaV7Jrkg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UmtsaGRyMDhCSTg4STZk
            djFCVUlRbnZROWIwTXAvdG51MzdHVGI4bmtJCitqbTNNS0taNE8zWnVPYVhGRnp1
            aE5iMDc0dWVpTmRONzExSkt4RUJtdDAKLS0tIEZDYnFXNC9RL00ydnAxY055ZjJX
            TUFzOXV1ZXNwd0Y2UlltemtaWDlpdTgKSd2jDo4zcyTkLoO32U4ssmCdF1gAyHDY
            C+X7NcGBjDD7psGLY/vBR7dXU0sIDwXPYk3NiKTCgbyzHaDFQBOyCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:52Z"
    mac: ENC[AES256_GCM,data:sxJ18k9Lxq+J75RxRdsq5KTeL0iLAvQvi+WKn0a6/XL5lwa1AxrkEzwKSwi6VJtoSYZ+azjGofEbgPfg+hzcPS+BeRsk+ci5/4xKjiDBiPhjepzLtRcafNdvRMLCa47y8G3JbXdnr9Rnh/sZiB3tV4V2pWDRA9LPDj734eKrTd8=,iv:kCSshBjV+D2Icr55WeEGRZ62I5C0Z4ZombIHGQjJgNg=,tag:HZ5MMnBcY2AvR8k1bppLNw==,type:str]
    version: 3.13.3
