apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-redis
    namespace: argocd
    annotations:
        secrets.json64.dev/plaintext-sha256: 2de718c4b2da9c9b7e33363c3bed6376ecf64224aaae4206a79cf7a8547f89cd
spec:
    secretTemplates:
        - name: argocd-redis
          stringData:
            auth: ENC[AES256_GCM,data:ZahtZclWGAYqqnBePp1wPoZ+ml7OMF2q2mxdlJxcNbTUx7NIeIoFlYvziOWd8kpr,iv:i4+InJH9USWlxE6O41rSAfUn2rzSAKdsq95mlvcaz1E=,tag:bw/OoHNCRzNAkuHzHJXyRQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQWdYRVRuWjlGbEZqYm0y
            WnQ3WU91Z21VeStaK3FEQXNSYlJUZ3ZLK21NCmx6UmhScHFaWjByR0V6d2hoZU0x
            eHg2RjRBcHhPTWNLMTZYcXZZUGxxYkkKLS0tIFhPa2RjMUxDbHlhY1dHNlhZWjFl
            czVZcXpMSGVsL0lPSFpQZmdkRlorRjQKtO6ofTiwKzAp2QtRMjDcgWu0bWhHBMkh
            tV/TPDdWTZLKSlONDhlkfQq4xN5xy9QHHuZJLRUIsQ3OVYzf4Id73g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:51Z"
    mac: ENC[AES256_GCM,data:kCxL1K78WGQY2ygRwPUQxzQgevQWMpuu2OTQ8wNLBuAf1rmrHx++yomxxU3tmxc1e9x4/IGGpPrVoUebKSMlbxkgp1rEUzBiPgMoZHfmSAiWMeT2Cy+agOdM5bRO0c6F+hN7NL19c2US0RxfrU2EY7ySPEb47Tfs1zLhGKiU8b8=,iv:U51Gji3dXLBK6gP6C4fOWP+uP0+8lrACl5Lovyk3HDQ=,tag:UKvESip+LNicImOOdQQSyA==,type:str]
    version: 3.13.3
