apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 6b451976cbd943ccaa91eb98f665ad1d413372bf9d569c7bc116cdd9754a6a9c
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cERGNndEZUZEOE1vbTZL

      YUdkb3lLVDZHWDdma0FOOEd3a0xWU05pYTBRClFpd29OdkROeTdYWWNQUWhIQWFQ

      TGprWDBjNGZ2MnhvOHRsNGJxRG9yR0kKLS0tIHZKWDYyaFJtNXhsUjFIbW1Qc1dO

      Q0NPUWlLT3h6c2t0cDdPVWZjLythUmsKAj/Dihv8I9I4v8bNRIib6b+2ygWo17Cf

      vwuWbjrd9iNdJtbe6p7HC1A6hnksor0w5cJjubSL2pVX4g03W3YsUA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:51Z'
  mac: ENC[AES256_GCM,data:1roXJQWJpRT+43BvP+5wdQH+3a9DAuIIBCO6yxk+3vjohyliZ9Y3Qy4gQHDnvGLb/cIPmSMtKhu7CVRSKMsHCGZceiJDhbQG9twdOaJcTwqI0J+gXZpXdy62XEw88vqw6C9jmekO0CjPA0vvt0VrhZ8g3MQ/bwSQAIkOS8lm1IY=,iv:ej36bhiUgJ4e7UKSwol0Fo/T7agtSegY2ICYsXolWcc=,tag:h8RrdJp4VllLVMkRmoP5CQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:JmRhyPv9ZX5Pu7kWAPasZbaN3KGTqx0qZFcPaA5ckdhZXd7dHJ+Cv734971Y4sVW,iv:2qtaWHNabKg5xaP6gpV3Xr9WWBDd3N8lBRPx/zV6MFU=,tag:Ijhi2ByQ2lAdg41Di8OdLw==,type:str]
    type: Opaque
