apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-redis
    namespace: argocd
    annotations:
        secrets.json64.dev/plaintext-sha256: 2de718c4b2da9c9b7e33363c3bed6376ecf64224aaae4206a79cf7a8547f89cd
spec:
    secretTemplates:
        - name: argocd-redis
          stringData:
            auth: ENC[AES256_GCM,data:qKQg6UiyWbkTf0kOcTYcy0fBW+OlbaK5+1T86/qNDan3NuttSQ4bqCxyphE4WUCM,iv:Rvm9a2pegZYfvL4e5QoVyjiHx22xW+QoJM/Pltm5e0o=,tag:VNmlC1PLdQUSQWAbJfhohA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmJid0h5RlJwTUZXNGVm
            YXBqTHBGMDJBTTY5Nzd0WVBzdzZ5Mkw2RUhJClBSczRzTEJxdit2ZmVLcXhTQkUr
            TzcxNUFxNW1qUlYyOUN5eG1tRXVqVE0KLS0tIElIeXRrOC84WnRSQ0RETGpwUVJh
            eGcyTTlUemt5OGpNM2hhaXhvN0h0d2cKTpdk8yPzCbfhyCfKaWMlN2bm4bpKvnFN
            h8rmhsKps4/0su+bu57mJiVP1edfgnZc4Yi5cAiT+nAoZcdHlxWiwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:45:19Z"
    mac: ENC[AES256_GCM,data:k041/S0qc7DtBtR+1DbGctie+nhG2CekCIIMXCVZphfXkrJQKUQzEvV+4jjSYWA43IQfO4BFvmR1jMIFsIMCLsr8z+Ml7bXUt/j0G7e+AE6d7GY3QZ3bmlc0DzBS4YIIz/ph2bkeG0h8L/Z/2DrDtpzwLmSUzU4F0U03XLOJCFo=,iv:CRk0j4OLB5X8BBJoaXu6FRmIkssCzg0B5v3mTCpk7vo=,tag:O4KC/cjLsq7PkQVekuhWjg==,type:str]
    version: 3.13.1
