apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 4b56224be52625bcf20edbe8904c94762be788471dbf14ccc8f417170574a893
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1NwcElKR0x2QTlkQnhh

      b1MycFM3Tld2VGt1V0RMQUFuNE1UdnFGYVNNCmJzQ2paV0M4U05NV0R6dWVxS0xO

      NlYzZFF6UGpHckVQcjNLelJRUENPK2sKLS0tIEl0V3AyUmhXT0kyYzJHZ21jeGcw

      M1VoMCtvcXZrTkR5R1pac2pKN2V2ZkUKpD6bkiVftICeQIaW6+UAENrO0IIfLslz

      cwPZkhrF/boncGLZoAfPobEvPjUYOtMlTATZ6aoCaxHXNgePYr9V1Q==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-09T16:55:04Z'
  mac: ENC[AES256_GCM,data:As2UrIBHw9ZiWpOlSktEGwpfbyElVe2QePq3OtLsb+5EzIJG6c/Zoumyg1jr96CTHl5KIMTQl8kpzbd8LtFrHr2D5HoivPctKLq5bQaUh9mdkHeYF2l9ym64er7wTLnSAQDjQeG8ucTe9SyZ9Q5Qmf1rZ46uhL5JXgHXX8RtS2s=,iv:ndgZPv5w5PQKYevTE51IjiWi+zdBp+1b79Cxmwh2xEQ=,tag:pa3Moo6FwvPhBg5RROQzKQ==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:AMGhbJfev+l4Nev2DBTa4JqmL6jx0r3OmDQ53Ld3wQZYbBfDA60+UMWY7+pYcx4=,iv:D25VvNgjZYJnEQSHoM+WYJJexCt9cwQoFoLm4IoelzQ=,tag:VDTJETQndDo0SkBQWf9KVw==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:2EmYDwmoeAZ57MNo76x4MwZLtRw3EQ==,iv:C8KyvQ7HVPgZkqtlhpx4B+xI/DHp3V1UqrCPSx4KOEs=,tag:2qLEey2yhCtnxmDriVZW9A==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:DDPjDyl+KO62JBrrcQc/U+q7Wdrnwmvon0ZBcHv3Ujw7vvEaVLBXLbQtQp/cm+0XcFBbTVU+Iy5o/4n3DGQGNfG8dmRuVsvl,iv:Amg6Yap6yb4DAO2ysTdDZdFJu35JP0z+jQv0eekntqI=,tag:uZ2i2y9hiog8tNzafV6rKA==,type:str]
      server.secretkey: ENC[AES256_GCM,data:2R5b8hyaijBCmDN4ZJYpw8yq5NtCPdsysGO5hBqJ6LfGvCTUD8A+p2nPAwo=,iv:GXq8wiFuaarci86+eYHHNLYv6S+TLaZVxY/0FjF1m2k=,tag:gLBI6ydMHuGg/4HdoEAYMw==,type:str]
    type: Opaque
