apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 4e3067d00ce044f16ad5d2e4a9116e6f92c61b0f5dd1783aa127373e824bffec
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOEFDNGN4emMwRXZBNkpn

      SzM4a1NZUE5zUWZiVWNJc0djdkg3THVrQldJCmtJQ3hHUEM4NDJSdEUvR2Y1YXZw

      YkRiNFlqVFFCZzhHR2ZGUjM2WHFGdFkKLS0tIHJYcGZqQ00xeXJHRjlqRHdjVHUv

      SXpjbU1QdUo4ZWdtL1JDMitLQWpLT00KcvcEZijYipVg18K1qxKk513iAcoRm8er

      wAJmeTrmKWIqrg9TfAhRs7tpjF9tH+sAuH3Ih3Qu4ntxBE8bBdukjw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-05-30T20:30:36Z'
  mac: ENC[AES256_GCM,data:o0Hrz/dhf3DBGFKCG5/HRdURdW+oHVe9dEtYkQCb7d1nglgluN+YDhVqE/MPHzvIt5LvW95pO2HzL6Ced3UoNMhHmPGh702m5pgwOfRPyWhxVygrDJMwAIOlOD78EWpRcAHkgDDQd14RRBEfKngfAgJ3dcEg6Q+pwUiIv7jM8MI=,iv:JiOgsLl0knq+WYI2r10rqk2gT85l9q9x3Ynej/8E2fc=,tag:MbDc5BSxBhGxVDUpDlYnhg==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:riWlvYlE3Ybrvws9ZSmNNdmddxH1uEeN+g==,iv:3SXZ2V0k9avYfzwqsX0dAzTQKSOph0uFudzjuCVIW8Q=,tag:5rM+tHUlZGp3soU6Mm7syg==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:TlCEzudM/COUGXY3+QG3OFW1ism0EIkCZTREIH2zxA==,iv:gi0ovYokeYycogUynzzkuMcWqv4CdtJzQvYnq6buuL8=,tag:BVuLhpKlgJnLyY5oYN6UQg==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:/0kLoewJqtiBfFU2JuAqvlIEYgy32flCOEpCGr1hRjZV,iv:y/fJJsGtNOQ71CWRntW+ZXwypYEBpPf/59+xp4MBWpk=,tag:UIhKF3J5OJKFO85zsk6C8w==,type:str]
      server.secretkey: ENC[AES256_GCM,data:91OU6rn9q4S8BttLsxBxK/3vrO3P8JDHbg==,iv:5H10Lw1MuKzve016M9+m4C4dKvcUlMX/swea91cT3z8=,tag:aI5sGYTvxFflF0DX8+D9Tw==,type:str]
    type: Opaque
