apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: allow-gateway-uplink-nginx-egress
  namespace: gateways
spec:
  egress:
    - toCIDR:
        - 10.10.10.1/32
      toPorts:
        - ports:
            - port: "8444"
              protocol: TCP
  endpointSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: default-gateway
