apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 12f93006b52b7c5e2cd7699bc256a5c585b60bbad73bc9b256ae7f93e9a2a9c5
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL3I1QnhMU2JZclhPN0ww

      cnRLQzZ6YjRuakNIYldjY2hjeTFRNEo0SUgwCnlOYlJxbGsrZWdJa0xsSzBUYnVU

      czJweEl1VkJCdFlaWG0xYnJsNWpsNjAKLS0tIGd0b3llcnpERW1RY0prWFVLYXBi

      ZVltWUo2SU56NGRGMlFRMElDS0V3VlEK+z2gjx98yOUhLTwa8PpuGMW8Nx80EwbP

      vQorfWbVXB6wNkCZHq64yRai5BuR8Fm17o83HUMesjMAml+cAd9+3g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-01T18:27:48Z'
  mac: ENC[AES256_GCM,data:MwCEF7JhMDqtGiR2u5npqIQ5rL2OaQho1k18XJNjigskGocDpw2ZisCdoVo97Aow3mRHbLQC2RvQbpPnhG6IlzvOrGW4hDgNnzNt5ss+NDmM6UxfVix1QHMzxqZAgmDBtM50upWPLkEaz4QHTs2F4pOPDakITchBcBHw5aKL14s=,iv:ENB3V9Mt3T5fDmpbMupKjsqE98fh7vR+RoB01tdolTg=,tag:PQNjG76ovYP7qaQtq1JfeQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:k+b6bc+fkBIFs3nd4KlLva35COW6rByoKBIlcGi4eIHL2NmmuyacHzaAvrPRYlmR/SaPQe5fjhkbfnso,iv:yWm6TT7Pr9Q87AaBcM5frk3PV7TaTkgkdI70qxDpvT8=,tag:iPhap41p7zkQvW5WK8qiCA==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:Zz54yLyO9V03GA9xs4oybBi0enaCgQ==,iv:M1AXyPGXLFD2gdUTJSm9hKgtmvjw4GAGRHC8ASgmEdY=,tag:P1cOOL7w/RdTEwlNb0TJ1A==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:awv/hmLm1w4oEX5sD2OhztLfH/bimTCMWdvGgJ9aerTXyzTrIdkL+B5+C20CbapdfWRkRMZw71YR4qY0iGpVNQSuWC1U3g30,iv:E/J4CqVvcl3JrN3zsK5QNhsLkCjNoyoigOmo3D/1yoE=,tag:j1N434sqhuusgUZ/dIcYRA==,type:str]
      server.secretkey: ENC[AES256_GCM,data:fmWmfBHRnfDdDR2D3QaTB3acw0fuVWJjmlbWknr5AG+uKDiAXd94koLKqAI=,iv:gUkvCc/ffExoJr+xE4A4FpDM5giW6q9Z2efpOG8qRQE=,tag:5fVcb8R5ItBv/OLQ8cKZDA==,type:str]
    type: Opaque
