# Resource 1: A reusable peer configuration with only the required address family.
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: frr-peer-config
spec:
  families:
    - afi: ipv4
      safi: unicast
---
# Resource 2: The main cluster configuration.
# Defines a single BGP instance that peers with the local FRR daemon.
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: frr-cluster-config
spec:
  # Apply to all nodes
  nodeSelector: {}
  bgpInstances:
    - name: "local-frr-instance"
      localASN: 65002 # <-- CORRECTED FROM 65010
      peers:
        - name: "frr-on-localhost"
          peerASN: 65001 # The single iBGP ASN for all FRR nodes
          peerAddress: "127.0.0.1" # Connect to the local FRR daemon
          peerConfigRef:
            name: "frr-peer-config" # Reference the config above
---
# Resource 3: The advertisement configuration (tells Cilium what to send).
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
spec:
  advertisements:
    - advertisementType: PodCIDR
