apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: frr-peer-defaults
spec:
  bgpInstances:
    - name: "frr-peering-instance"
      localASN: 65010 # Cilium's ASN
---
# 2. Override for axon-01
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-01-override
spec:
  nodeSelector:
    matchLabels:
      "kubernetes.io/hostname": "axon-01"
  bgpInstances:
    - name: "frr-peering-instance" # Must match the name from ClusterConfig
      peers:
        - name: "frr-on-axon-01"
          peerASN: 65001 # Your iBGP ASN
          peerAddress: "172.16.255.1" # Connect to the host's loopback
---
# 3. Override for axon-02
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-02-override
spec:
  nodeSelector:
    matchLabels:
      "kubernetes.io/hostname": "axon-02"
  bgpInstances:
    - name: "frr-peering-instance"
      peers:
        - name: "frr-on-axon-02"
          peerASN: 65001 # Your iBGP ASN
          peerAddress: "172.16.255.2" # Connect to the host's loopback
---
# 4. Override for axon-03
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: axon-03-override
spec:
  nodeSelector:
    matchLabels:
      "kubernetes.io/hostname": "axon-03"
  bgpInstances:
    - name: "frr-peering-instance"
      peers:
        - name: "frr-on-axon-03"
          peerASN: 65001 # Your iBGP ASN
          peerAddress: "172.16.255.3" # Connect to the host's loopback
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
spec:
  advertisements:
    - advertisementType: PodCIDR
    - advertisementType: Service
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
