# Resource 1: A reusable peer configuration with only the required address family.
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: frr-peer-config
spec:
  ebgpMultihop: 4
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-bitstream
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bitstream
  bgpInstances:
    - name: "local-frr-instance"
      localASN: 65001
      peers:
        - name: "frr-on-localhost"
          peerASN: 65001 # The single iBGP ASN for all FRR nodes
          peerAddress: "10.10.10.5" # Connect to the local FRR daemon
          peerConfigRef:
            name: "frr-peer-config" # Reference the config above
---
# Resource 3: The advertisement configuration (tells Cilium what to send).
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: PodCIDR
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-service-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-ip-pool-advert
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "CiliumPodIPPool"
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool-routed
spec:
  blocks:
    - cidr: "10.12.0.0/16"
  serviceSelector:
    matchLabels:
      ip-pool: routed
---
apiVersion: cilium.io/v2
kind: CiliumBGPNodeConfigOverride
metadata:
  name: bitstream
spec:
  bgpInstances:
    - name: "local-frr-instance"
      routerID: "10.10.10.5"
