# -----------------------------------------------------------------------------
# Cluster identity & K8s API access
# -----------------------------------------------------------------------------
cluster:
  name: dev
  id: 2

k8sServiceHost: 10.10.10.5
k8sServicePort: 6443

# -----------------------------------------------------------------------------
# Service handling / kube-proxy replacement
# -----------------------------------------------------------------------------
kubeProxyReplacement: true
socketLB:
  hostNamespaceOnly: true
localRedirectPolicies:
  enabled: true
l2NeighDiscovery:
  enabled: false
# -----------------------------------------------------------------------------
# Datapath & BPF knobs
# -----------------------------------------------------------------------------
bpf:
  vlanBypass: [0]
  masquerade: true
  lbExternalClusterIP: true
  hostLegacyRouting: true

# -----------------------------------------------------------------------------
# IPAM & Pod CIDRs
# -----------------------------------------------------------------------------
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: ["172.16.0.0/16"]

# -----------------------------------------------------------------------------
# Routing Mode (CRITICAL CHANGE)
# -----------------------------------------------------------------------------
routingMode: tunnel
tunnelProtocol: vxlan

# -----------------------------------------------------------------------------
# CNI chaining
# -----------------------------------------------------------------------------
cni:
  chainingMode: portmap

# -----------------------------------------------------------------------------
# Masquerading (SNAT) behavior
# -----------------------------------------------------------------------------
# This section remains correct for handling traffic from pods to the outside world.
enableIPv4Masquerade: true
#egressMasqueradeInterfaces: "enp2s0"
enableIpMasqAgent: false
enableIPv4: true
nonMasqueradeCIDRs: "{10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
masqLinkLocal: false

devices:
  - "bond0"
  - "eno1"
  - "enp2s0"

# -----------------------------------------------------------------------------
# BGP control-plane (for FRR peering)
# -----------------------------------------------------------------------------
# This is all correct. BGP will provide the underlay routing for the VXLAN overlay.
bgpControlPlane:
  enabled: true
externalIPs:
  enabled: true
loadBalancer:
  mode: snat

# -----------------------------------------------------------------------------
# Hubble (observability)
# -----------------------------------------------------------------------------
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# -----------------------------------------------------------------------------
# Operator & rollout
# -----------------------------------------------------------------------------
operator:
  replicas: 1
rollOutCiliumPods: true

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
debug:
  enabled: true
