# -----------------------------------------------------------------------------
# Cluster identity & K8s API access
# -----------------------------------------------------------------------------
cluster:
  name: dev
  id: 2

k8sServiceHost: 10.10.10.5
k8sServicePort: 6443

# -----------------------------------------------------------------------------
# Service handling / kube-proxy replacement
# -----------------------------------------------------------------------------
kubeProxyReplacement: true
localRedirectPolicies:
  enabled: true

l2NeighDiscovery:
  enabled: false
# -----------------------------------------------------------------------------
# Datapath & BPF knobs
# -----------------------------------------------------------------------------
bpf:
  masquerade: true
  lbExternalClusterIP: true
  hostLegacyRouting: true
  vlanBypass: [0]

# TODO: Egress gateway...
# egressGateway:
#   enabled: true

# -----------------------------------------------------------------------------
# IPAM & Pod CIDRs
# -----------------------------------------------------------------------------
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: ["172.16.0.0/16"]

# -----------------------------------------------------------------------------
# Routing Mode
# -----------------------------------------------------------------------------
routingMode: tunnel
tunnelProtocol: geneve

loadBalancer:
  mode: dsr
  dsrDispatch: geneve

# -----------------------------------------------------------------------------
# Masquerading (SNAT) behavior
# -----------------------------------------------------------------------------
# Masquerading configuration for tunnel mode
enableIPv4: true
enableIpMasqAgent: true
enableIPv4Masquerade: true
enableMasqueradeToRouteSource: true
nonMasqueradeCIDRs: "{10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
masqLinkLocal: true

# -----------------------------------------------------------------------------
# BGP control-plane (for FRR peering)
# -----------------------------------------------------------------------------
# This is all correct. BGP will provide the underlay routing for the VXLAN overlay.
bgpControlPlane:
  enabled: true

externalIPs:
  enabled: true

nodePort:
  enabled: true
  bindProtection: false
  directRoutingDevice: "bond0"
# -----------------------------------------------------------------------------
# Hubble (observability)
# -----------------------------------------------------------------------------
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# -----------------------------------------------------------------------------
# Operator & rollout
# -----------------------------------------------------------------------------
operator:
  replicas: 1

rollOutCiliumPods: true

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
debug:
  enabled: false
