# =============================================================================
# Cilium Helm Values — Dev cluster
# =============================================================================

# -----------------------------------------------------------------------------
# Cluster identity & K8s API access
# -----------------------------------------------------------------------------
cluster:
  name: dev
  id: 1

# For k3s or out-of-tree API servers, point Cilium at the control-plane address.
# Use the stable loopback you routed via FRR.
k8sServiceHost: 172.16.255.1
k8sServicePort: 6443

# -----------------------------------------------------------------------------
# Service handling / kube-proxy replacement
# -----------------------------------------------------------------------------
# Enable eBPF-based kube-proxy replacement. Leave ON if you want Cilium to handle
# Services/NodePort/ExternalIPs. If you only expose via Ingress/gateway, this is fine too.
kubeProxyReplacement: true

# Local Redirect Policies allow node-local backends for certain Services.
localRedirectPolicies:
  enabled: true

# -----------------------------------------------------------------------------
# Datapath & BPF knobs
# -----------------------------------------------------------------------------
bpf:
  # NAT engine:
  # - FALSE uses iptables NAT if enableIPv4Masquerade=true below.
  masquerade: false
  # Advanced/experimental datapath selector. Usually omit to use defaults (veth).
  # Keep as-is if you’re intentionally testing netkit.
  datapathMode: netkit
  # Allow ExternalTrafficPolicy=Cluster on ClusterIP (generally harmless).
  lbExternalClusterIP: true
  # Keep legacy host routing semantics; useful while iterating with FRR/lo-next-hop.
  hostLegacyRouting: true

# -----------------------------------------------------------------------------
# IPAM & Pod CIDRs
# -----------------------------------------------------------------------------
ipam:
  mode: cluster-pool
  operator:
    # MUST match your cluster CIDR (k3s --cluster-cidr or kube-controller-manager --cluster-cidr).
    clusterPoolIPv4PodCIDRList: ["172.20.0.0/16"]

# Native (no tunnel) routing. Ensure this matches your Pod CIDR.
routingMode: native
enable-endpoint-routes: true
ipv4NativeRoutingCIDR: 172.20.0.0/16
# -----------------------------------------------------------------------------
# CNI chaining
# -----------------------------------------------------------------------------
# Keep portmap for HostPort compatibility if you use it.
cni:
  chainingMode: portmap

# -----------------------------------------------------------------------------
# Masquerading (SNAT) behavior
# -----------------------------------------------------------------------------
# Historical iptables-based masquerade flag (works even if bpf.masquerade=false).
# If you flip bpf.masquerade=true, Cilium uses BPF NAT and this remains harmless.
enableIPv4Masquerade: true
# Restrict where iptables masquerade applies (only relevant when using iptables NAT).
# If you *only* egress via a specific uplink, set it here. Remove if not needed.
egressMasqueradeInterfaces: "enp2s0"
enableIpMasqAgent: false
enableIPv4: true

# Don’t SNAT traffic to RFC1918 ranges (typical for on-prem).
nonMasqueradeCIDRs: "{10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
masqLinkLocal: false

# -----------------------------------------------------------------------------
# Device exposure to Cilium (keep underlay clean)
# -----------------------------------------------------------------------------
# Expose ONLY loopback, so Cilium doesn’t attach programs to your Thunderbolt NICs.
# If/when you add a WireGuard egress gateway, extend to ["lo","wg0"].
devices:
  - "dummy0"
  - "enp2s0"

# If you use NodePort with direct routing from an external NIC, point this at that NIC.
# With devices=["lo"] and no external NodePort need, leaving loopback here is safe.
nodePort:
  directRoutingDevice: "dummy0"

# -----------------------------------------------------------------------------
# BGP control-plane (for FRR peering)
# -----------------------------------------------------------------------------
bgpControlPlane:
  enabled: true

# Enable handling of Kubernetes ExternalIPs services
externalIPs:
  enabled: true

# Configure the LoadBalancer mode. 'snat' is the most robust choice for on-prem.
loadBalancer:
  mode: snat

# -----------------------------------------------------------------------------
# Hubble (observability)
# -----------------------------------------------------------------------------
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# -----------------------------------------------------------------------------
# Operator & rollout
# -----------------------------------------------------------------------------
operator:
  # For a 3-node lab, 2 replicas gives basic HA.
  replicas: 2

# Restart Cilium DaemonSet automatically on config changes.
rollOutCiliumPods: true

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
debug:
  enabled: true
