# ==========================================================================
# Core Cilium Agent & Operator Configuration
# ==========================================================================
cluster:
  name: dev
  id: 1

# kubeProxyReplacement is the main switch to enable Cilium's eBPF-based
# service handling, eliminating the need for kube-proxy.
kubeProxyReplacement: true
localRedirectPolicies:
  enabled: true
bpf:
  #masquerade: true
  hostLegacyRouting: true

# For k3s, Cilium needs to know how to reach the Kubernetes API server.
# Replace this with the LAN IP of your main k3s server node (e.g., 10.10.10.2).
k8sServiceHost: 172.16.255.1
k8sServicePort: 6443

# ==========================================================================
# Network & IP Address Management (IPAM)
# ==========================================================================

# Use the "cluster-pool" IPAM mode, which is the most common and flexible.
# Cilium will manage pod IP allocations from the CIDR block you define below.
ipam:
  mode: cluster-pool
  operator:
    # This MUST match the --cluster-cidr you configured for k3s.
    clusterPoolIPv4PodCIDRList: ["172.20.0.0/16"]

routingMode: native
ipv4NativeRoutingCIDR: 172.20.0.0/16

# Required combo for native + cluster-pool IPAM
enableIPv4: true
enableIPv4Masquerade: true # keep true unless your LAN/router routes 10.42/16
enableIpMasqAgent: false
egressMasqueradeInterfaces: "enp2s0"

# This enables Cilium's BGP speaker to talk to FRR.
bgpControlPlane:
  enabled: true

devices: "lo"
directRoutingDevice: "lo"

# ==========================================================================
# Hubble - Observability
# Recommended to be enabled from the start for debugging.
# ==========================================================================
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# ==========================================================================
# Optional: Operator & Resource Tuning
# The defaults are fine, but keeping these can be useful.
# ==========================================================================

# Run the operator in HA mode. For a 3-node cluster, 2 is a good number.
operator:
  replicas: 2

# Automatically roll out agent pods when the Cilium config changes.
rollOutCiliumPods: true

# Enable debug logging during initial setup. You can set this to false later.
debug:
  enabled: true
