apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local cluster.local in-addr.arpa ip6.arpa
        prometheus 0.0.0.0:9153
        hosts {
            10.11.0.1 argocd.zeroday.run
            10.10.10.1 attic.json64.dev
            10.11.0.1 bazarr.json64.dev
            10.11.0.1 dash.json64.dev
            10.10.10.1 den.json64.dev
            10.11.0.1 garage.json64.dev
            10.11.0.1 glance.json64.dev
            10.10.10.1 grafana.json64.dev
            10.10.10.1 homepage.json64.dev
            10.10.10.1 hs.json64.dev
            10.10.10.1 idm.json64.dev
            10.10.10.1 jellyfin.json64.dev
            10.11.0.1 komga.json64.dev
            10.11.0.1 lidarr.json64.dev
            10.10.10.1 loki.json64.dev
            10.11.0.1 longhorn.zeroday.run
            10.11.0.1 matrix-admin.json64.dev
            10.11.0.1 matrix.json64.dev
            10.11.0.1 nzb.json64.dev
            10.10.10.1 oauth2-proxy.json64.dev
            10.10.10.1 open-webui.json64.dev
            10.11.0.1 profilarr.json64.dev
            10.10.10.1 prometheus.json64.dev
            10.11.0.1 prowlarr.json64.dev
            10.11.0.1 radarr.json64.dev
            10.10.10.1 registry.json64.dev
            10.11.0.1 romm.json64.dev
            10.11.0.1 shoko.json64.dev
            10.11.0.1 sonarr.json64.dev
            10.11.0.1 torrent.json64.dev
            10.11.0.1 whisparr.json64.dev
            fallthrough
        }
        forward . 1.1.1.1 2606:4700:4700::1111 1.0.0.1
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: coredns
  namespace: kube-system
