apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: glance-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f5c983a39c91502eb95b5ee74c6bd9452b2d2f6a69bcd24b0caf1e7fc8feb51d
spec:
    secretTemplates:
        - name: glance-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:wP78mzGu581xh9ldLNisSCbtwHQmpzN0NnzCZ6DDtk6hb7FyvS7tdLAEBJWkS/897NjOy8mZtryvwyygjmFMzBypXnUYf5qL,iv:ijnrTav32Yya8kIjHv64Y5H2/AgFU+cp3CNG4blDKeI=,tag:mzVgorlARxH8CpKaSxOFQA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYzZmd2hFS0kwenBFWFZn
            TGRnUGhRZnJhbysrb2F6NDNHTUY5eS9yUVFrCmRqcXZtQ2R2KzRLWXFrSUhQbUtu
            Ym12QXZrS2dYTVNIa0tUUDZ3SWJqQTgKLS0tIEZscmNpd3UwZTVVV2p2Y3RXdU5t
            S2x6ZERuOTVkSDlnemYrclUyMGZqNGsK+dkAWruSiIJ7rTFUO+iqm5q8a6gJPgrZ
            3tcm7z5/7zc2Aq5VFBD3HkN8gpJ6RenRq1jMj+WFrve0ttGMN1w2aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:31Z7ikqdLwXoXBIiI/fptT9bxmuHzDwpjWrLLxeDdjdzW5ouG0WihHVOl20rhECW7I/NBC3vWLuKiPfWu976it3fr6A7roeloWoTXdjdFigVrEEhcatgzPt7tfQ8t9GfcWQVpUBnIL+0O2UYJB4KLk7v8PAOk75EjweW0RCF98g=,iv:RdoHthYwkGOcizQPFqPdFpJQCJhH7zr3d6+voKUMHew=,tag:Q8TlBfezzuU8i7o/anXfOQ==,type:str]
    version: 3.13.1
