apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: glance-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f5c983a39c91502eb95b5ee74c6bd9452b2d2f6a69bcd24b0caf1e7fc8feb51d
spec:
    secretTemplates:
        - name: glance-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:2jhs24yDr2z2JiTNsl1nSMZUFJa2M5rZYnzf0IGdZq+MouybNA79XbGTwCpm9AgcuqBQQh+7HfYfgpzesi4iOlRfJJmB7RRw,iv:m72Wtxypzo/bo1rkjzsjdOO7NXl/Cwb3XLRnkFbnsTI=,tag:4kOefF36Tt8AaTc2KerzVw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESDViWkR3Qm9OZ2VOTTZE
            SVo5a2Z4ejNDRXpaUW4vd2dhb0ErZ3ZmdUFBCkk5K25sYktRQU9NUVR3V3lpMFRk
            UytrSnl6MEIwTCszWVJ5WGtTbExnL28KLS0tIDVJbWdNazZPSjlVaGRsWloyY0dt
            YklyalFtUCtCamJQNnpGUnRmejZZMGcK77aJjTDLJ5GknIXE1vR/CXLc3ekOorpF
            dEQVKzP71Iw+ne7qp6gIuI9GNr6XFWdHBNeapZFXjL7tg+EH8N7UWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:54Z"
    mac: ENC[AES256_GCM,data:mWZqzsfYLobAu8vZwwvtL0CiWBdcs9E/VuncBSwoRm2kxucdbDT+BHr9PsNchCYG7OuRRTj7EAcpQQZYwTbVO2lBCxthwF/d8mQz0XWw1bMYgs3pHkg6eHnameaMD1zIvyDKkpLvcZV5SFLvBNvo1lkaTMYuosUxjkT+VbacHkU=,iv:cnEQudMIccb8n3VeSfHsZ0Xx1QAA/fcQSVm2rwQqceg=,tag:sHOmDzIImI15YVVJWjYcWw==,type:str]
    version: 3.13.3
