apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: aed153d42afce4426a5633bb485d7a14e91a70a508ecdf9a5cc66528145a3bd8
  name: global-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ1daRlhEMEp6UmZ0ZVNI

      d09XNnlWa3NwMkkybkFlZ1pCR1lMS2JkeFRJCm82M3d0QWFTTmtQUUJEZzd5TTgy

      bDlqU0lpNnRhTTQrR1dHUjNOU1Z6dncKLS0tIFdkdDBNVFhNeUo1VkJXSWI2MEZK

      VlRVSkNHQUMxL3FXamVwU0F1UzdVbUEKUy9V+lwUbwlpWsyBUunayrUDdJq6GqI7

      Ci7kv/rcAyX5w1p+xhBMq+7vB5Xe8GNsfeDcMvKkHAqU930/vHMt4A==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-04T21:51:11Z'
  mac: ENC[AES256_GCM,data:Kxl/MNoucObOWDmJGXHGKdqweYgw70rRiGOftFBIK2ORzQkjluege0YhZ4rJPJMTxbfU98lKIlWgbAWDV8q6MGslKMeN3+mtYD3U6OxrJPeswjcCrM0rkef8lnKre64qMfzHaJxjGidT//+C7PhD/Ap0QjCeYt9CihUdB4uTWeo=,iv:lapPUEDN0Qd9sBb8REqGMh4L/AvEQwZXYsTkvP1Cr0w=,tag:O7Ag/iJALDZSFmHswg1nIQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: global-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:7MD8Qvl2UYzNem/3VgFSFGz24RDwpG03M8RFbBiYRP+vgUjh2tpHLw==,iv:CKAdIQXlnEFmyGOrb5hwVzRsdn5tLlnb+yQGOzdUOLU=,tag:56Tf/quAIpS/9jjmNRabmQ==,type:str]
    type: Opaque
