apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 31f1d784b431e18fdb2d51592527c28adbb28462e8b4e9f8a4df62aeb91a3dd0
  name: json64-dev-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSXZoUlFFdlpJUVZuUW5r

      U0VMN2IwZ2xNNGVYb283aDRyZ1VvZWc0b1ZnCkVmS0FIdU55cGFJTFpTRGJwWHpQ

      c2JuQzlHaHNDZlVOaEthb3lWVEgzalkKLS0tIERIYW5JRzdtaCtkblRrV01YRUd3

      TjIxNU96WGErVVo3dkcrQlZHaWE0cVEKFQCbaKb9P/HjcwMSlxXYzVUPMaT2R7ic

      7909vJXCjLL2VhKmfOGSA7S00Y3TG0AdaOCgypLuKi7aOX0qK2ytQg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-04T19:22:33Z'
  mac: ENC[AES256_GCM,data:JOTOXUNYwCYM8LAm+9tNlQPbWmfMCVyHpk5JLoJIvZ2B3II1Xeq8HvLab6twUaEf3DuzDuptcaxnoWK3JkHCki3r+TP3yj+ZK7QcFx0fG+Jrm57pxGowKUj5+XUHS0mgYb03XYTMi9xsPSKUwNIg1yx5BpGc+a9pvo5LnaZ9oJ0=,iv:NSGRT5Bbz2jr1ikoeJI1apIehXAEB8wwlQRpaE6iCRg=,tag:eRpxsEds3g2ziNUdPHkgoQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: json64-dev-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:AtIX1vhrPo52RX3z2tBjs2fs01Q1H9lRaFtLWo4ETjyYLfd03oXSMw==,iv:Ema1MUFisGbplLMtB8oH9iyWKEkaIq/OBkqC+JL5Hlk=,tag:9IC+hioQGZrJZgmQcPpXZg==,type:str]
    type: Opaque
