apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 2440a210f2f0a7f89a22d3290f3fa8524b15bf00464279e775a872fc84a08ff5
  name: global-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFkwOGJSallhWVp4YitO

      UlVHY2R0bWtBN0tGeHZpbXgwTjR5WURDeGtnClI5V2dxYmFiOVhOVzRLK2hzcEsw

      WDdTbHlGemZwbFRFcGkxNHNUZUZreU0KLS0tIFhQSVV2OXdNaEMzYzh0TXp4b0Fl

      bi9RVmxSbUhLUkY0VldJbVVYOHYrakUKk63k2ePSSkRyePJC93ShZrtXfYywEzbJ

      6EpXFaOji143cirxm4PcEHXgd73gGzZLfVQFrTFlZTZz9zY0LM5JOw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-16T21:53:52Z'
  mac: ENC[AES256_GCM,data:uDJbKamx4kw7Y4onE5YTOuvbTGTF1gc0xvsgxGioOviMi1jDj9M6QwBRx3w6Rvuy2+IOEY4kmvP5IGc19hk1r6bafR/7gCwK2DXIcCYG33rcrHkJnPAeDoNKGV96zie+NYdsbJEx5TjEk3DpmtCReaNHTlB5MusBjWjIwELITc0=,iv:U9x6pQzTCTDrIjru6j4G6vhHZuYmh4//dfsyhPPP8WU=,tag:LYeftbji4pabev0jThXlng==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: global-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:F4og6hMqOwtu9T0SIHH8beISIUpN5F2/bjsHw0w1txxesdHeNvnFvw==,iv:qnYEHkThqU4JCnpdDwaRb3EFYExPWiUQftu9euKsciI=,tag:DV9JPETemyWxjlYPFINcTg==,type:str]
    type: Opaque
