# nixidy defaults — cluster-baseline aspect.
#
# Every cluster's nixidy environment shares the same env name, ArgoCD target,
# bootstrap, and rendering defaults. Wired into den.schema.cluster.includes so
# it fires for every cluster; its k8s-manifests config flows into the modules
# arg of the cluster-to-nixidy instantiate (see ../../kubernetes/nixidy.nix).
#
# applicationImports (CRD resource types) is NOT set here — it is CRD/pkgs
# derived and injected by the instantiate, which has pkgs.
{ config, ... }:
let
  inherit (config.flake.meta) repo;

  nixidyDefaultsAspect = {
    name = "nixidy/defaults";
    k8s-manifests =
      { cluster, environment, ... }:
      # Inner module function: lib comes from nixidy's module system, so
      # lib.kube (release-label transformer) is available.
      { lib, ... }:
      let
        envName = "${environment.name}-${cluster.name}";
      in
      {
        nixidy = {
          env = lib.mkDefault envName;

          target = {
            repository = lib.mkDefault "https://github.com/${repo.owner}/${repo.name}.git";
            branch = lib.mkDefault "main";
            rootPath = lib.mkDefault "./generated/manifests/${envName}";
          };

          bootstrapManifest.enable = true;

          extraFiles."README.md".text = ''
            # Rendered manifests

            The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
          '';

          defaults = {
            syncPolicy.autoSync = {
              enable = true;
              prune = true;
              selfHeal = true;
            };

            # Strip release-tracking labels that produce noisy diffs
            helm.transformer = map (
              lib.kube.removeLabels [
                "app.kubernetes.io/managed-by"
                "app.kubernetes.io/version"
                "helm.sh/chart"
              ]
            );
          };
        };
      };
  };
in
{
  den.schema.cluster.includes = [ nixidyDefaultsAspect ];
}
