# nixidy defaults — cluster-baseline aspect.
#
# Every cluster's nixidy environment shares the same env name, ArgoCD target,
# bootstrap, and rendering defaults. Wired into den.schema.cluster.includes so
# it fires for every cluster; its k8s-manifests config flows into the modules
# arg of the cluster-to-nixidy instantiate (see ../../kubernetes/nixidy.nix).
#
# applicationImports (CRD resource types) is NOT set here — it is CRD/pkgs
# derived and injected by the instantiate, which has pkgs.
{ config, ... }:
let
  inherit (config.flake.meta) repo;

  nixidyDefaultsAspect = {
    name = "nixidy/defaults";
    k8s-manifests =
      { cluster, environment, ... }:
      # Inner module function: lib comes from nixidy's module system, so
      # lib.kube (release-label transformer) is available. pkgs is provided by
      # nixidy's mkEnv (used for objectTransforms render runtimeInputs).
      { lib, pkgs, ... }:
      let
        envName = "${environment.name}-${cluster.name}";
      in
      {
        nixidy = {
          env = lib.mkDefault envName;

          target = {
            repository = lib.mkDefault "https://github.com/${repo.owner}/${repo.name}.git";
            branch = lib.mkDefault "main";
            rootPath = lib.mkDefault "./generated/manifests/${envName}";
          };

          bootstrapManifest.enable = true;

          extraFiles."README.md".text = ''
            # Rendered manifests

            The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
          '';

          defaults = {
            syncPolicy.autoSync = {
              enable = true;
              prune = true;
              selfHeal = true;
            };

            # Strip release-tracking labels that produce noisy diffs
            helm.transformer = map (
              lib.kube.removeLabels [
                "app.kubernetes.io/managed-by"
                "app.kubernetes.io/version"
                "helm.sh/chart"
              ]
            );
          };

          objectTransforms = [
            # Rule 1 — eval map: k8s Secret -> isindir SopsSecret (replaces converter.py).
            # Mirrors converter.py's conditional emission (omit empty/absent keys) for fixture parity.
            {
              match.kind = "Secret";
              map =
                secret:
                let
                  m = secret.metadata;
                  isArgo = n: lib.match ".*(argocd\\.argoproj\\.io|app\\.kubernetes\\.io).*" n != null;
                  partition = attrs: {
                    argo = lib.filterAttrs (n: _: isArgo n) attrs;
                    rest = lib.filterAttrs (n: _: !isArgo n) attrs;
                  };
                  la = partition (m.labels or { });
                  an = partition (m.annotations or { });
                  whenSet = lib.optionalAttrs;
                in
                {
                  apiVersion = "isindir.github.com/v1alpha3";
                  kind = "SopsSecret";
                  metadata = {
                    inherit (m) name namespace;
                  }
                  // whenSet (la.argo != { }) { labels = la.argo; }
                  // whenSet (an.argo != { }) { annotations = an.argo; };
                  spec.secretTemplates = [
                    (
                      {
                        inherit (m) name;
                      }
                      // whenSet (secret ? type) { inherit (secret) type; }
                      // whenSet (la.rest != { }) { labels = la.rest; }
                      // whenSet (an.rest != { }) { annotations = an.rest; }
                      // whenSet (secret ? stringData) { inherit (secret) stringData; }
                      // whenSet (secret ? data) { inherit (secret) data; }
                    )
                  ];
                };
            }
            # Rule 2 — runtime render: resolve vals + sops-encrypt (replaces processor.py).
            # Idempotent: skips re-encrypt when resolved-plaintext hash unchanged (avoids git churn).
            {
              match.kind = "SopsSecret";
              render = {
                runtimeInputs = with pkgs; [
                  vals
                  sops
                  age-plugin-yubikey
                  yq-go
                  coreutils
                ];
                command = import ./_secret-render-command.nix;
              };
            }
          ];
        };
      };
  };
in
{
  den.schema.cluster.includes = [ nixidyDefaultsAspect ];
}
