apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sabnzbd-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: eddec4373e30fbf264e2f3be6dc255d01f0dfede5498a723906de0691f5b1d79
spec:
    secretTemplates:
        - name: sabnzbd-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:bLK6SkQoDFbVTzhoo3oThHek7voWMADkdENT6ImEvjW79R8SRaCzYT+tDSV5M2MLKMTeMK4e8icY47D0YAhRO3qxZZV2BP37,iv:sPlKwygYWL7PoSZf4K5oJJ4jBgqA0EoiMkahIN2ZUio=,tag:/BtVDhKcne6NNt7asiaBNQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVFNkN2FJUUhWRzBiblBE
            MVh2angxY2dpZDYvcG1rTkpxQ0ZZdHdQY1NVCmxQR1NzLzI4YnFaS3hsY1VBSDIr
            V2tHYWxaczNnTWVNbFVtZEU2T3BNV2cKLS0tIGJ6TWo4NGwvajVkbStHcEU2RzAz
            OW0vZ05rWXZBN3B3K3VzWjBjWko1bW8KFomQtIvigmr/41XI83Er6+vQUXZJhQa6
            zhljPUBSzIy3R356GRXQOLuaZRl7/sGIxmZ+kROfOYYtGuE5Q8jUxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:48Z"
    mac: ENC[AES256_GCM,data:8k8M/uJQq0+WO39AMBrST0KKnbG1/v7Vh9LhYXqnqe7V6KzdZAAxdRCaN7rTcVRqxJob/HREmkisKMaSEqfSykkrO0AYmV3nFGXpsOeDCL1ZwVn3dOGiQo9Z+bODm9ZmH5oiDLdTJpcGQmtaRpcIcZBlMtkWlfyJVfqzzyRCyVU=,iv:v6Se1iQ0bh2jBdzZ+/3hqt9P6qXI17I3rvA/PYK7xDY=,tag:D+jFfv0zBQrFx7AfiG8kIQ==,type:str]
    version: 3.13.1
