apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sabnzbd-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: eddec4373e30fbf264e2f3be6dc255d01f0dfede5498a723906de0691f5b1d79
spec:
    secretTemplates:
        - name: sabnzbd-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:ZsGUJLgO+NvdMIxRsfGN0YYtSfFBQ4Vie6jiuiEQM402DVFue6/kQbIy5S8doM0b5slDgx0OAF1g0ai5ZsIqBUW3n5biYXSE,iv:g3HqUtYxzhNfFLFB1HcuBKGcD7yFnvyVxV6rYkPfdlg=,tag:VEclVBnwC9nuO/0K9N6Abw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZanNObXczQ2IyQTUvd1M0
            V2pCVG5Kb2xyRldkZVZSb2k2S0VCWFo5bDFZClFJTWM5bGVZclpvQ29DM1p3TUZM
            L2dNZ0pvZXNLUG5QbUdNYmtnNzZLMW8KLS0tIDZ5eWtIaW0wcW11QnYyZkxZM2pz
            azdGWmJXY1MvL1ZxOVVlb0ZrMFEwU0EKYkt06zwTYAe7X8ET/RH4qUth/BGTvXff
            NMGZzoZWJ5y1V1nP2RYS0PV1E0E3XrBEgkApXSMhEIopDxhu2BdONQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:59Z"
    mac: ENC[AES256_GCM,data:Krn5uezGj8dUhay/v3siW6AY73l+XaPgphC6sruY5/crfvC0EL86F4i/w+XpcUwFtvyID8UbyycF2didUUT1v/vZvrkxx9noL2JZ70PGOw815QpBABaHFUJegMbVJur9tPzmt9PbnBoB/XQJ5UjTr7Of1H9ALWmcg3mSJlep0jI=,iv:m6wrNMn6ZB1zcFHiboT5sWdgYAv/qIwk6EyuStMSBGM=,tag:fhAJFWHX9MQWwZKN3KvP7w==,type:str]
    version: 3.13.3
