{
  flake.roles.core = {
    features = [
      "agenix"
      "avahi"
      "deterministic-uids"
      "disko"
      "facter"
      "firmware"
      "home-manager"
      "hosts"
      "i18n"
      "impermanence"
      "networking"
      "nix"
      "nixpkgs"
      "openssh"
      "power-mgmt"
      "security"
      "shell"
      "ssd"
      "sudo"
      "systemd"
      "systemd-boot"
      "time"
      "users"
      "utils"
      "zsh"
      "starship"
    ];
  };
}
