apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/name: ceph-csi
  name: ceph-csi-cephfs-nodeplugin-rb
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-cephfs-nodeplugin-r
subjects:
  - kind: ServiceAccount
    name: ceph-csi-cephfs-nodeplugin-sa
    namespace: rook-ceph
