apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/name: ceph-csi
  name: ceph-csi-cephfs-nodeplugin-sa
  namespace: rook-ceph
