apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    operator: rook
    storage-backend: ceph
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-ceph
