apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-coder-kanidm-egress
  namespace: coder
spec:
  description: Allow coder to reach kanidm for OIDC token/userinfo calls.
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: coder
