apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: coder
  name: coder
  namespace: coder
