apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: coder-provisioner
    app.kubernetes.io/name: coder-provisioner
    app.kubernetes.io/part-of: coder-provisioner
  name: coder-provisioner
  namespace: coder
