apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-oidc-client-secret
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: a4955f08a8ff7f1605aa18dcf6e963edfe9ba29045bfa0556858fe2d19060274
spec:
    secretTemplates:
        - name: coder-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:P6aW8KgIWyJmRUAgSn3FccaqCodjsgqXi0xXSL5b1r5laOAwB1YMhJSOZY4lBjlbeNeYH7HTaW5u11Ksc7XELF1SmzDqPzNZ,iv:NNfA0yQIVvhG/gxllGBicx5SO5k1uc4okweLJ1OaOWM=,tag:08tBU+T0kDVT9z6O8dLHEQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscE9hVlVFT2NhWG03UThl
            MUx0UTVYUXZkMW44OC9WMWpGZW9nOCtVUGlBCnErVVU3ZnZuQzh3VktqOUdjWita
            ZXU1Q2dqZGpIVUk0MGVDZzd4ZmtlU2MKLS0tIEFQcThwV2xYdWVZcG1qY2xqL0dt
            YWRNRXVZMVlvMGpxNDNTM1p6cUg0MzgKZVszhQ6ymqGvEZ7FaM7+sQsrZEaphHiG
            Z83O7NeVgGZJgNhK9uJYaCPC4fT7uI3lt4FgMCSAxgpHQzNT6yeOhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:53Z"
    mac: ENC[AES256_GCM,data:qg/u+88aWuu101du3tDf8IuR59xEvZNXZJBYWmrHllph2clnFCS3DDsZOEq3uHDrdu5XUrd3is0WB3zUwds+g68wdwGQOePGBMz+W2TjXgiuCxhKF1WomAuaOJ4tItQPyuMJrH5fY4nGEb+WW+Un2Q6v5kDcjJiOLTHV/6VfLf0=,iv:DPyiaWS6GKlaJsqiKM7OL+NAm99497VbT5wINSKakao=,tag:j2TCRN7JKuhX4aNZGayrYg==,type:str]
    version: 3.13.3
