apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-oidc-client-secret
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: a4955f08a8ff7f1605aa18dcf6e963edfe9ba29045bfa0556858fe2d19060274
spec:
    secretTemplates:
        - name: coder-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:GFwuL+dLVhMs7wf+TvYJOdkbU1DkmhQDxkwIDg+tpwJfwioxbEAmYkCJk9bAM20FKip1/GdsLx5IdiHctghHWSiXsMCobXb5,iv:IbAbJ7rKukyfI7KrLgGOejwNS8wsdg54ERe9Bn74BQ4=,tag:4VBCWF1EUDUOjZNdTw/OlA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeERLeVRJRmttSEUvZEJX
            YldZYklMTVduN2w4bjl1UmhoUnpRMHRZTm44CkEvaGNGQWszeFhhUnpwYXdMZGdC
            MDBRSExMNjlBQWRSL0tGaGJTYzNQajAKLS0tIC8xQ0hJR3VyZFZySm9JWE82MCtl
            aUVDNXVmYVJZdGtxWnl2cENETUtnZFkKfKKfKK6e6Bf7aawD35bVaaOOyTkjqkFf
            hEIKE2E/iZmov1Fpgl6uhdST/BLCn5m7EHJ46cdkfAoJWDTFF4WSHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T01:11:02Z"
    mac: ENC[AES256_GCM,data:3cJPYuVz05bjfSijKs6HSWVKnOkybNBD5uw78CrJErjomH8J1kbsUmvkxDada504DPJoIXuvhUKxQsUXCaynMQWtW98sHetWeuHoBIlcRW49w16RXGwfGjmdQEwX0RGDeNtVK5YBnEQrkdo/EQLukWmxrkRf6Ib9+ONktkC9SG8=,iv:QR5n3Puu+HD5Y/dfbr8+eplD9K7T0vx+4H66wl21WZk=,tag:Aum8057izmOUZgUP6GGz2w==,type:str]
    version: 3.13.1
