apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-provisioner-psk
    namespace: coder
    annotations:
        secrets.json64.dev/plaintext-sha256: 45d5c61d98d5246add3e86d240ebd47da6d1ca84217d279347fa43e6d3afc3f9
spec:
    secretTemplates:
        - name: coder-provisioner-psk
          stringData:
            psk: ENC[AES256_GCM,data:rol3JCiqZyRslf/8HjruarZot1sKVB0hJ7yN/LjhB1D8XOI4iurfcFQsZzmSAB4XKfUktDw2KR4tPVvwgpTWf9dxo+gKz6FX,iv:CYolMie/ttYBI8nQzN4vaKMzyXIvSXRkfDOoskuuoUg=,tag:YrufVCVfeNn8wsr848B9XQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYWRoSVRoMmVDdWk2M01I
            UmQ4UG1Dd3U0SThLQnBxT0QrSGduSE43OVFVClZUeWNMNE1KYXdOWHd3UDYrczJ3
            SmVhSVVHUmtDeEhwMTlWTjNJd2hHTlkKLS0tIHB1R1JMQ01sODc4bzVzbWpvbmFz
            K0xsVk5GeUlhTzV6QmJmN1E5TDFSKzAKlVzf3BCsDuJSzJO2V+5nr9ParDUMZznu
            PkiVdAx6GxBvvUEr38woqL9jCa8XPs7ohV3fhCGZN6bpsj4uQ+Bjkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T01:50:25Z"
    mac: ENC[AES256_GCM,data:lc8cc7TCL1aJj4zfLgy3HyOdxUKPUrk3lnfc5ikFX7UOsDUgKqI0NWqgVDKe5brRYfqjCE34/O0gkx7OtXqxm5Ogva8MXU0emNW4GlqVkppNoiwUqIe6Zj7LlR7aeNpEZphWScVfBCg9AOHaGvUUqIm/XbaUm+KSqslEhvr/tmM=,iv:JIIm7OhFXX843UeLo7tlp346eoXzIfEITROoYQT0C1k=,tag:/FeATr7PBmxybkeC+PtVvA==,type:str]
    version: 3.13.1
