apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 5eebcc68291bd6415fc9a8d768ee67368e2ed7554988aaf38db9ac1c95a915de
spec:
    secretTemplates:
        - name: sonarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:9ktujUCa7PMiSTti21BNbGiv2mhsQSYuv8q+jlnwXHP7uJuGCkJqYTT/o30F0B9P2K4r6nQsdJV7XSgkOpzD+yzYJmkn65CV,iv:oZ+AfqIxr26tXyDIqzX+4Tgxfe0lZ7V8a2lHYE85KUg=,tag:eoGHO1pymWFLDEIPxiu8zA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYWRFRk5vMmVtYjBDUGRv
            MWJmMnY5M1hKbGx4cEFmTjBmYlgzMm5YakVZCkxZbXN0bHZSWTNrVmZZcFhUbm1k
            Qlh5ZzlIZWozaENTeU1xWk1hQmxkamMKLS0tIGUxUDYrQ1VHVVZndmRaWWdVTUtm
            bGVCYlN5TlNMdk8vV0FTZEpiY3JDZmsK0YoVKN2ckZtQxYNlusfsCNFJO47AzMHK
            LL3EacPh/w+YnBfg0JTnYKXqP6VWOfXsLao243es8g8/LX4ZXdiC7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:33:00Z"
    mac: ENC[AES256_GCM,data:4YAwBTFQwNiH4X2OAA2zw8Oim6/BKlswr9w1VSg61FtpSJobe3Np2voF0a7dIdVnhMax1GwxOycCn/c8wJSIz7K7T+Qwe9fQEQHpAh0bmNCRwYb6tWwlyvJXVr3BiA0arh9kR1yzxFMXZ7r92iWkWNsKCn92E3SfGvQ/sk/8NVI=,iv:F5hoZEUnKtZAMHUkzxWfca/EJkCCCtQNZbqCcfbbCxE=,tag:LQqA6ZehjzrLL/3+Wj+dGA==,type:str]
    version: 3.13.3
