apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 5eebcc68291bd6415fc9a8d768ee67368e2ed7554988aaf38db9ac1c95a915de
spec:
    secretTemplates:
        - name: sonarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:o3iJWm4u6sy85TDQlUUUZu5PwmvLN5jDALvvIIcTIjkbKpwUWLhYN8IfrcDdqjZBY1D0gspZhd4TgsF2TIdREuzC4+Oik4rv,iv:f3Vsa22osfx4tCSgjC1TzYSHTXcoMl51seWDMYuaS5g=,tag:UMDfihr2Vd8yYzdItvJfDQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOFlMMndNamp4MjZsTC85
            ak5Bb2l0bjJSUnY1RmFrZnJnUjdWbkpJWm5JCnA0VEV6amNqQlJkSzJmc2o0RDBm
            UGF2ZC9LYTg3UGtROG4vbG5vdzVQRE0KLS0tIFdKT09lbldVSVZIYno3cDBTaWhK
            UW1OKzRXcFZlbDRIMmNyanJVQ1NIbGcKl/fc3zNjK5+MGAN8yhmIPMOfsmFMCgoH
            V+UvkQagkuzUOu4fF8furDh/GiTHPu3aO30Z2hlM7c4pCs31sVCHvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:48Z"
    mac: ENC[AES256_GCM,data:j92Djeo6eQgzNAflHDQ9RFx2ww8W63Co+E8rTza6P7UF2HQjTezmRQln/sMISJycZYYzah7i9ux68yHqeXGwHNYqFTepeqhpbFaVFMqmfCXkFbnPes/i6Cn3ot2vrPZxJipd5BxGZuot1G+ng8WCBClj+fI7nQfuhRMvprMlE1k=,iv:SghkrYzRFycjIR9eClclcm5q3nk/1akbA/OKxWEezhQ=,tag:fYEjNEv3tuuVbGAGlZLgRg==,type:str]
    version: 3.13.1
