apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-sonarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: bad2ec37aab16098e31a5a3bfb4f8166f441e7a32341af4a9fade0fc2653862e
spec:
    secretTemplates:
        - name: media-pg-sonarr-password
          stringData:
            password: ENC[AES256_GCM,data:vWo6zmDUVI73H438ykLKT8oHgKgJFT6vkW1YlisZXdC/KMoe943xI71nuN/xglbpPiSEMLBdgiAfCyLBPzaTUHuilLI2jZZH,iv:dcBfQB5OdGH1mEtlJAxscU+7DUC5+JPDdrcI3i4qyXU=,tag:ntIT/cnOsrdRkd4MTbeNBg==,type:str]
            username: ENC[AES256_GCM,data:fnGsxxxB,iv:zyfc/+UQ/aKMkCXB42csgZ2t3XKYhZunqLNkN5/pUHc=,tag:2iIoGc6W8v4UbDhn8NV6Ow==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ25NOFpqNnM5Q0hXWTB4
            Rm04bFZnQUYxaXRkZTNSZlhUU0l4bTlsQ1hjCmN5SlFsMDE2NXQzakQyN2pxYzAz
            eTlReTNZSENZQ095UFJkLzFwL3ZMT00KLS0tIFQrVVI4V0UwKzZnMWRzdUVLcThp
            TnUzYzlONDY3NERKelk5MG5MUHh2a0EKQtjTH1Zdzqx8jcuyDVlx+VZQ73xQpmLr
            M0a2sjUfQypaN49D4rSXbVRAehr78tSIXiwBOj0wlWMlMU7XLBfQPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:57Z"
    mac: ENC[AES256_GCM,data:yJB2PNfOSjZGZkWGYCSJoi4OqupnpfuqYoeXARZqwBVZPdzCaym0DG+ELbZOYDN0qFQkYIV4XhuFCPwKpvBdM1hQRCARanpgtGqzXp9KZGusnHMccyitcyWIRkBn/UQ72/EcDU4nOthtaIcX4NELvGg4SI/Sb/rcNDV6A8SqMww=,iv:iedQV6Nrmuj1WFn7r+xOtmruPrhxe6B1bMTHf1cpQao=,tag:7/Xpg9uU/whPCAtMMftREA==,type:str]
    version: 3.13.3
