apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-romm-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 7db7276d5bdcc1ac49f8019b7962736596d56ed90bc1066e2beca8d618036c2b
spec:
    secretTemplates:
        - name: media-pg-romm-password
          stringData:
            password: ENC[AES256_GCM,data:wwXvXfNfC1IymxDtUULSfE1w3ucVvdC/CtaPGP2Fl006mBoyKYL1vGOcplkttlL5PE/zXtLv8n1Mbe92TBcLkIUx6Kda+tYK,iv:9XA/AuzIr+l4QQcYg2PvduAbTxz4y4tVohBDIhA6jbw=,tag:r5uigU/9QXxALWToAc9C4g==,type:str]
            username: ENC[AES256_GCM,data:Rqj7VA==,iv:6Mf+Ib78UPqlWeJHUCAZ6fQDInfDqmkPTq7fc0E9Ko0=,tag:4tgXlCL8jGej3Vuy+zu4/Q==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQenlmY2UxVkM1WTlxN3FN
            NkVXVHlsSEUzakVPTUEyMmtNak9XZGpXYTN3CmltaWczVWw5RGU4MTlqVnpzdVZi
            WHo1K0l2UjYxaHJldDZiOEpWbndnYVEKLS0tIEt0YXZJY0UwTFZQc3JqNzJ6RGJu
            SmRkbFFiZ3JwYkRLSHM2L0ZLR1ZEak0KucitSVZiOQ2DRcq0ajsrlzOY1UQfiviP
            rOFIZfm3KoZiFzQ4ucPXu3HEGsSbY9x0bCJ8wscBATYIWN12f1IdUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:gYBDeX7B56o/f36s1ePrUnaO7xgFiMvujPu1u5maJOseDJ64gttg/g+1CG2BvkWgPq56R19dJsVFRvv4DV448sInyN4VMpJoh708DsZKJ4xvjUvExWUrvbp7kASvsjqSek+0RHTyrb5SdkwGD0A/ttCjzDtzSVcZiJH4TG9fqEA=,iv:2GNqQ8YteCzIwYLgpPrN3tmRHxkUcsnvazG5G5hziQI=,tag:HgQhnuijhV3d4FLyrHTIZw==,type:str]
    version: 3.13.1
