apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-prowlarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 19763a76b9bca23a6b63a9ec624178cb6e705a61fbf9fc88083aa5b20bddb467
spec:
    secretTemplates:
        - name: media-pg-prowlarr-password
          stringData:
            password: ENC[AES256_GCM,data:V9+DWYmSWUPyGQ5CHCebWNDmuPG8vXgmvNordxQaW1E93+1KamN+6eRzRCVQYr1l2zr7Yp7lF3lgZEXCpAACzEZVUEQb7tQl,iv:VNMvXt8a0iclj+/E/yJnbyeLCN34WpAINlbRGAn8qfU=,tag:0M2u24RRVsH2nEBlpy4ESg==,type:str]
            username: ENC[AES256_GCM,data:nPo+xFIuKmY=,iv:As25JpZeu4hJkT+JVhFiAnBV6ie0JwDjnqj2ZDXPVgo=,tag:sgxlQi2Va3UzGxb0zzNccw==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y2JaTnFxK0VJVy9aSjJK
            L2Zka3Vaazl0RGNvN1hDYXBrZ3ZYY3FBdkVJCk9jTkVzT1lkTjl6T2R6UjZOTDcr
            djZoV0U5NHhKenRrczV0c3gwM0g5NGsKLS0tIDV6Y2w2aWFTOXIrcm9kcFlpZjBx
            aURGOFhFL3ZiSU1wbjdRZk5QNHM2RnMK5MQXpT9zWZzvb/GLYkNnwGuwFj/G+T+L
            CKYHV9feTD2BEAyV8SSUTNb5JPtNzsI4/bfRrve0CsNNw9yATxrwdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:MG9twJuLKAGHu2zxbBCxxyzAPaQDq8rbkAla8D5PTIrkKcEkmegfE/uQZp+pzk/qdki+bncpwW1/5bf9BhLpB/vG/nj5KebojcCMYtEW1lpYsuWep1sAmALsmz6hVdDDvR4Y5n0YHndVy2vjPgPR1xyxQw7OZjN44eAW8JEZ9kE=,iv:z3dASVBwsm23ALsY7LaITE+XlQqsDrDHZnhImDTbiGo=,tag:BZ+k6NxzjIlPlxVpaTBi5Q==,type:str]
    version: 3.13.1
