apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-whisparr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 53cd109868011c1520c090412139700c565c844b06d88d5b4e2969a1352ef25b
spec:
    secretTemplates:
        - name: media-pg-whisparr-password
          stringData:
            password: ENC[AES256_GCM,data:D+k+kdK1tOhnOXUwZw7KihaLwzYq5gKm7xrYO3/EHBCjG74Uzss7JEEyWp/cNh2xFnh7QCUis3ODDAdvbHYxocDeR3xFqoxt,iv:2eOdMpbYIdr6BOTEFfYnTnoTZqzyRUejxQaZKTiseS8=,tag:lPR8sIaHPx92CtcvdTZvYQ==,type:str]
            username: ENC[AES256_GCM,data:/+0OgMPxRFk=,iv:xTvrrTUeDZ3grp2UNFn56rXpDcurwkCxYBvVkjv7WIs=,tag:HRwKX2MtK3IGLVwWI3oPrg==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeERMemNIZXp5Y2F5NVlr
            OWFUK0w1d0Y5Y3BqRXdDVzVsK0hEU1hjUWpZCmZJSVlBSmJ6KzdVZGVRb3ZEVHVz
            S0ZPbGFPVmtSdlN6WVVGS0U5Y2MvRWMKLS0tIHVhYXZGS3d4aDI1RVFFOVZnZ2Rr
            anB1WVVETE0yQmpHYkpheTJ5cFJMTEkKK9KEBf6XR/aA1E1WV0Y+9qaMAfavqaXU
            h8E4rY4Hu7FWOZiI0IzyB3BRPjC5TOKBRoc1QDlS40MhadeIgDpLrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:57Z"
    mac: ENC[AES256_GCM,data:tywAQ6BIRr0GHORdmFRT71Udb/o3zj9WYNlvkIC0CqXvUuCT3Iq9l3RxsBbjQhItyXdBYRDV7imXbOFqPuAitxyCU45kCrn0KA1msBPs4a6aN325HSvYCIQqcm9MMEBo9gUSruKBnyup/ZrUziiUTqWQvdy9GNBqPmMUc6sErjs=,iv:AeallfEIRf1NyisiFpkmnsA/nSBhAxkdeq0V7tZ8Sh4=,tag:CdOFqYxPsXGA5vcRYZF+Ew==,type:str]
    version: 3.13.3
