apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-radarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 1a5260838ba98bf6fca5bd17c52173e143be05bcda8a3f882b258519ca6310ef
spec:
    secretTemplates:
        - name: media-pg-radarr-password
          stringData:
            password: ENC[AES256_GCM,data:znzjXGz/fRIQUW8PoscHEk0lq6SdxOhf4z7D1cQsmSJXv1ZvEMfZw0kAyyLh9WL1GPngiQth1CjyttmRXLnPDT9PZWKBhRCx,iv:0QO+jZBbmcWt45DAdU+KTKNXCxJFktSNacRTOV1oCUg=,tag:nIgV64KvwjY3YxWSgxG7FA==,type:str]
            username: ENC[AES256_GCM,data:83x/8ydx,iv:r+3qOiu/I62WbZKhhNp723dPJJc4ddsu0ViGYwEsfj0=,tag:BGm5UxgcZzYU2C8MNW6KcQ==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGpFdlY0eFZZU3YydDls
            OGhnMTBRQzB5WWM5eEMzc05scVdrMlFXdkVVCnJXS2hlWjRDK2dmVnVUa2tTaVRU
            SVJPRk0xVjd3QzQxT2QyUXZkdTJPWTQKLS0tIG9LV1phK2VUVGZBeDJVK2FOYmk0
            cVZrc2lvcnFjOXdFN2M2WDJ4bnhCZFEKy3YaqZlDqgewHBuuBC5fjHWmvi/XHG0Q
            BSKQRqzkwiCr+6zJeIFdlApXJqWfiuICrpxX9nXLnuEkw+5nolUiqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:56Z"
    mac: ENC[AES256_GCM,data:5EdsrVu5TNi/R7pGbYREqLCNWrB/zfDe8EbMqhIDy9cxUAQuVFWhQuUQOwRZbnRuetdhDaWatQLTea9h64VsKxa94iWqtFGfais6N5JKBWxNtJW/Dsv5yT+ROjag0VePMHJ8Cl4XM8jXtQ/g8ZQGBN/ZnR+oq7Wrdfi6prc/aUw=,iv:fvgEgrxTI/hKs50yWu4UVeTFm/6ULrXYgSBckNcvEvc=,tag:rbr2G04A8Oby95HD6mH3xQ==,type:str]
    version: 3.13.3
