apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-whisparr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 53cd109868011c1520c090412139700c565c844b06d88d5b4e2969a1352ef25b
spec:
    secretTemplates:
        - name: media-pg-whisparr-password
          stringData:
            password: ENC[AES256_GCM,data:9N1DDYMKrGWyRpNaCuP9dDyRIGG5uHSupbfTAONP4xDZncWidcuHo2tN/ENz2Gn1KopVcS5fx2MAOtPNdNncN6K74bXfw5IH,iv:50X7cf9UrI/eM91Klt4molbWjl0D6kuRjGeV4c2izuw=,tag:JC7mJCDD3v234vh4Nz9cNQ==,type:str]
            username: ENC[AES256_GCM,data:SB5MYT60XY8=,iv:ATszxv+jdmL+5fVzAUeLS2vUCOWSWzsjbC8+5z6dcu0=,tag:qfHuQjAbulFBommNCNaO0g==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY1JKRzR4VHBqcVJuOVNt
            MU9hWk9QdEZZWHBxK0dRRjBNckVlMzd0WWhRCkpyd3p0Qit5NzJaMm5mZ0lad2NZ
            NTNtQnkxMFdSSU54cGRHUVU1QmtiZ0UKLS0tIExmYzJNV2JjVlRSRUxoYXJMelp0
            aWlvWkZLcXkxTDR0TCsvVDJ4amRWbkEKphFFJTZz2lSziI9EC5J60PeFRTXD8pW7
            /9UsPQ8CcndX4rD3GkhB2AfPzKxBwqRwR0EK1ScdeprWsochH6yCtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:zSimb6mhLhlaxy953P8b8NtGRvFxfQuJ/ddkgcSTG0uCPiTV7bbm3CmPbvL4Tpnbh2ndEqISS0Nyf7KQEhJwto2Fe4fEfd74dixpCjXM1gGE0157lNFPwoekRjFbIx2nntqwxiqfrUEq9zFjEGmXD7PBWV+BGU2cMgpIz38uPRg=,iv:go9gDE/qRnlf8FstNsMV3pnIbFGHTpqf4lXfXhzW/jI=,tag:NJ2RnLz8pK0qmq1BiMafTA==,type:str]
    version: 3.13.1
