apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-bazarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 90122c87f44e96ac641f042d6f50175526344e5402440cc0fb3213ac778ceae0
spec:
    secretTemplates:
        - name: media-pg-bazarr-password
          stringData:
            password: ENC[AES256_GCM,data:y9ztlvQznHsZFIXPU9LiJnrD3HSQe2SGkoKyl3s905N43WNVZk/QDkhHoIWua8hIqz45hoJkm+hqcddGW6wvyrecvn5i+ZAn,iv:rRIAajD0EE30hDxKMb1D+qEGAZWuuNWD3w29BKXhYwQ=,tag:8ML0836anoVagHmESTSIpg==,type:str]
            username: ENC[AES256_GCM,data:lGkmoRCT,iv:EPDlD5F5kg6f5u32uI6APMQvmq9SDiuE9B2YexspjLg=,tag:539kibOFz69jGvyqbr09Aw==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU1NTc3JMRnM2K3p1UnFV
            VDJxSXNjbTNkMzQ2Q2Y1ODhNUjEySFZjc0VVCjNWQ0N1SGpERGtuOGdmMFlFUDZ4
            ckJ2V0UwNy92a1BzU0hmellNSUs5ZE0KLS0tIFpoN2loZFN1TnF5YXBKRGM4ZDE4
            eHBxd2RxYVE3b2Nva3huUm50MkF6YzQKaerdqukEta0mHLXMUYDXgeSKvxYWkwuq
            Sz8epZzGvYhmCnsj0THJRwMbwOOL0/DjzB+zS6ABtcI1AQLtiQB8UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:YsNjPWpbVt75Tm85c+ffoq413lJuqx29JqDjXPFgw+S95c3i/FWjjPYzurlHkv11OL0li2PKucbfKw3btE8jB/hy1g/lbvVQeqWqE9Rb6/U4CajpC5lGSHYvBhvnLNgHXPA/u3EwoWWLprx1uwLA4HuFJABI7qrhJeXdulsSJHQ=,iv:Z5UCjAoVmLvu43YpVI6cahStFBW9ER7kYGPhLFvXrJA=,tag:rNEJpPDAwLSoDLLGLnKPpQ==,type:str]
    version: 3.13.1
