apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-prowlarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 19763a76b9bca23a6b63a9ec624178cb6e705a61fbf9fc88083aa5b20bddb467
spec:
    secretTemplates:
        - name: media-pg-prowlarr-password
          stringData:
            password: ENC[AES256_GCM,data:svS3Y3prBMkW9Usp5jlwch3/Xavpv2O8jqPVNArOwb6VAldzi2xx8UxRc2zikTueyxgWBkBYbWqf9/i1RwbEQParVWdA0kSu,iv:d5ZnoC923Rttes2Jcm4KWk2c4ZwshOybkrSSE4lCWBo=,tag:afkJzaWGxai1TW4jmxPJsA==,type:str]
            username: ENC[AES256_GCM,data:tdInbmZRy4I=,iv:Qluvl4VyBKtyQUjRubW53eunqOH6HkYBgX0lAN+2ZTc=,tag:7Rs5M9AuiptfWLzBfoGLIQ==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dkdoaXNMbUVXUG5LQjhE
            ei9hTEpMWlRXem95QmJIcXB5b2piSForbXpvCld1Vi9BY2RWRmVYakF2K2NkKzJY
            cHArNmVhbGg2NUJIU2lwc21CZGZ3ZDgKLS0tIEZ2S01sdyt2WDRWSHpwUlVva3hB
            alFmV1V4aWxqZnU2V1dqWUpOaTg4TnMKmSeCtOPt7k1SQ6Yn61+8i2wJ3IaEDiy1
            +qJM0YHcg5Nr7aaRTAR4Ws9DA2cDl0D+7YE1B8XWljFz7OJ7dr4YYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:56Z"
    mac: ENC[AES256_GCM,data:AS/Qr3caaeIdRLlis/u/2SvrjiPdiO5rNk7Vh2dignjpiLyC2OovdgmZlFshx/2A3XH2DgUdCfuQR/Kuy+yNxZ4o2zqbMiaZTwCzU7Hjouj0yyNr7oP8YN3oLNTL9qpmXhmxjqZcjojzdc6n6EanI0/0dosFlcnKqiqVeEftFlM=,iv:+N7QM0/Oik4sWVy+8iwocjONxMhg4vGdvH7ERRE+kL0=,tag:pHcsNiIODVWAZ5ZtbYuC9Q==,type:str]
    version: 3.13.3
