apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-lidarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 3f60a28e70f90dc7b0968ad335cdecf97a619a79c1a1a54117decac9705fef98
spec:
    secretTemplates:
        - name: media-pg-lidarr-password
          stringData:
            password: ENC[AES256_GCM,data:JGrJ67Wm1y8ET9CgCnXmp2GHP8m9ift9qu8DSx2Zt40K4D12C4YsLuS8PXzczP69lkqCOEuDWkXWzyWwCvsfYgU/j8g5rVlK,iv:c1qT8Jn2xQWD1hrnESHFlNf2Os+51SuhI0/tp4svQcg=,tag:e5UgIVa+uQBkeMHpxLmLRQ==,type:str]
            username: ENC[AES256_GCM,data:RUr8nAUQ,iv:r376G/FMBgmgiZhgnv0kWY7JkaQTSW+aFBcu3GVVB2s=,tag:i7b/f9nF4I5OvmUXwFEBjA==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVjZMTU10SGpBLytWU2pH
            c2tRVDRsZVVIenNsLzVJaXc3T1ArZ0VlbjNZClJnUzNXdkRJSzNwaGN1ODdjWlpT
            VW0rNUFBQW1OWEpPcUZlYUc0U1NoWlEKLS0tIHh0Tzk1VE5FWjBscm5QTUU4ZWI2
            T1N3ckhtRmV4bU5NSEtuODE1Ry9pTUkK4XD3zRCeYWJUz9Uc/JWNY3niDAcqSmWs
            bG5rkx4HCXD6eCfOfR2I+y7qwmFoQ7FMvJIYpxgsKByZ/EBiez67kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:knjcVqd6ZAo/tgqKaiGm//KTucnOtJ04fI1iQdIy6FJfp0YnuoC7Zmew5gxm5pyLBuhsgrlN1NO/wmGTUl6HjtWPSrdPpHheNsajk1Rqlhe01C+LcrMPF30925XoubOonYFI5VUjaYOl9tkWvVqZeeCg5ddN/KuBMjHSFQWeKGA=,iv:vic2EFj8qkX2MUnLkx4gqp6946bxNMEBq3i76mxpDS4=,tag:WLoA4S+KKNRMWoIZZTrN2Q==,type:str]
    version: 3.13.1
