apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-bazarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 90122c87f44e96ac641f042d6f50175526344e5402440cc0fb3213ac778ceae0
spec:
    secretTemplates:
        - name: media-pg-bazarr-password
          stringData:
            password: ENC[AES256_GCM,data:3+HK7IOlNvRj5pR3l0urw0VFbJd0O8rXWNBjTbqf9kAIKse/LsO0l+Vc8lLreH5r1xcxeamV3hkkhqu54j6QsDIWQnb/Ncjv,iv:hE62r6fyNP1ehZG0g/g6C0AEX5ylC/FqEn/31ztF6nU=,tag:cHFFMmFQ+m3tOMoqa7bxCg==,type:str]
            username: ENC[AES256_GCM,data:MhwCPODu,iv:+dCvZzc4C6ysrMKGSJnStwVWMRNJt9wYwWjd9OHdrZw=,tag:kJAfUy6aMPuumQpwx0fQtA==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaWlTZFFPQ1RCYURVWFZY
            TUI5RnM2cmpNUkFncVYvUUNJb1dUeEltZkRrCk11K2p6T2xhZnM3bFlMTjQ2dzZi
            LzlnbFpKNnVqYUN5MmU5VWlEL212cUEKLS0tIHJjaUhORDltS1NMYzN4dVdjbTlt
            eXl3UmJpa05ERk1hL3ROZkx1WkM0WTQK5dkinbwzqzLVCeVUjj1ktgn4OzU9Gl+l
            G8EVW6X1DzXrTXnDORTcHNkeAIS0KB7xpw7LKkrTbwfeq+G83JbnsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:56Z"
    mac: ENC[AES256_GCM,data:QX4XlLR8PrIzCLngD+q7K0uA/iDEaL39ypeSjeYqpw5gtolxxxPTo9RvL0TGaeeob62LgEJGPMSF1bRjkbxNvoHK+Q6ZmroTQf2pi3Y0K6Tcyq4CTPthJ0mWlukm9ZujIBh/INJAvgCXojNz9eVDUtBKYmJHq3LD4iiOo28LeTY=,iv:EcgY4sUa4qAeQyacxPLPX32CSjBDAxhqUvYY6sbK1vs=,tag:+14YGh2EhLXKv4cFkipwEw==,type:str]
    version: 3.13.3
