apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-lidarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 3f60a28e70f90dc7b0968ad335cdecf97a619a79c1a1a54117decac9705fef98
spec:
    secretTemplates:
        - name: media-pg-lidarr-password
          stringData:
            password: ENC[AES256_GCM,data:pHr5rjPGOVr+v1tqhsKMZ+CqZyMNxkbDh4ZMFgNBIcbSPVM03EqIQ7GQppAshGrnJPUW9+xHuMmacYbx+oQavFCXmIRM4xYb,iv:24rqeT6jvl3fp2hoCIVSUVRSXT/F6NtnLolG0M/dCEc=,tag:TjS4b7xL4CkZOJdWTtl9KA==,type:str]
            username: ENC[AES256_GCM,data:BNBVp7jz,iv:BOYclvCPYHx7zBBzKs7brQTsKzW71f7L7FfN5nSq3eE=,tag:GcuOGRbgUcPXhMJIpNjwyA==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QVZ6SkEvby9wNHlMSWFL
            NFp4SUFnRWhCMVNuM0FPQWlqS2dDS2EyaFdRCnFwWGpsSlA4R0VEMXlyeU84MmVr
            dVhUMWtWMEt0TTBTcHRBSFBTc3p2aXcKLS0tIHVSRTFVVG1JajhHK2ttZlJzWHcx
            S2JNRjA0ejhlam9jUnJtNzlaOFhzWkkKF+S76YQTJtNjZmMH8WVFsu+OibIVU1Ip
            sXcvOjUeBiw6cjHm9nSznolnWXRhKg52cNeTfsmORRYCJgVlgDjU6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:56Z"
    mac: ENC[AES256_GCM,data:VxCWTA4u17pdFio6qhapPDSXL/Lkfmkug29XQMzJ0/MzZaOa+EH1rAKrFK7Fqmq293wbVRJGusAQhFLNMgLcWF9j64EOnbRXvSCxWYE8ypxIiKx4gPQdzEW9mOpEpRJrEzp1xsm9a47yVd5doK2gSnnd5eVlkWQTqiMY6xdfJdI=,iv:0jHU3DiBpz3hzol21E08hZmdedDyuG0hAoFn/l/0Nhs=,tag:X37R03MGauA4JU2XRgEW/w==,type:str]
    version: 3.13.3
