apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-romm-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 7db7276d5bdcc1ac49f8019b7962736596d56ed90bc1066e2beca8d618036c2b
spec:
    secretTemplates:
        - name: media-pg-romm-password
          stringData:
            password: ENC[AES256_GCM,data:Ln/gZRoxxHl8ZbuGu7uQpCH2yL1ua+aXaFhNvDNrmlvq4qvks9lddeHuvvAI3bvjn2rGwTIIL/ueTvCxnKkoVAUYDp8B4UzE,iv:0radLLYwd7xEXYlvB3mTdxswkcV8vk4lT1kVh69kenU=,tag:rznFNd8cAq1mJgddQyc4Tw==,type:str]
            username: ENC[AES256_GCM,data:FRtJjA==,iv:bwLS+RUBaNG+RLSVNL0vWzxc+MGUFszFL0rfpmuGE9E=,tag:Qg1ncBrs3UprsNnQdERe5w==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQkMzSlFLMDVRcmxIZVE0
            aHJKdWlGNnp1UFFaTXdhaWFKOThaaU82NTJvCmVSTWw0cEs1VXVoV2N6NmozUktr
            UksxSDZhWVVPaHMzMU1xOEFQNFBIdVEKLS0tIGtabmVsOFRDaExkWExKNXF6MXpN
            cVE1TlpkVFNFYjFha2plUVp0bHVlRE0KxAHg+3kGfcSYujpB6DcHS/sU6M9Hch+7
            msit8n8HcCJhJhoK2v5eE0FvvZt0nrZO8pSGp94JV0Ob15HprEPa6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:57Z"
    mac: ENC[AES256_GCM,data:1rhZyJEavo4yMv591qvsoSRVASUZGvkCmCxlIxoh8MSyvMEHsEnBh3YTvxOy/5Hymbil9Q8gM/fQuOXJsuPEVsWHDXEab8m7bUcaM29kDc48IODqYFiZ9rd/HeJVprmTvS0pVNUaNGn3+xPp0pEDG7YG0BJYKtus5HyAi+bE7lA=,iv:gz1Ue+v3MSFhYi9XeDSt1K5Jbhjkix4c3mqM16ENd8w=,tag:Dhit/ZFfy36aGUoC+5aACA==,type:str]
    version: 3.13.3
