apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-sonarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: bad2ec37aab16098e31a5a3bfb4f8166f441e7a32341af4a9fade0fc2653862e
spec:
    secretTemplates:
        - name: media-pg-sonarr-password
          stringData:
            password: ENC[AES256_GCM,data:2B2odlmgUJfNv7k0gMBO4IFjIUC5mBqamZliGH/ZGKOI+4+aa4r4mspqIce4UnT4n3oDSJrnNmfVtvQ6+68dYJLbfzRKZamS,iv:bgg32jrklT9vmlREwsz4yYzd33QrqNC28L0ueg3rVLk=,tag:Wtx+YIerc+w3gbDX/btgfQ==,type:str]
            username: ENC[AES256_GCM,data:KJ0cD1gR,iv:ceRvzMx3wTuopwfDlh84Ux0VXWRuoP8Pfdad4FKfTjU=,tag:Org+g66VDEH2mTI69IdHpg==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYlUxckV5aWNNaEpDZVNJ
            d3c5RTFKamdkQWIxQ3dGeEdlRnBnTEJCWkVBCmQ5blc5M1pPUGhlT1FaRkkzWkQ4
            NzFoTkU1Yzg1S3FzZGlLb2NobkdlRjQKLS0tIHl6ZkZ5TGlUQ3BlQjhQYnk2ci8v
            UWNua2ZqNVZwcDdRcnA1R1FkOExIejgKDJ8J3EL+RCETke4DSsKCNN2O1UdjWJ7W
            Pucqqz7ezJS402TmQZOxLFP6CQ2qx2ySt5IIm5WyTEpDvLgfQTHZtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:rg95rwIVl9yepiVIOVdve+oEA+BcUN7PeVCt8VNiyEE2QMlKsrn5V1irvmm9fC5miEKMDelJvP5kb6OreikSf7ryk0JSQiAqhkhEMihdJZmB4jxg1rMxVGxuvOPgY2arpCzuGElr+sIUw/Y96zuUIhS/EjWwxn6e3N/aOzx42QQ=,iv:w7SkMVjHtNHL603s0z0PLW/M7KKEFOYuq65iBUVn4K8=,tag:xALyXzGI6U2w1W6CKjnopA==,type:str]
    version: 3.13.1
