apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-pg-radarr-password
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 1a5260838ba98bf6fca5bd17c52173e143be05bcda8a3f882b258519ca6310ef
spec:
    secretTemplates:
        - name: media-pg-radarr-password
          stringData:
            password: ENC[AES256_GCM,data:ufKNJSvC0loNUAICEyLpptd55BDjOOVek7pj6x2QJ9ffcZT4Y56KimjGmewe3rq/0A3Xkhf3171/4G42jG8Ricoo7xkqosoH,iv:hwbnj7O6U4yA6VTkaAegPoS/UwRxvgDwbUQn4XYpBXc=,tag:j7MBTgOko6934z2pPygybg==,type:str]
            username: ENC[AES256_GCM,data:0B120pHa,iv:oEF4z81+nH5CXG+pOosE3ixpiDfZuVBm+1bHPzIpiPQ=,tag:of+L9gskfuz8ZgTqc7chWA==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK1MzU1RRbldNSTRwZUtD
            cld3NElYQmRTOFhBN2ZzTEVhS082OENLZlE0CjlybUxlWkUrOGc2RG43TG9rRFpl
            dHJGOHZvM3VsSDFXc0pGQ1lJSlVqemMKLS0tIGhDOUU4b2s0UldodStGTkdTanQ4
            b1Q3NWV1OE9rZ0tIYUoxYUZZeTlPM28KeYm05cXra9SiqjZf/0yghH5GOMW+P3KE
            nYizuObe9OP5OR6lJTjYHQbAB3Z7WdE/hBO26ZIVcaXB2YEC6KUiog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:++ZJR4HiFPjWTjE+zc5oftzPtcq0HTT+Gty+q1OtPzRh+ztanAPgLT9+pDljjHnG3P7vhj5iUBhmYdvvkahCwk3+2ZzW8xU8khUrzV+Zd/B9PGoAvkgSpUEH73A0jyPQtPBr0Ll1DM5pKmDqRgc9FlPoyBemzGg2kBnm7IX6DAw=,iv:YJRVY+GVGiumhkLRAEy87oV2l2lOFQW53lpj0L4YWV4=,tag:hYEU5o+9pfqIouNX95CA5A==,type:str]
    version: 3.13.1
