# Bootstrap:
# helm repo add cilium https://helm.cilium.io/
# helm repo add argo https://argoproj.github.io/argo-helm
# helm repo update
# helm upgrade --install cilium cilium/cilium --version 1.18.3 --namespace kube-system --values ciliium/values.yaml
# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# nixidy bootstrap .#prod | kubectl apply -f -
{ lib, ... }:
{
  # imports = [
  #   # ./argocd.nix

  #   # ./caching.nix
  #   # ./certificates.nix
  #   # ./cilium.nix
  #   # # ./container-registry.nix
  #   # ./devices.nix
  #   # ./loadbalancer.nix
  #   # ./monitoring.nix
  #   # ./policies.nix
  #   # ./secrets.nix
  #   # ./storage.nix

  #   # ./adguard
  #   # ./homeassistant
  #   # ./paperless
  #   # ./rustdesk.nix
  # ];

  nixidy = {
    resourceImports = [
      ../../crds/generated/cert-manager.nix
      ../../crds/generated/cilium.nix
      ../../crds/generated/traefik.nix
    ];

    target = {
      repository = "https://github.com/sini/nix-config.git";
      branch = "main";
      rootPath = "./manifests/dev";
    };

    bootstrapManifest.enable = true;

    extraFiles."README.md".text = ''
      # Rendered manifests

      The manifests in this directory are generated by [nixidy](https://github.com/arnarg/nixidy).
    '';

    defaults = {
      syncPolicy = {
        autoSync = {
          enabled = true;
          prune = true;
          selfHeal = true;
        };
      };

      # Many helm chars will render all resources with the
      # following labels.
      # This produces huge diffs when the charts are updated
      # because the values of these labels change each release.
      # Here we add a transformer that strips them out after
      # templating the helm charts in each application.
      helm.transformer = map (
        lib.kube.removeLabels [
          "app.kubernetes.io/managed-by"
          "app.kubernetes.io/version"
          "helm.sh/chart"
        ]
      );
    };
  };
}
