apiVersion: batch/v1
kind: CronJob
metadata:
  name: synapse-admins
  namespace: matrix
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app.kubernetes.io/name: synapse-admins
        spec:
          containers:
            - command:
                - python
                - /script/reconcile.py
              env:
                - name: SYNAPSE_URL
                  value: http://synapse.matrix.svc.cluster.local:8008
                - name: SERVER_NAME
                  value: json64.dev
                - name: SERVICE_LOCALPART
                  value: synapse-admins
                - name: JWT_ISSUER
                  value: synapse-admins
                - name: ADMINS
                  value: '["@json:json64.dev","@sini:json64.dev"]'
                - name: REGISTRATION_SHARED_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: registration-shared-secret
                      name: synapse-admins
                - name: JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: jwt-secret
                      name: synapse-admins
              image: matrixdotorg/synapse@sha256:6b84a7bbac36f080b2d2e51e0289cf1b08b349598ea44a558df38d558f2c2311
              name: synapse-admins
              volumeMounts:
                - mountPath: /script
                  name: script
                  readOnly: true
          restartPolicy: OnFailure
          securityContext:
            runAsGroup: 991
            runAsNonRoot: true
            runAsUser: 991
          volumes:
            - configMap:
                name: synapse-admins-script
              name: script
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
