apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: synapse-admins
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: 58b0a752e9f3f74e32590313eccb9a73682c12f33b421f08868f875e1cf4df1f
spec:
    secretTemplates:
        - name: synapse-admins
          stringData:
            jwt-secret: ENC[AES256_GCM,data:JpIM5Z+xTYqJ920Ap7hXB4GQRLgBnqBKT8qR1Xe0V0AlSC7Yw32AIeQZXcMwGFVhrNctqIr6vw+A4pFkdrHRV7pngKIlFcjZ,iv:o9qw8hwS1U12L/hGynctJVBvNgrf/6EECfES2DTXViE=,tag:rxfWUAHhJ7/vjkZn5PfwMQ==,type:str]
            registration-shared-secret: ENC[AES256_GCM,data:t+QQSxZW+W2hFgq766TKSJ63WrJRvx9xa25FuyVzQSHI/OebORAQO/e/3MdmvCeEl+eWrqfLNhMd6qIx7JOrHwGz+DFJKz88,iv:KWNeAJ8LOxRW+qLzIsodgtHvatA6PkjYDOEaEBx8fwI=,tag:mkSRlxPYFSyy7xmuCHpksQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWGZrUytZNUVBWWMwYXJU
            QllYVG12eUZUVm9kY0pZUHlHeFBsRTBwUmowCmR2MUZiSDg1Q29ocC82bWY4Tzhl
            eHBXcHFPTjh1YnlYa1FvVitQaHpVZTAKLS0tIFYzRlpubWVxUEwydnA5VGlSVitS
            KzcrZk1YeHBUbmx3ekZOelkwZ0k3SUUK0N+8I+M/adAM5Dcbv3de76LX+U/um7ry
            7V8BqIW2quVnq/zqn/VIsTNCfC6iI8dqoxMN8A8DdP+QtJqNAZkWkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T22:44:36Z"
    mac: ENC[AES256_GCM,data:YxYdzbtip1ZooJ/7wo+zY8BAA1771O4LxdUdB7fqLJJn9pLFdfiyyZaSTdaxB+FUp4/Ta2u8WdrbJji9Uzdpv1dhQpZA4i+1nHWOUNfJlxK+8YqCiDbiIuLeq8+AX8qS1fkxpOWMqFaInfCWTRslpIyr1fa1CbBfWe6kq9YE15I=,iv:gBsrU7vGwkR0DVppfgklLJCZpEha/ZVUgkMGdJgPq60=,tag:CPHa0ZQR5jC638psN1JRbw==,type:str]
    version: 3.13.3
