apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: profilarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: a7fd2efffa03da9fe04f85e6514d6d1a8b63e3ddb1213067c48e9789629ff1e3
spec:
    secretTemplates:
        - name: profilarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:78gq9Vw4sa31XdkyZXjKirWyiKTXpKhbYfPw/MRcBwFhSKn4naGMWQYfQ0WuAdBUcOKe82NKH9IBJ26WjvTwHFt1W8onoR+f,iv:1kEPDOONMiVq1JVR30Kizg4F7y4mC1+9e7Dj9dJ/Za0=,tag:Thyoz1LSs0+W5LOp+dUynA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQTlxL09MS3QrM2tXZkEv
            SzJFandLeDRnakd2dzZzL1VENjJ3N0tlMEVrClNXUkZxUjdnMHlhTk9ZNGRsc1ZU
            djQ4T1diUUttMVQrbEw5c2hQV1RqRHMKLS0tIFdaRzF2UCs2MzE1ZGk4Rzg2VHJz
            eEdaVytyeW1ZNWx5enJjY1liY25wQTQK1vUONbPBEzGT3Ejs1qfzP6GBkhb5Re1M
            pU4wGZHunn+yZuBxAWC+aFZzBNklTFCrv+2g6PXEDEB+kIf7LMougw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:58Z"
    mac: ENC[AES256_GCM,data:r3C7rE+H8uQKNtgFD1cBx3j4QFr2Pd40TYw1RJoA1pkJ3WZUW6L/fKeqwUOgQ3345pHTsmj5phxL58DOuzwNEG1355nfJJsHGoL48II16bk+obk3PbrsE5aErb+JNNCbXaZfWk5Af3y6ZOWNX/Iq74nTyTFyXgZo20Xw1JSNpvc=,iv:zhV/x/JP+jnTAz0ul/06Qrsh2cPgm74/PPy+1ph7tUM=,tag:tTDUvjwcb8mXL0ZrYh15Zg==,type:str]
    version: 3.13.3
