apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: profilarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: a7fd2efffa03da9fe04f85e6514d6d1a8b63e3ddb1213067c48e9789629ff1e3
spec:
    secretTemplates:
        - name: profilarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:5WLbU+6FiayvDF0j2WGZYoIi79aQGxORrA4jZd7qiV7UIjBK49KOoL6HSSCwABOQY27+qK1I4f/+j7kxl19G8vNX+sYQn3Gf,iv:1sRmEgBX0kfkRX6FGpKNwDYXFgfAwilzK5yQJPGKdRE=,tag:yqtT3JvbCi61jvqGyEXbpw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaFgrUEF1WEloZFFSWDFx
            UFpLMkt6SUZGUUFHWGtnRkdiTmdHU1B4Z1dFClgrclVjL0EwWmQxd1haU0dlK0Vt
            TVBRMHZyTlY5bFBjZkpPcWpxUG96eTAKLS0tIG43Y3Qrc05iazhtWFBRckJ1cTJi
            MzcyMlFXZ0lJSzFFcVVzcWcrRWQ2VFkKLSSh2Khcu+WmXixSvzVSJ32bKc21CS9g
            FuN4fpfY5cHX75/oTyDm9fxYlitsxmglOotThzFJQbBznM9niZVDdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:02:22Z"
    mac: ENC[AES256_GCM,data:H0MuvFi5PoIZMQD7xEkYiKtsXM2tOOAcEcwu6xCo/sEN0I8sIP+6FN5ty/xrqT+LnjLNNkQuj8ob3CQZesjMHOiRvntJ1UzA+OxJgSD0clUt2x3pavE7koMKWcfOF+iSffZ4l4kW1V1R3R1cZXT5OnvY69sJKzdPzZugwa6LykA=,iv:1RCrhvv8A9GBp0/1twVI2VGkAtnjbwAWYQP7sOM1wXM=,tag:6vQfp8rkUwcXOXEmieehTg==,type:str]
    version: 3.13.1
