apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 9fb462381f2837b319a43dc08f1be786abe6383f0dc0de4652c8ead3ba738794
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMXFNb25odlRRMTF6VC9z

      QkNwR1hqLzZ0RmpWbnRjZzFxOEVDbzgwekdVCi9iKzVaVmlmN3ZtY2UybzhTeWkx

      dGlzV1JNRUNXZEhIaTRUWXl0QzdhR3MKLS0tIFlkbEVpNk1kTDNTYnluVDFMZGRL

      NjBCSzRZRUxNWjg1TnA0MDlINjAzRm8KEhrrqDufVYQaNBaUxQQo0X7Zffkg1sbm

      PEkdRftWlQMv3Y70Q/qRt2AjvD+7y5A07WoE5ocz9BkWit8c7qZolg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:50Z'
  mac: ENC[AES256_GCM,data:I3JoozAtcaskHS6uD0Q0SFCYvlur5oAmbSpa44RGSX8t8Z/U3AJEyIiC5hIBDwL4/mqKM1VSi94+X+gFOOCBM4HEaT278G7LaJbJ/RZ64SxW7EL87q5IwmC1wxZNHRZIu5go9QiUxeYm/d3oOUJIIsKu/JVsn28xfnm9a0/y0CM=,iv:bMxJlK3cNnIDEtWLw79B1dimPYhlEKH8UuEs7hTBZ18=,tag:7KvUPBwI21YsttrmcT1fNw==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:zjBPf9OhyHkqYQcCgxe6ZuZVGROkdpLj+oEdmLJ6S63yKw1MDsPe7lD3cIshgp45YA==,iv:2l5BoRQDt0jJgvPrhk2KdUNC6lPJmfnJZ5kDWRESV84=,tag:R27wWX6foa6HYA458iq6Vg==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:Zacaqoubv2L2YMtvks9dDCw2WESmyA==,iv:+NShJTNRexJsMXXcUAx2I7vUiO3yvtQSjyeJPIiWOco=,tag:eogiuvIR4bq1LpIvgDW5zw==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:jwKY/ZFlPUiFXy+NC8VN8ulgPuKzuccrZux4Nm7fhkHYC9TC6fsBcgGYCCwjf/kHFcsf3R2EfACrNQ4Zcxpmz9INJRaCIJuF,iv:BAMFDnaiTvAjPoCcVq3Nsqk4JefR4dMliqJDExo2y6U=,tag:+6+IF8pkhlRJ2Tn+OHgz1A==,type:str]
      server.secretkey: ENC[AES256_GCM,data:HDCutVINqlCLKJxWZq7ZyJOJV6mm0Tw0IBRj1htSyPlUpr0B3O9E40WlZcE=,iv:83wZVxTEEB6G6gybDklAP8PBPSmVTV4yaoEHvVQp+yg=,tag:TWbkUrpZVIL+RSVp6x021g==,type:str]
    type: Opaque
