apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: a8718c624db12597eb542b3f9912d20166c879c6aa51de0ed9ef0e090935153f
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT1lweXNKVHZOZEdvalBa

      TURrTHRneE85VlFhb1NhZXZUbldwdFJTbm44CnE2dVNxL1lmcEhNYnd4YjNoK05L

      aVVqL09zZG1kb3ViYmY0SjI1bGtKemcKLS0tIFVXTzd5WVprRHJacHhLWlRVZHdQ

      NVgxeHZZT0ZyWUIwQnJXZnozTi9STVkKSlcBLh/ZPx1qM8oq+5c4gXSJhyE4WITB

      HXinASexgF4tWMJK+ApevtzAVP6QPGTtpCT/Hm7QxJIEtdj2bP6/ow==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:50Z'
  mac: ENC[AES256_GCM,data:nGTb0PgDfx9zdLjTXPPt+GlcAN/22sM7RzUbI8VBSbz30vRF0gS6VfIKD1rV/pwoaW3qw2i0F56BV/6+FViES3wiMUyS1F3pKMuWbdsuiM92cJY1BTggu8jwOuv0m5jT7FD1VMZAkcgrgamXuWLTzeYub4ZfVaB/y1wH/yBRiGc=,iv:NXhv7Mh6TS5DgATvJ6Tp8hLzDl/6B3e16XNG++cZLDM=,tag:33oE3ihrwQSqwANFr7Tjyw==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:UKJ7Do3f96DHA7aHEsYya7Qjoi7wOYfCCRHknPPd1opsUqbt/rEcwwamsthwxgFj,iv:aRg5acSmWSjnO6RCfpvAHqpZZVxZ/Pa3CLLOU8ohoDA=,tag:zSUPpfE+PvVdMuV5ZS1UeQ==,type:str]
    type: Opaque
