apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
  name: bazarr
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: bazarr
      app.kubernetes.io/name: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: 89a4252f4fc8cdc3b70fe31e6386bb2bf7e1d485b9a153a5276fc5c8880a16ad
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: bazarr
        app.kubernetes.io/name: bazarr
        den.observability/file-tailed: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/config/.alloy
            - --server.http.listen-addr=127.0.0.1:12345
          image: docker.io/grafana/alloy@sha256:41c41849989b7e054ccbadc17938ee1e5592fe26bfbc56ef3ffc109c0b0b2739
          name: logtail
          securityContext:
            runAsGroup: 65536
            runAsUser: 1027
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            - mountPath: /etc/alloy/config.alloy
              name: logtail
              readOnly: true
              subPath: config.alloy
        - env:
            - name: PGID
              value: "65536"
            - name: POSTGRES_DATABASE
              value: bazarr
            - name: POSTGRES_ENABLED
              value: "true"
            - name: POSTGRES_HOST
              value: media-pg-rw
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: media-pg-bazarr-password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: media-pg-bazarr-password
            - name: PUID
              value: "1027"
            - name: TZ
              value: America/Los_Angeles
          image: lscr.io/linuxserver/bazarr:1.5.6
          name: main
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: bazarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr
        - name: data
          persistentVolumeClaim:
            claimName: media-data-nfs
        - configMap:
            name: bazarr
          name: logtail
