apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bazarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 3fa68be204ba026203548a0fcac20cf57a45a3500d98be933bcbcd6ea5dc22dd
spec:
    secretTemplates:
        - name: bazarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:+s4ihUGpV4ESPkFA/3N4t+9xUSrfbPNBeQGmrxXq838uLcX1/Jt+grwzrsdiS1Jx2r0QIocjOK0xKhRWxbD5/6ea23eqiaHU,iv:dG04Lfp5zzFqUTG49qSOjMqU9rHfk9PwC/bQGdfN6bs=,tag:pEsK5lpEdiY8IhFLIoPduA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SngwcFJnT2lNUDlKREhD
            bVlZbUdxUWdnTHlvbFNBa1BjSndhQjY2SkhNCjlZZWQrUDRWQTQ5R01yMDhVbnlQ
            SUt5RkxqemlTaCtmYStmbkNRWDhibXMKLS0tIElqU1hON2xHSThJY1YzZytxWE5m
            dC9HUkdZM0dEdi9vSCtObEpFbzM3TlEK145KBq1mucpond0mjFsqoHXf4nwPNkSQ
            y2/EGQqfknXkPA7oByjZN5U/9jFiBdpAOBO1QvPOLJHu7Vn+/iefxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:44Z"
    mac: ENC[AES256_GCM,data:e110yBaG4tR1Rbi/ODzM+7INqktja4joN24PTN+NJvi6M9f4p/RDQbbrTFjatZKA8rfHrQ4d8A0j6LOOS/i7LE/sM03dC2NLPpVmuLn+kfRE3LWEnmv4HupQys7+EvaPU7aVb3PVvxNem/oJeYGliUX746ppovi8E5nKjudTExY=,iv:0R9FZCxEzQ79hIhKV66nHlPatE4NEm4FHPUGTpqI3gQ=,tag:L7704W0J4fAxQp6Xhugn/Q==,type:str]
    version: 3.13.1
