apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bazarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 3fa68be204ba026203548a0fcac20cf57a45a3500d98be933bcbcd6ea5dc22dd
spec:
    secretTemplates:
        - name: bazarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:BdxJ4nOTIfMDc+7WqxNfBa69EgEHvV7uTc/Ye7WKb4wHOx9iis9erxGlvzh77m3hXUEehy7bLHLnrZR//KskxVWpZp7hPtJO,iv:Qt2cvF9VEvHSrq19+T1DOc9lthNchpqACO8fwCjd+Qk=,tag:Z29ntr+lvoh/caVOW/26BA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd0IzMkpXYVphcUl3VUEx
            dFJJYUtlemlPeW9QUk1EQ2dkdDJJN2lESnhZClMvNFhCb2ZRbmVYdFNJMXY4STRZ
            Q1FEdE5ycFNqR2lmVUl6WHhBR2d4UzgKLS0tIDFJaDdpWjlJbTdUc0JOQ2RhR2J0
            c0I4Ni95U3RQVitIYlJQWXNXY3dzbUUK3ZqP4ocUzbZ5m14peRmPdtcLvSj2zVwy
            yRChcTp3Sd0T75YOWsnNCub/D+ShxsAmLk6fH7XSlzMNmOUpyUM2VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:52Z"
    mac: ENC[AES256_GCM,data:Vk1MxU3cyF+Cyk2YMrx5aq73qsFQ9GGSUUJ6lgV0cjRXW2G6FbKTshl8V92hcCmdjB/5hcWe3A8LxgNGW6dQBs7syfzvGn2ux+h3FuwyImo+2NYYFAFz3XGZNbUIFFIaXpUSmkkXE4GEKmoPR6DzgoOmetiU/31zbmZQCIEsHe0=,iv:YBzox1VsAzOA1BJu8QCtpPmaklSsGt/Hc5p5Dod6sX4=,tag:JZRZiUaP83iijqB+bLQ0rw==,type:str]
    version: 3.13.3
