apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuwunel-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
