apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tuwunel-oidc-client-secret
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: 5bbb371b77b12b060465cdb2ff379a6106e87c99e2750466f63824b887c134c1
spec:
    secretTemplates:
        - name: tuwunel-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:RmtUsGk4+tR9UHC4SL9TcMbRlywHhxZ3w4eIu85bVRN5MZVfw2PmcywZidhvi0KUFWFn+WTt9qF4Xtn1bO0AtXrid8D8PuY+,iv:1cVzex9GSGkVuJ8O6TiB5rfhAGrvwr31w9QnMx2Zhes=,tag:M8r3p1/gjvxic7LF9F3MHA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNTk4YURIaGlTc0FUa2oz
            OFdkem85NkJOb2NZQUdwejRSUWIzTVhVM1RvClZMY2crK3JUMG0wVllnbEFpODls
            blVqVVZHUGdhSS9QS1hXaXZtUkxFUmMKLS0tIFJKempwM3ZySUxiZksxNTJ1L1la
            ZHY4TThGK3QrZ1dMSmtjS01YTkZncHMKcm6QQ+I8b9sdIAUxmlvalNq98Ztbzb2k
            0bBqm1JvSVL/uXQBujxOJ4vwri/6hzUBc6DM42W77eN+Q0UaxNaGxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T19:45:44Z"
    mac: ENC[AES256_GCM,data:YRhyPZsfpJi89fzELzPp0tFf45BYavQZ2+w0rieHVvX0jso5oz7WnV6OK+jRD6DbGCyxoEVt5OTacnsdyRA+P9Wjo72Z+Ysu/LOSf6q3d87N+Q+H7StpWbmWjPmHQy71s729vWhIpYTxGo3HKaHm0LDIBpwJF7QhwbL3LRdz7Pw=,iv:JTCPTTvOWnM/1JN7xJ+2tWLGWtgYyKP/AMbahHMkmkM=,tag:FumHTTG0B/eCk1dGXTkRIw==,type:str]
    version: 3.13.3
