apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: synapse-admin-oidc-client-secret
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: 3ab47d29ea84b0ec8f0315d286b0457ecab76ea08baa46154d477ddecb36c182
spec:
    secretTemplates:
        - name: synapse-admin-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:7ZL5HOS31SSrxYUwl0XQ8cM5m3Zrcuwj0TaRwHZQ8+xNlDz6Yluzwj4U6i8gVuygAJSt5/E8CjIrk5z2JU78jm9fUmzDH4WN,iv:rkW6nYTB7wevJF6pHeTurHxlzUpye3H84qwXX0lSJDg=,tag:KRR80LrJTRTObFRn+u1IHg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RWNDK2l3RUVxOHk2RW9r
            MHF1bHZEYUsrM3ZTQkw1WHFOKzdzZ0JSVkdFCkJ0Vlg1eWhlMWtsUmtkSmVJSnJ2
            M3ZrUWViajRnTmZmcVdmZ3BRTkYxUzAKLS0tIG1QNkhNcFJNNlBUdVZqdXZyR1k2
            QTladldhL1NZWnhyWURzalc0bUtUZmcKm1Nq/3+z9HGI5MSBmOLiXcjgNLpWpYNS
            SQrQoTlSH10+OcWMi3A+Tv+hdFqyNmZHK493vbWx7tU4ceq54GkncA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T19:45:40Z"
    mac: ENC[AES256_GCM,data:PHBMCQlrHdV09WzDQvl2Y3E3zTaNhu0J7t/Vd75p2qXE7d75IvOQuIwcJMogATRXjkmNe+5x1qSIQ5QdyzYFZhHlxbvO2Rm5ZbSc+D/bwlXxWi8HQXARf/+lW+5V/e4GrV7amRAcTS0j2sG+gGfA0rahMoGYRV9h165mB2wRtYQ=,iv:LfsYanb5R/1dhr/NHbR6TwJKYTx/O3mIDCby0VC7nVI=,tag:W0rYq8J2QMgeimkaSNkVLg==,type:str]
    version: 3.13.3
