apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: llama-cpp-qwen
    app.kubernetes.io/name: llama-cpp-qwen
  name: llama-cpp-qwen
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-single
