apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: llama-cpp-qwen
    app.kubernetes.io/name: llama-cpp-qwen
    app.kubernetes.io/service: llama-cpp-qwen
  name: llama-cpp-qwen
  namespace: ai
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: llama-cpp-qwen
    app.kubernetes.io/name: llama-cpp-qwen
  type: ClusterIP
