apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 4b56224be52625bcf20edbe8904c94762be788471dbf14ccc8f417170574a893
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSFlKZlVQM0dKSDdLV3ZO

      NkNmYXhhZzFkaFFLbWlJaCtDOUtHWEQ5Mm1rCkIvakRBT2s4N3VDT0JtczZGbEpE

      ZHpSQUdsYjJlak5XR3lZRDdLSTJ2RWsKLS0tIDlUZmR3RXgwYWhkRXplNVlxTElr

      ck5NUGYycWVBd1lXbWFKZUp1aHh5RjQK17C1ugX4ufEZiq+EdgvrlBuzBrga1fyZ

      LjTwOEyjlZNcjIY86s2AXX0LCR+sAar8fpndCgf6g5x9vu80c6v3bg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-18T03:33:28Z'
  mac: ENC[AES256_GCM,data:H5gOkr1sgJ6eviCmq0pjDR9plOwC4cjcvv/tPYhQzwwkE4StxM9kHXlDm9VJ4Up31wUWwfJLZ4kPmNMSZjIZTkYjztdyfgVvGYAmyas2riMPHSDJl3VfkwFDWLuk9IwlHOBMVorYzU7HQ5G6vQkE+pQxXizIAQNqIj+W2NRw5NE=,iv:MJg84Msse2paJ60xHYmY8ZpZHiwRfZ1Ao4D7q+SPIP4=,tag:pGE/yvtf67u7Om3NRxAt6Q==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:CdA2ckARXwiBQ42OMZ8wlow3TrF7Fibil3e+L6JOUHZgRTZT1DxxnoEytv/gl8w=,iv:td8U3AA7q+JL09yj4bSVIRaHVFMCkutXq09JfhvZL04=,tag:oeS9R2FPQyQ66iSqAVbBUg==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:7aOZPYaEsuTJ/VZSvy/AFFG7ptaO6Q==,iv:/tj38eRMzOF3ZxIIOur6HeBwixlg/PuU7NY/t4SIWps=,tag:ug0RFbcS875AXCNCyeTzpA==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:o8q7+VniA3GsauJmjWvoftMxO5hDmO8yuQKqP4T8hekaLU0kN3Yp5+FIj9Vi28qxW7sEG9M2olCWEoKlBjO30o5qUvlQvJUM,iv:KZ0tCoK10czG7hYZLyr8HDUHYT/LR1FIFHh/ViXlt6A=,tag:WjFf0CtvrufDRWAMxDSFXA==,type:str]
      server.secretkey: ENC[AES256_GCM,data:Y0rBwIAw/RmZVZnOmdvnYXzQ/yPjU/TzxR89mdIJMAby9yYGKQWf4MmbFrA=,iv:cO3nVQyANsXNHaM7ANLg7lbMBvuXk83fPBgIUWnOTSI=,tag:s4HW5SOJA4Rt1e/L/7Getw==,type:str]
    type: Opaque
