apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 0c6371ec8406f749aba71c274877d57767c96dd3163f81e1234dcef100609405
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOFBLYTN0cE1IVDNaKy95

      cTB6WDBnNTk2OC90Vjkxdmc4RGdnVnlMYmtvCkNyWUMyMXV3VmZocytRVUVwM3JF

      QWpYUmk1WTUwblp5WXlLWE5iaml3ZEkKLS0tIDdCS0dQUVp1TkxmLzdHcnRHa3pP

      dVhVUDRFcFBHeHpQZE5oMk95S2ZkeEkKRrqo7tlbjQV9VC2ADO2ZyfFuqtM7+aBx

      gSufnc5DrgQQEiEPz7mkjHGGd5MtFZRW75iD259RSi1UiDxtWg6deQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-16T21:53:56Z'
  mac: ENC[AES256_GCM,data:iPM5TiypUqntQnsjilXiwz1d4y79QLCIRTIZAwTehSqCyYSi2c8RbZrlj3cHhaqbZ8bapW8iCAUcPd7Y/JcJLs+nwKx/cNHlfWucfzCItrqywP6isRR/Q6IXurP8bVGthc9OJc7HEuME1aGqwdWNL7ZfmrjqjacC1ewBnAaNfqw=,iv:x3LNHi5miEIFNsBpLVjLeTSM0wY+BZ894hZdFq7ZruE=,tag:7Wc3FhWsQy+7bvzc/oX8zg==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:ID9YR6Pb7Ebfo49+GJswiE7B4317G9TbEsSVn6IILfpzuZM0f9hMyjUxJeBCXZg=,iv:5tYRAFUWM5V1vQFzQ2Nn/0iHPokWgfAE4c1cCvp+f9U=,tag:K+LpUvzx8iKIRZIzXejmqA==,type:str]
      oidc.clientSecret: ENC[AES256_GCM,data:AHqFlDwMaJNgPsJXVverum6BsFn8yLd2Cg3TbZsVvbc/Cw4zvNrW6IcOCwDhyLyJnjsnBFwReX6t4QDFZy+gA+v0kz1Y9UHv,iv:426ziaenB94I7zSuP+DqwO1bpHOq4gL3j5kQh9/RJKU=,tag:bQHY6t9Vi0j1n7D5L0FJtw==,type:str]
      server.secretkey: ENC[AES256_GCM,data:+GIx7hia0O/k4ZHHVZl+INTlefqk6zNa5dMoGpFg0Ld5/guC+5+LqolmRzw=,iv:DLsPUYN+Z2iQvrr48+0iF38X3KGnXUr3vZDrCKDzXQM=,tag:K6CQShO9V6DRHqIjIYR7qA==,type:str]
    type: Opaque
