apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 6b451976cbd943ccaa91eb98f665ad1d413372bf9d569c7bc116cdd9754a6a9c
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyakJBTGpXZmNrZDVjaEtl

      aC9OeGhqTld2S2hWcDBSK211ODVCRU9ocmxZCkdNYlp4RGdaMWY2aHY0WWZuRzlx

      U1ZSaDhWR2NFeFlSZGpTcDJUWHVBSFEKLS0tIHhYSkIyNjBmeHBFeHBNRkFnOFU1

      NmZaSnlhTjhoNms0cHNBRmRXUzJTeEUKNRJHZprBh3DSZKdOGkI376+QcqB3LAGA

      uDK7N4lqGgy7W5x1L50sHDup4q+/j6nsVJm75HlYjirRLB52n7TkDw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-16T21:53:57Z'
  mac: ENC[AES256_GCM,data:1D0KbH7h+SCWHwp3gBrbt/K7QPsJb1JuOw3YyEPHDCYpf39+FMKEmSkD0EpvfATPRkidOTY7lFGqGe9eBljrlO5sW1BrW4dg9rxOCivAS+aYimxHfLjouSjBtap4DOKpqJPwGfz+eFkW+mTTwhwCgX11I0SXvl57/f/rgTYXmYY=,iv:tiGR1KGJjd8yV/Ugwm5+UUHVe2tmJnr9KtEXapLVCSs=,tag:zsCLolKFnI/HZ1VOsqzCGA==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:VC4vOU5/63HErJbUozCDE/TKNu5zrhGuvxW/QPPhCDp+OvLxt2tMKXsV6NryrGiH,iv:P6mShTE50LGDT7wkNVnLxrJXGtfU0pwQJ1ygrdNFfIs=,tag:kboedw/F4gN3sekaNAAlwA==,type:str]
    type: Opaque
