apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/name: garage-operator
    control-plane: controller-manager
  name: garage-operator
  namespace: garage
