apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
  name: qvrlab-com-wildcard-certificate
  namespace: certs
spec:
  dnsNames:
    - qvrlab.com
    - '*.qvrlab.com'
  issuerRef:
    kind: ClusterIssuer
    name: global-issuer
  secretName: qvrlab-com-wildcard-tls
