apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
  name: gen-framework-com-wildcard-certificate
  namespace: certs
spec:
  dnsNames:
    - gen-framework.com
    - '*.gen-framework.com'
  issuerRef:
    kind: ClusterIssuer
    name: global-issuer
  secretName: gen-framework-com-wildcard-tls
