apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
  name: getqvr-com-wildcard-certificate
  namespace: certs
spec:
  dnsNames:
    - getqvr.com
    - '*.getqvr.com'
  issuerRef:
    kind: ClusterIssuer
    name: global-issuer
  secretName: getqvr-com-wildcard-tls
