apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 31f1d784b431e18fdb2d51592527c28adbb28462e8b4e9f8a4df62aeb91a3dd0
  name: json64-dev-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VWp6Y2h4dHNuM00vS0Nl

      bmwxcGdPSUhHWkN0am5QcGwwZmtQMS9NZEN3CnF4RU9ubEIvZ2VVOWppUG15R2NM

      S3o2YnVpVnI2VVUzNDFZRy9Ta1QvWDAKLS0tIGhvekhjRHM2NllzaDZLbDUxUUlq

      RXVrT0U1YkNWbGkvVVlHU3dHV09xd2sKzxiBYXGlF3VJj/3s+MKpwzpyuVzlgqMA

      8x6KWe1FfZx04zd7fFasBTvNOnEd/Kmx3o9kUx6nO1NIk7/7wBtx1A==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-09T16:55:03Z'
  mac: ENC[AES256_GCM,data:GCfCN+wDSV3SQJMtJ4pWLCG77WegcrMUlRat/jxV/CErJzTajeCJrUyXC/NwxGel9EgjJHeLOfst8y+KqqmkSNl+723f9L6Vs8PiMQbcw8MWeASa4OmFYFoYTM25odX4LYbJ77HFj6pUGYLM+z5X7uw0mKMiyFQPWYxq1LLx1HE=,iv:Ty8Q7m6BujHAq3QHTJdW4oqBzp/cs3pj1Idfjzd/gPk=,tag:35CJBJbd+VF4k4vX7D120Q==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: json64-dev-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:BoVvUV5JUZNYwwuKJVI/MvS3OVmkKWUxs3JlQIlr17T7ea0lZhwlSA==,iv:RcDGtiAZkWMWc3mAcoNiWw01xvdHDP3fIO1kmmr0u2U=,tag:lYbTJIJV5gOGPjH11Ub/EA==,type:str]
    type: Opaque
