apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: json64-dev-secret
    namespace: cert-manager
    annotations:
        secrets.json64.dev/plaintext-sha256: bc17dadfb9fa8885bbfd9c31a7ad227d9057875e988959a8e4e4a5d54220214d
spec:
    secretTemplates:
        - name: json64-dev-secret
          stringData:
            cloudflare-api-token: ENC[AES256_GCM,data:gXdeE6BhXeniut/ttH6XPFK092cvFUw8EvX9on6scsLVmTx2QWXiPw==,iv:WG8cysiAnxfJbGHKzOlmPyy0aK6iRGXOF+cTFIYNg5Q=,tag:Qloq3JZHdK/wa+WQDYbr2A==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNFdmbEhkQnk2cDdKSUtB
            YVhLTjRJNjVMSUxYSytVa3hyRTRmUzRJUWxRCkxDWVhHSStjbHIrVWRNbWVKMkJC
            VVhCaGQ1VUdrTTd0SzFYTUprUWJIREkKLS0tIDQ5OU05bkxCdng1V3FJdzIvMGFV
            Y0ZVOWZWVS9sSGxvU0FVVEtzTHBxWE0KTtuu/r63D1iBuOJsgaH5DkoHfJllo9hK
            xUBVeDo9D+5brxgg2T9kgWm/pra+2U01sDdlVmtdw3YmlaEYcLxofg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:45:20Z"
    mac: ENC[AES256_GCM,data:LWls95sA6YTN/EgGHf/o/IC2LgV9eqR/vzPm5Ghu2fl1vumgocsFxhwyVHFSu+0TOh0vokZyJw1FxaTziYVlS01gYwdEwGC7ANtJl7jQsHwMRe66jo+Unk48qbIfhj9ELtqkAXbUUvuv8z9ECliaCpuySR0zf3tbpJPib7Xrxic=,iv:cTV3CRd+tNd12BS4vzQVQaWRTdj3FNj1Bx++isJH97M=,tag:oDxmVmJ9cgqSsgoB6aByIw==,type:str]
    version: 3.13.1
