apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 2440a210f2f0a7f89a22d3290f3fa8524b15bf00464279e775a872fc84a08ff5
  name: global-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQnNpSEorOW9INHNrUDVr

      bk0zY2ZaY3gwc21DOXZja0dLSVJ2MkdxdkE4CllSYW9vRTgxOElHTHg3MDdQOXlI

      cElqN2JYd2F1V3NXSnlZYTZ0MXA3b2cKLS0tIG5xOU1LSzlYWnZOUFl6TDlxb3JD

      ZTZSUXBPZ2dncms0ajhEWXk1WTlJRlUKViTXzDHpsXx/qhz4joHIhTUbq350BGwW

      rIfhF/HWBQwiu5rNkGfBQCWvr9rEDFJmcBsRxUSs8qWtuZCelCuQoA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-09T16:55:04Z'
  mac: ENC[AES256_GCM,data:Wpf2wKH7U+SArKHp0W9VjclDlVKNI4tkx8PCtRXqFVW8VgZTugB6795w2eSeFjV/ozOLQm8vASquFGWmr0aybWaUv9ikdbsMaV8fbvfqddPI5LouTrrSHLe95crxpp68MQU4BysS+/2qrxO6fkmZYKX0qibbXkKIRf2IfmQEfMo=,iv:k5eJvdOUElW3+Rj+EdLc0pjmfYB9NCfbU+MfaWLRo7A=,tag:uEkoF1ZZ5+UzHQOC6qMBSw==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: global-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:YcUfMMN5ZAOdHr0qcMac8QxrwUVuaG92oopY1VrrjzALNgTK63kdaw==,iv:S3mi3LddSnwJ0BuAjZuYPEb+yfkjciNwNiOcFBB5uhk=,tag:PDVhbWKXiGxP6kr4PF+Dfw==,type:str]
    type: Opaque
