apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: global-secret
    namespace: cert-manager
    annotations:
        secrets.json64.dev/plaintext-sha256: 23ecefe946af44225ec378ddb944ba2768f9262e06fbbae397fae16f4bc32f61
spec:
    secretTemplates:
        - name: global-secret
          stringData:
            cloudflare-api-token: ENC[AES256_GCM,data:d/bCkuAcMtFFhJI+IOjoA47BN410yAQrfAMOEI3Q83+xxgiE6lUUJQ==,iv:xTlP1nSsOPgr1SEY25TJOLaPrpI4OL4xtm1vQ5jXQdQ=,tag:1iK8d+Y8XoSifipv5mGkDQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVW81NDc0WUhKSlBuYVc1
            bVNJMDU4Lytnd1JJMUVCSmgzKzFyQzZQWXowClNCM1lwbTlNL2QwbDhDa1RUTlM1
            dWU5Nm80MVNNRWc0bmJ4S3lhREg3MEEKLS0tIE9oK0pTUm5Oa0k0RWZEcDBpRThK
            VVZ2SDRSTFJRUWJ0UWpQNk1MeE0wMUkKF0DRdFXXSwGGfKDrSwlA7Fv7W3E87oEY
            0Htfz1/dEfdejjkglS14/R7tDME4EUmFOVPF6eTzRGv2H4g4943xRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:45:19Z"
    mac: ENC[AES256_GCM,data:q61Aqy3VOv33kYYvMAsPxiijE3u87ELUJtVpP3zlR3Aw3RhZ9Mz5XsNmM0TemGzSVC/Nhok+cYgrGUFII9Ehoq/BmEJfCEVo0T7UfyhDoD7GlvxEUrQs8eCF3ndc68Jv1unFca9QvoQy29eGXmjR2DMw40CqDyT4+xknJ7QAupc=,iv:fpmX7MIV3uHH2xWPVgrh50Ybt6UNqge1JObnqoi9LG0=,tag:h5u59GAWO8uA5EIMMMDzEw==,type:str]
    version: 3.13.1
