apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 31f1d784b431e18fdb2d51592527c28adbb28462e8b4e9f8a4df62aeb91a3dd0
  name: json64-dev-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbVVsRkxvSGwyaUZDM1l3

      SWdibGNERFp5SThRWStVWnJiYWIwYm9pVWxVCncyOGNsY05mcVlvU0VNNUNPemxa

      dWZvQlNUUWI1bzJwS096T0c3WjBUUG8KLS0tIFEvTEtrdzFyN29IZVpENDBjbzh6

      a3Ayblp3TDdBaytvU09lS2swTW01UGsKSr+fA2tvf2TXAEIg2qGyR5sB0qoHmYAu

      ikvNBW+A48ERQd0SJNf9ZXteVOEDmNaDicLe755YwvcvH80GeImeuQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:50Z'
  mac: ENC[AES256_GCM,data:kP+QZx3wr/tczxf2SVcXdXKFcTT9c/GSiDlzOiRFO4uKdTQs0Z42Zu6SbXLf//tHaHbXOzrnFSZ3CDfV3SF3A25XQw4FSGyPSnHTP4OMIMSvypaPo/EeFQLMUgnOTzt3MThQ8Ya5jWsOiDkI11jFeEvVhsCjbWT1ZHQDUFl1CTc=,iv:GrFQ9BC8djzftUvnCT/fqhxDgBQkq/74vh8/clKp+m4=,tag:EWJxqBnw6sMO7vnZw/zYOQ==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: json64-dev-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:cFfymo+cGb0SnVzbZ4jdPJZtNfU0wIh5IXL3pau0egLPGtGsTS+jag==,iv:ZwpMBGmifDUWK29P1brwFb+YpZ0gmH3wsRTo5LLI6hQ=,tag:4/koA3GbOEUs67Ew8/QW9Q==,type:str]
    type: Opaque
