apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: c2404e823585d55f9bb5d29ea89f2af9092892746ea4a172d490ca4a7672e7a5
  name: global-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudERuRVdOTDVQMXgxbUwv

      S0lpajdEK3pLSDdZczdSLzJFWlRtdDdnNUhjCmpSZU4vK0V1YkpYLzMxazhIUExs

      N2xoSFp0b2tvT3RBNnhscVYxQWxjS1EKLS0tIEh6eDJxaFFjQnMxdUROdmxJUlpw

      YjBoQzNBVVV0b1BESERYNHYramJZajgKQCBKeiEcRVYUA7LLNCgtwYwDl2BrgGC0

      OOW8gtnM9EXS/W1XGCHiT2zVdztbLXIVA/WziTx6hRj0EPbqXqmXpQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-05-30T20:30:36Z'
  mac: ENC[AES256_GCM,data:fBIkIOwV3YadVB/3VdjB4LtPIL0tPn5vxMJZExUkDa8dfp461nI0bX8O/QHNbYyLx+1Pmc0KV9jL8Q/HUTbktHcbBUdA7vQBbhdAapKcKevaHzsWXkkPltt6jgeEvAkFZzX6MTZ3bkLSBFLJETyWaob4Tai+W92EMMVmBbF4pt8=,iv:IsPl16kO+QMtPORXAID/nUstQ2q9VA1kxrOtNBaBAS0=,tag:avJCss4SkHPPc9iuW8UOxw==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: global-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:71AmFQoTHPtGel+qbW0Se+XiyW0jeFMiLJkIinvqaLnU,iv:kxMqSomJJQ0nlbn19FsIN+fUynsgUkC2mW4LxyPAN0E=,tag:bBNHHzcLvixUg3uMI9ZRTg==,type:str]
    type: Opaque
