apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 31f1d784b431e18fdb2d51592527c28adbb28462e8b4e9f8a4df62aeb91a3dd0
  name: json64-dev-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNHg4c2gydzhxWUxNMnVo

      YjIrRUVubTdmdUpMcW5xVDZBYzlGcnNuaEdRCnpvY3R5azJaYjZuNys4VVFhczlG

      ekFpaEkyN0k2MThYR0NHNjNJUzdKemsKLS0tIDlERDE1R3BWUDFGV0F3d3VnZzFE

      TlloNHBKU0hoRDd0NXF4VFVwU2FQM2cK+yZRlV0kKi7bT3/R1bBcVBHVE5zczk/q

      Zc6HuUosvdM8xSAGB97ie2jTIjdSnYsykJarD2I7cqkLOyZtEswtwg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:50Z'
  mac: ENC[AES256_GCM,data:rrIbUh7UpTS1BiaDFUQsUkXoG22pRovU+lQ0FBwjcwhI3yfu/Zk/LZX+cfEeRqBOtHNVsg5thQ/fftJvEtBARDy5uOiELcEesJ6QbyBoZ4Bq7ajgdDUoE4KcIQExrikzPaziTv3lNXDncQLvH6TGhvFKSQYYY7M8zJQpFAq2NJQ=,iv:roChZVW7eFTLgGAsRBR4fidf6d7CfccAuOh92gXrnMA=,tag:65YihRx86/XBQvY2bgocgw==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: json64-dev-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:YB1S9f2J4/8YPZu8P/fP/Io/oavV75AEtXXNXlM2dINaNFLIIoblXQ==,iv:2u4cSfPUaTOyzpjuxLQwbmmzQJj2gxSQd33p0+0oitg=,tag:lmotOC0kzXIVFYHPSXKKmw==,type:str]
    type: Opaque
