apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-grafana-kanidm-egress
  namespace: monitoring
spec:
  description: Allow grafana to reach kanidm for OIDC token/userinfo calls.
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
