apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-secret-key
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 64002e2dda8ea3681adb720762689c7386138de86dee66b06368b8a29d77d1ad
spec:
    secretTemplates:
        - name: grafana-k8s-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:D9Tkoe3rLzDxPUBWH2txN/eMC6g7fFtsm8nXl1swA/kMc2zT1JMwnO98rWBnCsqgb5zGje8vVnF0R2X7RxfG2A==,iv:FrPVkqkyLctdWBN21A02fduo1rHCu6FN5eN67s6xzBk=,tag:P24/p8aUf56ia5V3B4r5kQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTDlHSlBNZnN3NzBweDJ3
            MmFnYUI4R3FpazQrSExFUXJRbUZJalJ3andrCkIwZ1VsTTliRUwyUUpDSjJDUCs0
            blpMcThRZEhJSnlWNlowOEVrUWo1R00KLS0tIGgyVjFoYVRXamFxejgwZnM1ZlFM
            UmNZTElaSVFENkc3TWsydFMwTmhNUW8KgJm8FV3G2BMKhuMsbHVkfXLUjMBCJlLI
            Pw+1UL5XQqcPaazyBwNqlsSJIXJ3U0TWpjfwFsgDNFESZSt6wCDxyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:55Z"
    mac: ENC[AES256_GCM,data:fEFyh0zx553JCzKIUMmcVOnSVkVHKawns4NrB2jTDRGScSCJSzTBwMDM347Rul4i5QSX2OP2k++PlS2XdRocC6LzjuEsffqhKfqNd9loqnB/hLPDa4NtnGbQQlyCIx+p1XoUMUSf1J2wAcxc2cfXQCI+t9wc4zThrvc7NXgy4j4=,iv:/TDhz4zmQyM9g7LNpIcWCPwg74GDK0i+0qGbAoAE2dU=,tag:qRCChBl50agFjx7pIeX2+A==,type:str]
    version: 3.13.3
