apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-admin
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 2e883a92efdcf7f6482727edb75bf5a1b034161d7a49d31f95121c51c11027ca
spec:
    secretTemplates:
        - name: grafana-k8s-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:bEQ+Dm20nxflwiWdwvS+mm/TgSpOe8FQXeCtjB9eF6H4APn1rjAAjtLtsN6YCbDbLIqX6LJU+Z7nzQC0QL+LAD/OF0LomYQz,iv:jg3fZQn8Uo3RRwez+GFhcZ34gQI1lDknQv1YQGM79DE=,tag:8agcTpP9K3DkG1j/4HVb9g==,type:str]
            admin-user: ENC[AES256_GCM,data:cnziOsk=,iv:Ol0/15kt7RwdJ2AI95THMZjz2Gw5xAt3BNoOOsy0APo=,tag:U740ol5LD0mW2CixHEH9aw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa2Q1RURHZzJPTW80b0kv
            TGk2MzllZGxNL2VHWjA4V0Y4VE4xUExzZGpRCndvUnBSTmNsamhpTFBGa0t6SG9w
            enh3SmI0MVRTQ2NFTTFjK3kzVVl3Tk0KLS0tIFVoYXdQdVZFYU9QamlLaFEyUndt
            eXdRYjMydWJYdUgvREttVWZOaTdxajAKboi34m+PRHfAwF6MLT/eR7vIynEKGkdT
            4AUKtnJbilagEfiqTefx49R2TdrPUFV0vP+GcUMWI2n8M3+KCX4/aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T22:41:07Z"
    mac: ENC[AES256_GCM,data:yy1VEhJFkgw0mYg3Bq9NLSehOJARrn7KkFFcKQC69si7z8Re6OLwYDGJc9QIgz4YFvv+TGwqKEU+aqR3uTIBtfO+h1EozwShRjxTeWluMQN+iLFjp+77PO2b+ugZIbhdmnfv41Xqn26vSlhGpuw0FdUyooFEIx2xIkbIrfnwRSM=,iv:xgL09h2CmKJAF82+0OelvUx+HrvRNxZxdRevLYLJKBQ=,tag:UP+Oe71jmtkwaQ1xk05O3w==,type:str]
    version: 3.13.1
