apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-secret-key
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 64002e2dda8ea3681adb720762689c7386138de86dee66b06368b8a29d77d1ad
spec:
    secretTemplates:
        - name: grafana-k8s-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:EfW6NDyayeDj3dCAQjmmvCVZqRlwmAksKuCyzCmIgcwWysTmuGsM9tuXy35C11X1o15P9afAPvI9dCPNHW1/MQ==,iv:FKR4wa845MdGpJkMRikyrqNImKD85TB8yayEeid4Ed8=,tag:ZzSG65L4Oq6YmeeQMc+6SA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VGtQeFVEd3ZlSnI4RFpm
            VUpjSmdMOWJCRHpnK0w3c2ZNUGc0VENZVVI4CnlwVzl0QW9xdE1vbFpOQ3JUR0FG
            b3htVnl4VnFRb2lWZUJQN01YRXBhOTAKLS0tIHhMOHNLbXArdnZuTE9WSk5WSDFl
            Wjl4c2UvSmVMY1FKSlVMUmthNlNESDgKIOnI+E7IykTVtmxZPSE/37zwwX59aaXG
            ahsyS67wW143pWwbi34ddKVE7jPPjyVARy6gc9acB/kUxsf8fgCq2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T22:59:05Z"
    mac: ENC[AES256_GCM,data:dEPCK0Sm888DQ7UB00+XuhovmRiSNjUYIQhirLYnBaDoasyCZk2mP7Hdn6A9Rs0rUMgJn86jeDzO7o39J0p/YWsKZG7irnJkH2vualaTNtrU6nVYxAfGFaw6K3Ej9lc6KTv9VUctdL8vWR03eMIQZlQIK3TKEosJDiQrDppU2O4=,iv:CGcpOVwfSANcn9MkJHM4a8OtlkQJL+cvCPSV1Yekaf0=,tag:4RbgGMPvYX8maNFa5A121A==,type:str]
    version: 3.13.1
