apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-oidc-client-secret
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: af86886cf11acd392282f4c88f7384323ee298375880babfcf05679a230b2315
spec:
    secretTemplates:
        - name: grafana-k8s-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:9Bdhu+OfDqvXqWv1C2Cekhrxd7vjvlZKob9W7k4WETkrtYabNqUmriQkFU7zwzHneey0iAoERhXuY9DjdXPrZiecTEvXS642,iv:8vLdD0/EJfM+IX8LkbspITJb0A9KpQpryNH6cagmXxs=,tag:1uBR0ZYuASJ/6Ee57J2z2g==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcnRhM0pTdUYzNGRQWjRa
            NWJyUU8vSnJJczhianRXTWFJNTdMbFIyaG5FCjJLVW9Wa3lDMCt4THU4VFl4TzRa
            VS9SbFZndnJxZCt4OGFDRkZnbWl5aTgKLS0tIEZzNCtKTStlL1llZlF1VkdBTzU2
            Qk9lQUViOXFvRVVnYUNRczlOVEpoZmcKIByL1kMjyWgb91U6n9Z3PNeOXIlcwGri
            KBxrMbnCxTcOhjglIhzRWZff8Ib/jmCZ6/3cKVkiqzVZ1bbQ5/tPZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T19:23:42Z"
    mac: ENC[AES256_GCM,data:HI46OJuncGbjSFM8qEuyhbQWLXsyfdhEf2B9jNabxkPY83p8YuQ2OeV/I8GhB9nAM0i0mwBN+QdbLq+2JEXXhLCCm4MI9kps2KDl1kLj0uNdmPmUiQSwc8abWSLQjHDTECXBUwqkQo9lbyZB5K8YT7FxqdpRfvy0WPd8PvHvFwA=,iv:/ch7F8+cpYIVTziavS5WbjzUewebust76uV1Ntea8Aw=,tag:cBHcRAy9ShGzwIza4652xw==,type:str]
    version: 3.13.1
