apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 177c53541bf66b4bf0f696c0d782b9d16d79f3f626b67434780ecb1ea88d3a95
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: monitoring
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTlY2WHBwNGxTenAyeDM1

      NEF4aWpaUnhyc3BaRHo3d3VIZDhxWk92OVJvCnliVTRrNWszdEZKOVQ2M3R0WVB2

      cE9HbGVxUkdVT0RyclpUNkZrOGlHRGcKLS0tIHdBbkplNWQxU3FZS3dyT3h4KzFj

      RTVEZHVsd1AvZGhwT1FtazhQYlNMa00K4qlp4gcHejOip394rWu3R6qzihNBSUH3

      5R9lNgmtdS/uiTSdHwyd3lWggC8fUeFa8kzgc6N+u3ogCmkJgldl1g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-03T01:06:23Z'
  mac: ENC[AES256_GCM,data:UjOe/yUQ/fXwmRf8FrebrUyfU+hhSvfHUyUHh1/Yt3jpJWAqaTUKi2O7JC7frevDxu32exYE8Sjqs+L8HmTvn8R+GWUSX6iZLeFDgy0pI9MDgYICGyJp4WCEVaT1lNX+dy1bUO6hFSAXCn3iA5ie5PwWwqu7Qs0F4WTQRZcPnBw=,iv:/QYOF74mPjqk+rUbxirWTKR6itIv1iiyFe/cjI339xk=,tag:lCR24BdyeQL1srM+BwGlKA==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - data:
      admin-password: ENC[AES256_GCM,data:tnkwYhE1rsMgP9vsnGHXOb7yH7ChqgHFKx2vnxVuCh5TUMhFqpkhCKI+8s3m1I2PE62aBIlJQ3M=,iv:asCx1swGq2vv40RPxTaHGAf3rZQhdky7rYbCNI+GWGY=,tag:W4LPV8eWQ06iJihwtNjW4g==,type:str]
      admin-user: ENC[AES256_GCM,data:805XynqXXbQ=,iv:QJpVezEmls5P/JBCBoQfbQi26i5FO7jVSqN5Q74jnKQ=,tag:VfjQhcVpesEpGFjR418gIQ==,type:str]
      ldap-toml: ''
    name: grafana
    type: Opaque
