apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-oidc-client-secret
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 99878a1db155c248992eb14822b827491e5e276f70e7d99a32adfddf583a6e91
spec:
    secretTemplates:
        - name: grafana-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:1nJRJRaKN8AZv+CiYmZ8eDpdaXUnA22WUU7aDmVKEa1d+obxmMUoT4P6peE4fPM1w9mOraZmCMKkdCtmYl7Ev3U+cA1HhXO+,iv:G7JBWjt1xGvoc09qakt5LhFg0roVWyZcutzgNn+rI8I=,tag:/dTnxHc3uJYPfPCDnMXI5g==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZHFHRDJyKzR1R2YrVTVH
            K2JwWkhxb1hOVi9ONnJ2NnZ6SUxNUk5DK2x3ClZ5Q2t4NzlGMSt6eVcxaktjMkUw
            T2ZQaFE2cmxLZkxIaDZzMFFkMUxJYTQKLS0tIGhsMEpBbkF6R2VLUXV6SFRTRSth
            dGx4RzZ5TEp2aDBHTytQRktKZDZJYlEKanqyUB+khACgl4DtLX/5AIH1phpHtBvt
            Nr6+6sp8aokl736CpWXYm7AAAIcfxu4t58bkzvQv52DcFMNFBg8nag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:18:27Z"
    mac: ENC[AES256_GCM,data:vFc3PazZ4JP7UIgLbAElHw6ZZNqxM/Y0uFKJpFcXcMghLDFt0SkEihrvTFQZhxuLlHBpwyGzKTBC5Xm0lJGaT0yZlvxCH56emMGSnMjtlGvNxv94jQFTlnDK3OFLeOp3A5yW6BExybsCDKvf37P/EcfQOXZQUzKxcWhB/nyX7eg=,iv:xA1w6UYDC/iSHt8bK0CybawNHLZ6puLouvBere0xQKo=,tag:XX4JDYYliOPP4/zIuX//WQ==,type:str]
    version: 3.13.3
