apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-oidc-client-secret
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: af86886cf11acd392282f4c88f7384323ee298375880babfcf05679a230b2315
spec:
    secretTemplates:
        - name: grafana-k8s-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:is0kgFQlrpKBuiwpiOqr5rGg06U5LQwOCnhXZFEqxIJ1HIVskzcZwZ0Y71Ev4XTm/HChszJAX5ExM3dD0WoDeBb0FyPK8lRW,iv:gOCMo0vcvJ4XLIhwuvgkKKgDC/TBS2f2VTBy+BI8LUU=,tag:QeaLJZiT5eioZDhyuvgI9A==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OGMvUjZQT0grYnZXdEt1
            OFZIUGhWMndsNnM0bC83REpVV29BcVBuTkJFClhzaU1XWXd6dTh4U0tDQnBjd2JL
            cjFsck5aTS8rdTlDSzdRbFlYUjhHdTQKLS0tIHV1dWNiWmFNY2xiTUc5NE1wbXdN
            Z2VFNlEyRFdXUUVONDRKMkJldE51bzgK6PW+Nq1t2aWGbc9Tr9e7/Vmuh9fUG1mV
            v0Gs58ettGkHklL1kuqFlIZ8v9cNBZgOQ+dzlWjf8mANJKlTh9ZU4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:55Z"
    mac: ENC[AES256_GCM,data:TNnDVZ70tOShiKwhxbVrob8LLJTxTcw96LrY8b2Py/Uq/JWsxWP4uDO96UmNL0KvHPTaPkeW7WOfWOwLa6JepnBZUnhbQ1pPFaLWDwwjoF0j0l9o8i2lDhnmMPNTCRNHyP+D027SWF8cd4kIsyhLqBszKstsSGBSEKJ+ALBwjxA=,iv:jifFWlfSRFKuWuojG5JaF6JJUcR8MalSneeYxrWbWCo=,tag:4ceJz//42OnoNUFbrUNrpQ==,type:str]
    version: 3.13.3
