apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: e802dc58f9f970ee3b130169602e2407ddfbed96b80926c70e504b2e69f957b8
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:PQpK8GPtorI4QByxQs1641y5YnQyXpxP1GIEeBxrJI7Vkjs8rsNrswfqqUQjSanvtlLch8WOelcU16+RwPuBh71HrIh8YHlB,iv:QR9p6D1ce/c4QsaRr7yQYGKnfGow7zvK69xsoMB8ass=,tag:Yr7VKUJI4q4eFuc3x/8U9w==,type:str]
            admin-user: ENC[AES256_GCM,data:wKWsofU=,iv:E24MHVIIfwjSKC6/GL5yLGFn3xebNhh60zuW0mPGJWw=,tag:8gw1LEsEtjBcRyiJkpWQUA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRFJoenJuNFY0Z0NyTEZj
            eDFOYlVlK0pLZDZ5dDFXNkpOKzFTeDk2L3dZCkpLM0g4SlZCWlQxRVRobC9Ea09O
            Unh1WHhsMkZZYkF2NGNGczVBc1dLckEKLS0tIGtpa0xoZm9WV0tYSzMrQ3VYRytS
            RXdoN1JoVzBDUUVVQ2srNE1iTHAvYVEKLYARDsNKNmL2mclhCh6T2BYIUWZ5kIda
            0Eo/w+DomtLYT0grbSgTyqQX98Pjmu9EeJxzg3+7ULh3wxqhA+UI3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:18:27Z"
    mac: ENC[AES256_GCM,data:hgJvxH1slW9D5MunCJpO9HYt5DCbfLNFHvWsQfc4bQtN62QFS7uaSss61y954OPs/9VUwwGycZzJDiU2+uLtWjTiEa+di/j7EkBL9+PodsmmD+lrfpC1w2xN9L00khdE7rvYokB22E6jLn1RwfDa+dDEyksVjjdjHBzXYlYxKrg=,iv:XjVJnALnsQRnDz7ORniou0wyXHrL869kdqaRIT7cMiA=,tag:HLIf5Pkj4USBNWgGZpxxqg==,type:str]
    version: 3.13.3
