apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/component: admin-secret
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
    name: grafana
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: a49e21a7787fb4d508afdbc3fc0a1b02a19397d86dbda513cbd7584d4f6d1019
spec:
    secretTemplates:
        - data:
            admin-password: ENC[AES256_GCM,data:mwi/eqmMScERqw1NaCplhYXwkSVL8D5SYqUEYAW31hhTYd3SQXbmZnNvPkfQ2YhPohSNqmr+nUw=,iv:udfsvI7Tfq9Og/xSzr0Mmw89lmF2kJV9ATQHuHWBC9s=,tag:sGc4TXL3jdba29DI66CIaQ==,type:str]
            admin-user: ENC[AES256_GCM,data:7RXOvuzoNq4=,iv:oKFlFXHfdMPxihRPgoaKPu42VbOYr1DJl9/xEc9gnPw=,tag:a11M5AgJPDhbfVYJh31CMg==,type:str]
            ldap-toml: ""
          name: grafana
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaEptVkpXUmE5eTRBUG9Q
            NHVZcDhzMnk0MUpFd1Q1UU5zWHc5VUNmOTBZCjFlV1pQZ0ptd2hBQ1ZqRTlDTXdr
            MEpnWHFPWkgvQW5LblhOZGJZZUtPQUEKLS0tIDE4MjhhN2J6WXQ4bXVWMFF5MlA0
            V3Vpb3ZhcElnVVBUR2ozcm1QeC9SRUUKkIOTHa8/pt6rKxl+UMLqK5pDsLyxAYMZ
            Wq34I2oZ3K4JBftDSJS0I02HSCQzEuY3x+oJsDIycpOssod9mSQ1Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T20:39:40Z"
    mac: ENC[AES256_GCM,data:ZN9Oj5Ct9jANlc2fJ6sAjS8VWcM6nv6oYR3AYfo3kM8XsoOnmjsHytQyA/4KsvHvTtqVXQN7dNzNSwdk04ICjzGMkvpg9xKVCf3LoMGHv9jtjmLyUK1aWkbiNsnUZLdJD4ruI5d67Sb3DQk8JHH5cEqTHmb1AEatXLedeTmwIgA=,iv:KLaQxgiHrEooHEQR1x6H2pOj2VLo0/ZSLv+gQjmbT0E=,tag:y4qost6iZVVxnFgSA4O2jQ==,type:str]
    version: 3.13.1
