apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-k8s-admin
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 2e883a92efdcf7f6482727edb75bf5a1b034161d7a49d31f95121c51c11027ca
spec:
    secretTemplates:
        - name: grafana-k8s-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:oysPMHiaRgdZ8GsIUQ4NVU02jHfMm9uQrE8f53oFCxPY9ZwtWrFUnq5I/h+RXd+vq3cEH+4TXPL3aNDRsararoXWubGE0/9y,iv:BKIRzNdUIimL4YV/PG4Oou4QeqWp0i1U7USBbBIY9mk=,tag:po75NulCOUbu8KSVhtzGbQ==,type:str]
            admin-user: ENC[AES256_GCM,data:+Df9KPs=,iv:QQdJMdng+Lbi5r1tysy3ghzWwpJz6XOWCsrof1WBFKk=,tag:ZrF4rp6Y2b9hRDTEx6Ikgg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVFKclpEdm5kZkNLcEFr
            elJzUXluRTNQNWZvRVc0L1A4TC9iM2s0djNjCjdKVVNENmZ0SVlBaFhMcnNWYncv
            d1NFNnpMTEZnZlZkdUVIWm9QZy9OcjgKLS0tIDVMbkh4WVVLV3FDMDNnNmNraXRz
            M1hTYnhrbDhwL1oxdVR4dThjcGR3ck0KRgayJiKeyuYO8zXDZwirq5PMWqCOXg4m
            QO2JCQgN/94YtOY+ccgjru7L3CUNUqf7CzXHE9ZPf44+r3QRnXHIkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:54Z"
    mac: ENC[AES256_GCM,data:VeidSOU6cMMMJ6CcChAm9q0phnGs0h1N0YPJmjm/ekucvE2CmTdANP07UW8WNiVTJLs8vK2mpZx/PB8GTWPiKGCx5vc4ks/bx9ZCDSzfRwA76hridjgxAB1IEdSD77HXFdHAUNlAS8Esa8kd54pqMyvNVpJWT2ck91EuSIaTC2U=,iv:/lUtI742wAGsCTeXlfgF3Uncl6eFl3YgKGZrumAzhbI=,tag:qU/0jPfkGabrJBXvhJlweg==,type:str]
    version: 3.13.3
