apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: f8faaa09ea5cfd83f26dffbf18c91bc38939e3079faa98c5e7c3bc88d0ff58bc
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: monitoring
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RCs1K2lDL0pkZlc3Snk3

      YXdFd0xFZzduWU9XR0pmNnppVW5wYlJ6aVUwCkl0c2gyWVczMFJsTlB1OGJmNlZT

      NWhEVHZxTnlHVXpnZXJHSUVpVkNvbGMKLS0tIHdMc1hncjMrMFByYnUrUGJIdVlu

      V2RhOFFkTzZ3QnlYMnJITDRYd2tjelkKQQWadKcUusDWuh6FUNBb70Kl5WewcKs6

      vhvxgghtv++cs+MO0PZxpxFiLV5X8xp37aVMtGToauCQY5UYl+iq5Q==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-08T20:28:51Z'
  mac: ENC[AES256_GCM,data:xAR3FyZCW/HBsbFOF7S6Oj6OYF1xnMlSPGV9mxrUOKZiK0fslEvoviqefT3rJ4j1qEPMipRo8h73UQMH2NGsLkHht8M9Fpe1shMGyTpxlZ06XpgqXQrIWBhip55ZY3A3gS8aeVholYt/zhTtIRlK77oV/wqGsScZJIpjGoUPQoo=,iv:3b0KCi/iTx9XHFcIzYUs1iW9MrT5E20CpJVPEcjBDo0=,tag:yZ49dopxOs0GJ+Z8YVLjRA==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - data:
      admin-password: ENC[AES256_GCM,data:CtQkITL1GW5EBOPRO9r+Y8Z/1I7EDOPUoHh0rkHzjQv9sfA6yyq3lBwGSPqB+YAW91CrebaMFOw=,iv:hWM50iFKws/HWgx/Ce7MHBwcqibyelA9odKCwvvtk0o=,tag:m1EEL7sw0kb4fKbtug+tPA==,type:str]
      admin-user: ENC[AES256_GCM,data:OQDIdfUxcbE=,iv:kLBJ5MhBNVEwBn1bUK4Df/+M+lmDvQ4tDKQJW4uYPwk=,tag:FVVkWx8pCyeZtxGN5rhAcQ==,type:str]
      ldap-toml: ''
    name: grafana
    type: Opaque
