apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-secret-key
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: c7ad89696c4ff2b3bec0be0039afc6b36f3c27e5b0403cb3810d48c1e535a8e5
spec:
    secretTemplates:
        - name: grafana-secret-key
          stringData:
            secret-key: ENC[AES256_GCM,data:K32TVBZlYx0Ziv5gDVm4iJn3Fm+MtIFbctA31GLGUwZJJLnOg/rH2BGEKuRys1SldYvs8b5L6SiGK+7SyzEE7A==,iv:GfL4ilt8WWSMW5bOG4UTEt+yweFbNPPxbwJW+ddzzUo=,tag:6A+CM5IXg4G6aO9HZqYxQA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWW54R2U4QlhkVm5PL0xI
            d2N2M0dkNmZsUWVSZ3NUZ21GUzAxbDJ2aEJRCnZ1NGtMYTlrcTVEaFNVT0FZcDhY
            ZVdMNFpINWpQUWhweFhWWHpSTEVndW8KLS0tIFF0WEl0OVllck5ma3Z5VWcvVkZX
            STBhd1E4aWRuditKNDBpMXJxdUZVUWMK4rVzbjdOzysD19ZfbldmDvhmBqaFkld5
            5d+ylcDxigZY50oV6tKGOCahjIdcjbIu3au5nMEedbRHckfm0c4NVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:18:28Z"
    mac: ENC[AES256_GCM,data:h97ciU4aOl0Fhh/jlRZmQxoa557lUw40i/1fL/lmoh0dZHfsjO3l3gdKyEKlJ6vExXXXkYWPV+YF5CatJWm1oSdoN1/uNM82ELbn+d/zSdQbFkI3Wo0uAqb1f5q95kRcGbeazFYAC5WzxU8vPfYCluOraIDJGdBfgkIVxAXv3EQ=,iv:KwPNLIXppd5knlBU0PshjFYg/C3K78JfgvzH6fVjIfU=,tag:xkZjdj+j/dk8E+qNz1Sx/Q==,type:str]
    version: 3.13.3
