apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: alloy-events
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
  name: alloy-events
  namespace: monitoring
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http-metrics
      port: 12345
      protocol: TCP
      targetPort: 12345
  selector:
    app.kubernetes.io/instance: alloy-events
    app.kubernetes.io/name: alloy
  type: ClusterIP
