apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: allow-metrics-server-egress
  namespace: kube-system
spec:
  description: Allow metrics-server to reach the kube-apiserver and every node's kubelet.
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
