apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: matrix-pg-synapse-password
  namespace: matrix
  annotations:
    secrets.json64.dev/plaintext-sha256: 14fb57e6e831783a03b0d08c5a36e3483df42340ed9cdd559cc7c3dd493e796d
spec:
  secretTemplates:
    - name: matrix-pg-synapse-password
      stringData:
        password: ENC[AES256_GCM,data:2iyozwcemcLhq0aq4Vh3CTE7aa7vuY4RtQJuWQdExrF2K6NMq0YiJ0q3wvgfgB3C2nGQSG8qQE4rOiVnrnjir6TQTbT8q+FB,iv:gDzQYfHpqM7qnVqxoRflj8QmjbTozgiAnbfsoYUt12o=,tag:xjhovLrEGkTL4RrrIR3VQQ==,type:str]
        username: ENC[AES256_GCM,data:E6dAvZLKxg==,iv:qLIBc4Nm3sgGLAgdkS11uLuRtPwcYntAum1MP3qdhvQ=,tag:9GoRs8x81DosTU3iHzls0Q==,type:str]
      type: kubernetes.io/basic-auth
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWlpQQS9rTFV1VFdaYmhh
        ZTZpVHcvakpOQmU1YWZIdXBUQmpOU1BKVzBRCjQ2ajRHQkY3K2ZGNStLU1BPenUr
        KzJyTUQ5YjFlOXhONTRHK3FOMk90ak0KLS0tIEZYeFRPNW1wRCs2N1FlWXBmTlh1
        TUJJYm5RLzVBYWhmdU9NZ052VnFOVTQK+OJATgXH8unAKXBUseavFlRl0HSiNIY5
        N2n5btddLTGm16QVvkPjDqwUyYzoRhi0X+nV1M4TL6m9KTCd+Us3nQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T03:38:29Z"
  mac: ENC[AES256_GCM,data:FRjpDzx6fkV7vtqy50hrZAWyPHxBYf7IZN8EJTTkhsJcc2S9guYjw5rxCt8u3RRtr4olFKiBiWG00cWOj3xsME7oCvqVD31cD8SoehSC3OpPmIv4NZthKCjFu7shV/iytUUWAtixeo+czkutqPRnuinlxdN9KVIeblwO0jSXVEI=,iv:geNlqC74XsG4+3ChIPCIrTKoS2zaOwfsBnmBB+66GK0=,tag:Or7x6p3FmzlD+JUG8pBLHw==,type:str]
  version: 3.13.3
