apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: synapse-oidc-client-secret
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: a06a9869b80e5f8124f5f9a58061565dea94caf84c4201b3fe098c7e1ff4813d
spec:
    secretTemplates:
        - name: synapse-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:bQOdEnUCTwGH5PNofFJ4tu9DMnkcUoLKhWDM9bocXaQReCkQFP87GhxE9OdmqmaSMa4aHd3Nmvzn2xDb/o1Y+y14a8EjBBt3,iv:Jp7pRqSPOFB3WaSGBWsHq+e/0iMbfb4uSGz3oVBxxgI=,tag:Jtb3IY7flJ/1w4tLuPBF5w==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ1hkZHNCWWNTZ0hoNTUz
            U3d6Z1VqeGl0Z3dSSDFObTZEUlhHN2NzTmlNCk9KemtHM3ZuSWF1RmEzdmxNL2VC
            SHFvdmlWL2RZMXpmUFVhNEtxTVBMdkUKLS0tIGY4SERRMmVVYnpLY0IrOEZsbG1o
            enRNbTFmOHJVdnFSWWlSOHp3ZVN5M1UKD4ZdyxvvWMkMW1jIHObnHC45VTtxuseS
            3PJQVRJ3TZgypmnczT8OdNp37CSSSw1ZFqJAmtLFBtttLbwnkg373w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T03:38:33Z"
    mac: ENC[AES256_GCM,data:xBUK+fhBo4Z/90bdrnPlN8F0+SIFfkJtOSzQflrWk3ujbJ07cWRdtq6uFgmDtkU1IFa+4hmI+NJ5IwQs0gJKcnuffEbeV8fWJLdvUAZUeMvVf4ScRq9lXNBF1DxvMrmrkcj1+7MrrOkTSGq8FS+CY5S+oEnwOvRpEN9asD4/YIc=,iv:F3FB6FAcfBbiO3mG1B95AMyKv/jD+1E6Znxbp4rhd+Q=,tag:rQOOpZm4mS1SFPH0Ad2sWg==,type:str]
    version: 3.13.3
