apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: matrix-synapse
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: e91d2fa118995cbd69c8f13796d796cc7febb86743062d9214480ba1450b2add
spec:
    secretTemplates:
        - name: matrix-synapse
          stringData:
            secrets.yaml: ENC[AES256_GCM,data:xfhaXia4eWKAZoaNXRITLCZZiBbLHio7x66iYa78DEr2DeXCjJIl5YWa4A7knK+vafG8EsBCWlFE90lrn8nG4l8tsUJnnAw7GP0DMqza34/qJ1JEkQze/i9q9TpZfo+ddN1QRhZp+G7BuTZlDhbEztwXCAusD+UVGbimkcRv1gxcxGssxBZc6+qhoLtui2LembctPAAkcl6Z8GTzeuIeV8O9zrsaRdxGow3c7l+ghPIrVuAaeGkViDu9zTZhAIR8TI7T0CvHsb51s1U6rxHASLQgV77Y5xbJU0JSsu4qGt5FE2pi9eYW9VjEiVcaccJUL+owPvWS1yrazkpJVIz0oRjvLUI5Z7QlVRO7q51HKj8bZugypvLH6rHgydr+hHYWYrJ6OzzeVeU9yek1PrjuPTgyTMBCFzoDMwvx2koBhYMyDMTuezMIjRazZ/BLzuStSslsUYdxFgzl1fyP9t8HPpRyoS7/l2vjbYM2M6Gqa/4XSPZjWwCC0qCmRAIklUupy+/1X8+RbgUvb9TOtCfWYnsiA6zgpzvAOrSEoF8oUdl64VNIYKgugpcNzmX1JJUNNXqqLdZT6FPMvdQHyHjodRt4PbvbrxrdsaxPdy2q2micZUjaWrH7XruhmxVGyQsAacCDTU7LQeChTtka0vft2dBGwJea/JbXqfdxyqzRmReTJ4vCmYnh5/gkG5btI6kgCUiYTb9C0F6Cu7KoyO6ByOw+FFNBjZNKiitCAiVffvSVGMyQcDWPfysIwuKHG5J2TW6KmpBVPoZQXzSwU8qYcpD9aLEHLy/cLH1f+PSlEsxuvSEFR90p1jCugzjY21ltzqfpZoAMMPvSdl71ufgJmrf1vrYRaPCCnKynTt28Ag77RRd1qiRtLJo+gMZQEv1eH5IyUf/OCChx0gN8ItWCyfUXAIZ3Oam/zrpp3Ezy+GFEnGxEBvZWsN76wsvJmw==,iv:U+OXV47WgDviVHwajf3y+ze8sCpXXL0V0O035mpZW6o=,tag:Xp7NHdtFYcN/DMnG2NVM+g==,type:str]
            signing.key: ENC[AES256_GCM,data:0NVaRgY65G3eWsNJsGuvoifkEBaSsLOpYg3kkS2I6aQ0Ml/KCUEoJ0zJOUO94BU63jpJDvZB48DGsA==,iv:vCQVIgtsfBGqF0kOICmsA9OPv+5K7N2FtftkptiVxh8=,tag:5OoHReTVjQbU0PJIPHsgaQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcUNOeC9vTG90Z0FHQW50
            cjFzYXAzcmc4MUdWQzhQcWQzZ0l3aitjaUVzCmYyc3ZjRkNWWGtQZVVCNVpFMjlX
            YWR4YzZvR3ZjamIzbkdCV3J2eEtOQjgKLS0tIGQrbW1XYjJoNkdheEowODFaeVRS
            OWw1UjJTSWd3bER0RVlqNHFkR1d5SG8KrUwsyHHdDR90xXdJ44Sj2LOeyeCwesFW
            auBwbYtCR9sD4FTfC9tqNUoLQqXr1iZix2d7mmP0NQvgbyPx0FILSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T22:44:36Z"
    mac: ENC[AES256_GCM,data:BgGYVPsXfAMNzyVpF4XuPHphJm5cyY9N5XZjRLjmVwNUe9rIkSHUAgCMxv7oJpvSl9/qO+RyNVadsMkvEcIGZgQFfM8PYolopX6izFr0T4XgoqBWpgkXolXHL+X7qcwxUfgFWzhWio/jtckz49GHy/3FrQFZNYd6ant4Y5/aWbU=,iv:zuOoP9qv/d+XVrKll3BIM1gYKU70hoALgijr5MLTYck=,tag:dstmkBZAeI9iTGOldSbOhg==,type:str]
    version: 3.13.3
