apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: matrix-synapse
    namespace: matrix
    annotations:
        secrets.json64.dev/plaintext-sha256: 849371cde902adf1b348d301439f4e376a9e6de79a9991ffc5689c12134e3c16
spec:
    secretTemplates:
        - name: matrix-synapse
          stringData:
            secrets.yaml: ENC[AES256_GCM,data:dJ2QGE3uWTuvYTIDvoOMmkSs4e8pp6fLUKkCKx/tqXPVFM0xaApCbIhGUwpie6rTagmdaUPoZ+3u/W+p5zC2l8xByjKRzazEfbyaI3BGQ1XvY8L8d1ijzFZnkmvY5DJvInm37GmkDo5uSxnezMPxvXsHTXHYlQtAzvJyEitEEO/edQaiQU9Ygj/nU+/7WgjIK0hGjF12TZhMSNWNb7FjtjMotZH7Uj0J5nKr3DEqb+OqSA9qfwIbFKvNolDFkVg7bGR7CD0FRaOH5dNmrbquN7LD1kQF+WwrgE8ufJNmyVauu4hffpgrAEyXlqlLGLrfF1IADMtd+Bc9TZr8v+SMweaeZU1QSdmYIQtX5VbdNgeH6+IMmWu/tFBiQhIy4TXTiOPf1lksnsxeKQNvJGK66LNlVU6IXRwBuy0KMEaDoBE9U84bjDvx9eODEd03hRiQliGzo9SbcVpR5dqSgcdINrOQDeZDWWMZ6dm3ZYQZRiWftvrgaIRYoM1BNYYHaZXJIwWZyLebG7qRMh6pN+D+3Bth52V6BV9oFCDflFiwDMYa,iv:k8EQOSKUXZz989KgncLxpIYF9LRvNN42kUhURi/7Zcs=,tag:cVMOsahigyMi3ru2vw136g==,type:str]
            signing.key: ENC[AES256_GCM,data:8/5wFTkhR2g3Que9B7mca0Rd6pLBNzjFbCu1rxofDJdRWJao2P4K+ySqGEDBEOyn9SueyBTJsbvBRw==,iv:skZ/tYUdc1Dbzk07Kybjio39AXQE/1GP2PR4gmHk/nc=,tag:KsWKd9mR8HYv15oRDhi6Eg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSTdlMnQ3ejlBYzgvTk12
            ODBhZ0VJZXNTd3BMcVRheEo2RWV4UnppK25vCm1Rb3NVUmJhbDczTzRhY0FsbjhP
            Q1o2cXpsNXJxelpDUHM0dTdEUjNyYkkKLS0tIDNWWHk4NkMrWTV0eW1uYzlUZUV2
            ckVOYjJ0ZEp4ZWJLbHdiN0JOakFZdVkKbVF14mGRZTQcxHx4Y5FoKu2wnSuQga5/
            9uNAyUijGDZEAR/1MeTBeJvtGLTnYOHKPyKYSZDGiAnU6Ei/Tv+m+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T03:38:32Z"
    mac: ENC[AES256_GCM,data:A/P1Bbcc0MzgCUXL7ikLkrow3k4ahW1xZgqPRQfP8tyuRaIvezPVsLhRxAM/0LVWlIHeFE5cz6LfJ+yNs4dG2Tj8drR5yO51paEKe69f91tkA9ooFYupc1uU4qzvGzK9usDK06xU0WcKnysEp8U3Pz+NboqvLtNLCha1w8ab3mo=,iv:0qykinbsKVsTwtnZfsdrQ6AdhuJdNh6c+o1hEfVFQ+Q=,tag:dMB369Oanz6SgVsZhBdeQg==,type:str]
    version: 3.13.3
