apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hubble-ui-oidc-client-secret
    namespace: kube-system
    annotations:
        secrets.json64.dev/plaintext-sha256: 147f5b9639d74d2d3824b9e727e3b46f421abb864bbcf2d3bdbe526287941172
spec:
    secretTemplates:
        - name: hubble-ui-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:enRkeRKezvYtGNd0OYl65UB+WX7KQBKguLhF4/AUQEgoLaJLwo0GwvmLJKplTMNkuOpYoCiF74ajdZEzLeSs9Mh57VrOeY78,iv:mqsf1rWLDHZss8Xk4/RGmBzCgJV6EOzdbern2i2Tjbo=,tag:HsM0F2Gu0VMgLs21cXbjEg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWJNcDZ2ZUYyZHN1NEM2
            emRnM0d6blV2MHZxcXRlZWt6NVRZUWRaYkYwCjZvZmdqTnZISVdpOUFQSHlnTWRv
            bnVwOHFpL051enVwNlUrQnZKNjAzZzQKLS0tIFc4Z3hDd1U2ZEJJNC9wSmdIQXRl
            TEt0Q09DNkd6V2h1ai94aDJGNWY0SWsK3vAJRFuJbhqdVzubEccRyUvMlinqjq86
            Z8KxGNnZ78lkqxjhMfv5ldx+VA1Czg+k4+JWf8CUm5Nw5dIabtlUXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:52Z"
    mac: ENC[AES256_GCM,data:r7iCS0r3X5NIk38DNnlRHPliXZyKvLCjf/z2vBn7yptZsFvbU553R8hySDwz+nnizKOW2AUbxH3buV+eYhAR9GXCtgn0JOcpynMyRpzWCkZk5VO6wL550HPTbGaD3NGSE1bnFwTqXVoXLwvTno54huW0stGBzjDwSjk0OJMrLYw=,iv:aiiQrjxRAGjmnx7l/ZtwKDFAXitM0gIFIzsgruAkgZo=,tag:aS6pue0PmBiKsVZQB3LkNg==,type:str]
    version: 3.13.3
