apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: b59808b699ec5cef375a19ad78f475846a7f1edc85b4b4e97b35dd7b3b0a7384
  name: hubble-ui-oidc-client-secret
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSWdnS1c5RU1DcitoZUEv

      TXBTR1pZbFkrbHcxQ09hYnRBZ2h0a001azMwCjRqUC9rVUdseG55cENaWkE5QWxv

      YjBrN3Y5MForNk9SUHNMYUdySy9Zb1UKLS0tIGJBK2dSU05EUE1qd3c0QUdmejlq

      VndRMTdIYkdhcTFhbjliL2xMSFVqWE0KmHYGTS2I+J34mdcX/cW2l0172O1Le2On

      uGDrY/LTxRQFW+u2W91mxN84DYY3EaNV9HWxvGF4PDtITVsaBKzAnA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:51Z'
  mac: ENC[AES256_GCM,data:mi6wBhkKQ9B5L6xkBoeuxgtgq3t1tPWcD6NKbJED4vAx7nT1agaL98ALTeFt+8xm71BbmCEMLjpsIg39aeLwbq/q6hWh0WE6X3jvpSrb27Qpz5DWV5fmm/NUZpQ9PvhVP8DC2MOvJosWzBzuqsS2RUXmGAdQMKejM/Ati+NYqLY=,iv:hzb3Am1+FFkgiKEGrPQ8Nur4QWOgWNq2QF5dbCKi1+U=,tag:IkAhakC+FTGo4j5c9SALkA==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: hubble-ui-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:sL5+O6mfFjinwqc9IJ3tHJCmSOTyruADJ10W6F4R0Jtsm5Ic37yoQgo6xmemLCvxWxPH0Z5mgsPsdzLO4lOjcEP3A1ikBZOt,iv:FaTHvqJBlqFBCFm80xEZOtujsU69k4aWUozS5dVOnQk=,tag:vSS75F+rVunfD0D4HSseJg==,type:str]
    type: Opaque
