apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hubble-ui-oidc-client-secret
    namespace: kube-system
    annotations:
        secrets.json64.dev/plaintext-sha256: 147f5b9639d74d2d3824b9e727e3b46f421abb864bbcf2d3bdbe526287941172
spec:
    secretTemplates:
        - name: hubble-ui-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:g88DkqiQ9jUoH5Uew2DbWPXlNBXEOnzlaboiPBPCLqfyCoYsFEoNhf7KBZ7VoqHfURwWGf3ms2RINBlvOJ4Dqc9bFwqVQesm,iv:kmLEP7ITgfaOuIoM71ZwLag++y4O+c0kVLbpE9ykNU0=,tag:qNMYJMC4fLtl9rxNS8uhng==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheUxBNFp3WG9CdFE0M2RE
            WU5IZWgzNEc3TDNoZ0h3QmRLcE8vRk1HVHhFCklNRWhCQzRXdjJubjVQQkFXV1BG
            S1NVMm02a2RFWEo1VDg3dVUxWWpjQXMKLS0tIDFadUhDK0hIU3ZmeUFzbzZDMkJl
            MmVMcEQxSlhZMUNMNzNuQllaNFVzQ2cKSizYXNsBiQMVsokcvqPIw8dSosXIx3hF
            xRvf8s5fKHv8Q2sfO2HQ8wxkRZcceIjFyXWltu83u2mnRy0e4pUfvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:45:20Z"
    mac: ENC[AES256_GCM,data:Oa1fVwlKgyAp0O++piyUM6dShK6mUcnoDSPOIJddzFRwPAJ+415/6huZzGETN5w+7+J1xpJdVAED93KRF4wtQGx5RZBPrzJFzRAZzMbOVFSIlJJJ16oA4v+KzoBi6OBxXnFjZx8l1sAcwHtI8W8rzr7+XGPVGuzIHSfBEVlT8tc=,iv:eYaf5w4MlBxfW0nxDNSiW7QcDQQ3i/6IGSJcJu7xzQw=,tag:KXSu/Cs8FK1t4AwtFNquMg==,type:str]
    version: 3.13.1
