apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: lidarr-oidc
  namespace: media
spec:
  oidc:
    clientID: lidarr
    clientSecret:
      name: lidarr-oidc-client-secret
    forwardAccessToken: true
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/lidarr
    scopes:
      - email
      - openid
      - profile
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: lidarr
