apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lidarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 5ba0e0f71261a7b821daf700e372ba9c7327d896b8deb5f06c8257f522ddbf55
spec:
    secretTemplates:
        - name: lidarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:gH3poTCtI3Gs+5Nnz65+htpCBtCAlA5Ws7Ly95f6xHgz92IdBHVMx9brOLHXzetvfuRzbbiGx042lGZhwg9Qd/C2GSU75d39,iv:koTmFXGa22LoN73ceogK8Lk11JhnBbJW1n8sMMEc6M4=,tag:b5cE5lbnxhyv3/XmuMjGdg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eTdPenJPRVZXYVp1cGIy
            Mm1wUmpPa2xLVmoreW12cTgyN291d2xxNmprCnpPazdjRWVCZ2ZXbmg2aVlHNitz
            SU1ka2hVKzAwdjV2bVFMV2l5M1N2TUEKLS0tIFlHNFNsc01JYndjaXVSbWdpZEZD
            RVVHN1c0WlVjUXNLRDBtM0tsZUtUVWsKje6K8w+dgONxvmQwqGb+bFuGB3HrBBVE
            nC/o9Vz8+UKac3Pymr0pkpIYl3ehPQktDBXMpGuYKfK+aX8yMIiSVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:55Z"
    mac: ENC[AES256_GCM,data:H3xJ54RDu2C+vChec3fq2PIMJmykRTuYrXiI8LSxvPalTcXrpSk44U9G1mMN9nLNhzwAU6ekVi56GEC/ceQgBrcaNiZiy2kYRzqTeTpotkIG9hDpUCYeORlcHUfeXjG/cl4TGRSEHuniLAowdFbdMp9Adoyaw2ATP1590KWD790=,iv:nOv/Y4Z1pzP49GT5tyMvFlwdkgJfL7XTus4v63DJnVo=,tag:enfZedMSICDd4w1AObNK5A==,type:str]
    version: 3.13.3
