apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lidarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 5ba0e0f71261a7b821daf700e372ba9c7327d896b8deb5f06c8257f522ddbf55
spec:
    secretTemplates:
        - name: lidarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:o8nKK936cmUhZsErcQARUWKsYsYoFon3fbe18HLotcnAuIE5cLmoI+jQ0U544gFxEv4NOfULMXXM4cGIuBWM7OoHYbuCLeJo,iv:QuVYrRfQKbQ2hvGfqBdlec0ndYEaH079B0H4pn1AgkE=,tag:85iVdu3NRBJy8AGQjZJVpQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicVo2dGlNZkNiYmExQjF5
            T29PU2ZGalRlZkR2dEtIbDBsaXlXdUp6dVNZCjNJem1PQmVvbjJRd0l1dDFqUFM3
            TGVMUXAyVW5oMUljWWZXaklhbXV3TjQKLS0tIC9iMG1ySFFaRG53Q2J4VENyRGVI
            dlNWWFd4U2s5OFZBbE1pS21KUm9Wb00KxOP0mDEQm3SsOGh8JOH86L5fcS4H/r1r
            mqz1S0jwENUJflcg6qhkMF0jkD0dWCqIetVtkt0JSjA6AjeKPIb+EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:aRvPfnno7eGE30iuD9nwx13NZBigdbDBbmIjeBVojMzVjnBuSkvWxatR7EbO/AuL6ZfQgyhWruMy5yLQ0/L32ioLp8GfKJbDiIWrNtUN4V3iHKKpgeC8MM7o/2e/ctmPkjLUEyqrx8qcqDLjSUbsygrqRpEK8cy97x7oV70L71c=,iv:7bQzBSOz/G2/Y20j8zFsrvvUou5L4eQtByX4KxWax/A=,tag:Nx5yDUgSB6/EBX1TVd9AfQ==,type:str]
    version: 3.13.1
