apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 31f1d784b431e18fdb2d51592527c28adbb28462e8b4e9f8a4df62aeb91a3dd0
  name: json64-dev-secret
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYTJONUI3ai9ZbEdQOGdR

      Ym5aNFYrMk1xTjRUR2NBTXlJZ0ZHTUFPRWtnCnNCNE51Qk1wZ3VxNFQ5clhvc0I1

      MVh0cm02UEdzYzcrSVZ6aW9Dc1FVV00KLS0tIGlwbmZoNDk5SjZwYmNabVRtcm5i

      Rlk4bjV1WWY0VmM3S0hCSHFkbWZ0K0EKvsMdOu5GZF1gkLBEWzJ5rIUy/b7jCg0J

      IzRhYeSLyR7Ha3GCY89dYO8b1g/tASzAI16ChDRzSB4JpIClqS81Jg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-05T19:17:21Z'
  mac: ENC[AES256_GCM,data:eZM6nG9/mpXfRSiC/KYkjQ91O9YAKoom6B98mQUzGkUA1+YnVORN1u6Mhz09KmxaVXix/t79t1C55xKryvfXfEc+MZL/s94gFTVI8+jPv355A3Gwblcczup3HhpptGGMWLlVco04vEHMMoYEFE7FRAJ3oRonwJNW0f/mASSbTmk=,iv:NM6ePfVtLzVwYFliWp/IuhxuOcB75/psYMN44PSyB6I=,tag:+n0CZvDZMp/5Ge887Wu1iw==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: json64-dev-secret
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:C5FhNiQ5p9VfClJtAF/F1JoAcwLJLsgXFjVigDN6D9jlTus88nyM4w==,iv:dZJ3rKLqF8S0jXzqGQ0FQO2mMWDzHJ1I9kjpE6RILd0=,tag:0hj+bn6cxYpD6jyLGILC9w==,type:str]
    type: Opaque
