apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-arr-api-keys
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f925250481b76915cba97d29b5809772b5ce169df66bb1a00071c4efc6fe5798
spec:
    secretTemplates:
        - name: media-arr-api-keys
          stringData:
            bazarr: ENC[AES256_GCM,data:9bedSqSuJT7gmsArimHdzr7cV+Wij43QtGqMAzFB8NA=,iv:Bc3Ph4B7tRqNR1YYAQoJpKaBdRSnQf0zSV+/tebXoVI=,tag:mNdiMRge5m5BqUt4wNFYMw==,type:str]
            lidarr: ENC[AES256_GCM,data:CF9qN5FHWzw96jG8y0D17FT84iVtXlyjiKdTjA/l+iE=,iv:g6BFN5Xlv0LfZlMuATsfstAj1kqlBZOHLwdkXV7TDEU=,tag:P1H7695wp6q2HmkfK8L9Ig==,type:str]
            prowlarr: ENC[AES256_GCM,data:SOnG7baU0JwCc7GM8qh3OznSlR0m5usaKHSrevMyi94=,iv:7/vk8e2Ok3xvxVhv+RNSiTNJjZ0DvdbrCqWt7Xzt3mk=,tag:ByjdfvoMj170S72LxNLO5w==,type:str]
            radarr: ENC[AES256_GCM,data:w7V6B/mGaKB2mG91OghIt7AJC8wPwnaWPK9cmjaxtwY=,iv:fmBr2SQk9ifvWvSMC0Edq+gLSJnGpx6AFzBP718bPCY=,tag:HvLpnhQDPxZDcMzjjQKnUw==,type:str]
            sabnzbd: ENC[AES256_GCM,data:lM57moUDKYdk6A0Ol6xTjBJmK8eQLSpvxNW7Mo+iTgU=,iv:t2pOI/5UOOxjnY/ZpVIbjax3NwXUnDXNCU+H61hhC10=,tag:19b72T0zecZ7zZogdjGUXw==,type:str]
            sonarr: ENC[AES256_GCM,data:WePrNtoUyQwqDvjoH8K7tHajDT/VuOUVw6FA9YgX5HA=,iv:t2QCczyycbm8eJrmr37PJN5DV3ka+5b0KASR9eWE4C8=,tag:FiF1GjZ4mMKIbuSC7A4tNg==,type:str]
            whisparr: ENC[AES256_GCM,data:h30KwFbVULlNewIwudT/X6G2o5A3V3pL0kRCJiCNhpM=,iv:ki1LSMXeIkzs5YUfSxzZVbE11em+eQB/RuyDclXSSk8=,tag:LUlTi3oyfCNSh8ryPJDGkg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMUlydkdBUWcrRTc0L2o4
            TTczalRZQW9xYW9QcC9DdFo1Nm90cGVNa2tRCjNvSXQzN0wzUkZJa3ZZL0V2SXdI
            cURLM0dORHQva1d0bDhjMXlmM1lRU0EKLS0tIElKWmc0YStjb3JUaXNCQmMyTDc0
            bk5ucDI1ZWdNb3lHWWZicENMTlhnb28KrLVi34sR1hBvALq/mm6nu8X+uwcvHhsp
            bYaJqqIKx+BgMSGhwoqjtapdYvkkRAjxfv1D8NgWzkLJLj9ds+K48w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:57Z"
    mac: ENC[AES256_GCM,data:BVwUROSdNlzRa9OhrmIv6LgKI6MUpKqliFUq0YcqdbKudh4+NadzUnBfNJg88U+48Lm+Z3kDplTKvAmdSJ0Na9ftLM5rdernujASFc3PLus6y9c32J2YfCV1eiXnv8zR/Bl5qqLDz6FRlMF+0nuyQelegCr9i55NTVPA2JqIPdI=,iv:rG6WxqQ4nkqMFNCeEMQVHYUSssIeQKdNMD3ElyPmpRk=,tag:DkGdfWv5giB6AANYscE+3g==,type:str]
    version: 3.13.3
