apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-arr-api-keys
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f925250481b76915cba97d29b5809772b5ce169df66bb1a00071c4efc6fe5798
spec:
    secretTemplates:
        - name: media-arr-api-keys
          stringData:
            bazarr: ENC[AES256_GCM,data:s0rKtYj7bC3PsenlbrdV187V1pqgyzdQI5VofPJXgKI=,iv:1hcjZobCFpwT1Tec6sp2qMEYa7WTdOFguRTWMps7D9Q=,tag:KHb7v4NzCwcD7pWf/P86ew==,type:str]
            lidarr: ENC[AES256_GCM,data:ts77IzN+mpISBDO9IXZPB6Ua4l6+sVKLSfMS9jDo8lY=,iv:WzSnTwJyID42YZZ+hpHcxTZg16L24nmAYrlqiuuFCxE=,tag:StDWz4wkEiIReR2QoYk3CQ==,type:str]
            prowlarr: ENC[AES256_GCM,data:vhKsMdHRjtMl2jj+89X9kmJAmmzxNH6O14Pzo79XP3g=,iv:29mw5oqHmw4Z4+VVdTuDOliwiQkSPD/EZFMcVnfPeo4=,tag:nnC12ZHh1LqZwV6P2oNP/Q==,type:str]
            radarr: ENC[AES256_GCM,data:4TM965ldfiX6j9dhRBIgHeBXqXCw4f3tDqRKLGDqkJE=,iv:e46A+ilMaB3pnwhUaUBYRODqwxwVMKEtrU0UywrJZH4=,tag:f8YgpOG8x2ajwRhlcwoSaA==,type:str]
            sabnzbd: ENC[AES256_GCM,data:/P7oKsN3nGQrfiwvZIkheJICdNyZqEbsNiQEjVZUmbs=,iv:Dj5PJxzyOrD5lCvoMd+rKmxVDBGMvelg3MgTpgeifvQ=,tag:ECgAUlx7ixI5S3p17mjIgA==,type:str]
            sonarr: ENC[AES256_GCM,data:xY/k3WYuUVIMuFtwEdP8UVRoZ+5WONnVCDW9gBEM3Y8=,iv:6M9PCzKbNchDWcsrnw+QA4hhzyIV22FBIpXxL/BmTGc=,tag:ht3+IJX/DR1S0mQEMxOHmA==,type:str]
            whisparr: ENC[AES256_GCM,data:zdqBgCKUzoH0puIpczUarLmhv+hQkNt/iJncDx5WUso=,iv:X8K545Sy6HfehdXnSyNUhW3xRvrohAtIzN4ONXiQ2KQ=,tag:4rewNLJyiiqE3uM6vhSWLA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY25DeWx3cXBYbFoxRGNX
            SWlCMUV4Ti9wenB1SWxQL2gwQUtQZ3I5cXpjCmdtWDRDSW04a3pBMkxzT1ZXK2pS
            SGVwUEliNklLQUxIbXBrS1kyVThYZXcKLS0tIHZIY3RIQWpVcXdFWFhFOVZTUWs1
            MFpLQnl1dmgzWVRaSHNJcXUyUUYrd2sKoSV+hoMYNRarunnJVJuhMhLvH58bFNIR
            vylj7A3tkR4No10tJpFcW0vO7fzsg5gR+nwcO4tgx3LupHIRV9IrxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:46Z"
    mac: ENC[AES256_GCM,data:OQ7dI+RRNs+BAvICY4ApFhsRquVGsRJTRCHcwjjCetQnnHSwr7L1zsCcuc42Hoa7dXWd2ciB8o0m6BNNV6LVc/iuuwiQdcSIurlV+PVigbFE568pi1quqdzF2hukkSkxtlK9204/XBU3xI/gc3ObyC2pVvhciV1czvAfZuXDrD8=,iv:2IoPKrnc+EHdrWP6RHDuLf3YAY3PiMNy26WeCVRH0PM=,tag:Ipe8uz/KL/urPuJAwxGwcg==,type:str]
    version: 3.13.1
