apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-submission-ingress-smtp-relay
  namespace: mail
spec:
  description: Allow private-network clients to submit mail to the relay.
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: smtp-relay
  ingress:
    - fromCIDR:
        - 10.0.0.0/8
      toPorts:
        - ports:
            - port: "587"
              protocol: TCP
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "587"
              protocol: TCP
