apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 10.11.0.30
  labels:
    app.kubernetes.io/instance: smtp-relay
    app.kubernetes.io/name: smtp-relay
    app.kubernetes.io/service: smtp-relay
  name: smtp-relay
  namespace: mail
spec:
  externalTrafficPolicy: Local
  ports:
    - name: submission
      port: 587
      protocol: TCP
      targetPort: 587
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: smtp-relay
    app.kubernetes.io/name: smtp-relay
  type: LoadBalancer
