apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: smtp-relay-upstream
    namespace: mail
    annotations:
        secrets.json64.dev/plaintext-sha256: 2e3858799c7f0c49c165c9f390b19036fc9f6fa99216fb66ef514f8a3b9d6a6f
spec:
    secretTemplates:
        - name: smtp-relay-upstream
          stringData:
            password: ENC[AES256_GCM,data:hW6zcNiRXkHQ0kcFWirexw==,iv:66Gj8OM708OnRrF1MJ+xU6YQRwBGEE5bm7sU4AZJaRw=,tag:vD3WVzvZarUVETaY77Uifg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGRFYnZua2lXUCtMYTNJ
            OWpoSlpvU29pclM0MzJEZmlaMklPV3g5b1M4Cm1MUkZIZXpaUE4rQjdrMlh6dzB6
            MFhVNjI1WDlLVndEK05HcWQ0WWJrNzAKLS0tIDVDMDN1L1FYRHkyT3FldlJXdUx5
            MnUxSjRHamNvd0o1aHZaUitMd1FtUUkKd0XfR86SmAyEUkLyNKMzVGDkLBhywuTW
            VDlriR82it8Khq+KyHWVfiKFG1fivPLMGOIrByCnLPkoDcHQadBVVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T19:35:27Z"
    mac: ENC[AES256_GCM,data:/1CySW/zqDSRQy9JLbgsSt7DFkxTv+Bnt76jZS2nggoAeagPsntxI1Dnkfa3l8alOVazJntvd+a11zXPmVdrjyYWbbem9eYBeGsJbo5X0cf9TppqdpuxKjbx8uUmbOhVsOgiFHE2a2MkkHcUqSAMfxoMO9yV5rP5DJksaZscch8=,iv:bhhKWCoS39xIKu6Nw3sGvj2H/LFF7jSjE1Cxwe2NUwE=,tag:JK1Pjn4BYK+xD+ZEGZIjKg==,type:str]
    version: 3.13.3
