apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-garage-ui-admin-egress
  namespace: garage
spec:
  description: garage-ui to the Garage admin API (3903).
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: garage
      toPorts:
        - ports:
            - port: "3903"
              protocol: TCP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: garage-ui
