apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-garage-web-ingress
  namespace: garage
spec:
  description: Garage web (3902) ingress from gateways (static sites).
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: garage
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: gateways
      toPorts:
        - ports:
            - port: "3902"
              protocol: TCP
