apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: opentofu-state
  namespace: garage
spec:
  bucketPermissions:
    - bucketRef:
        name: opentofu-state
      owner: true
      read: true
      write: true
  clusterRef:
    name: garage
  secretTemplate:
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: burrito
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: burrito
    name: opentofu-state-s3
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
