apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: garage-ui-oidc
  namespace: garage
spec:
  oidc:
    clientID: garage-ui
    clientSecret:
      name: garage-ui-oidc-client-secret
    forwardAccessToken: true
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/garage-ui
    scopes:
      - email
      - openid
      - profile
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: garage-ui
