apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-ui-oidc-client-secret
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 2149d109041492b752a7ee3d3a1b6fb1b55b92625fd8408e5d3f58dac8c7c579
spec:
    secretTemplates:
        - name: garage-ui-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:ex5pu+ghFxH1xfUn8dDATPqLY4fLUoAqcqY/ArtMdNO3969Y846zmqREo4+fIR/ihYdFy1L0uY5kc3C474DDTAclaa7zQVcp,iv:b1yYd2h5oAL2xN9YCPoX8p4Xrjt9/cH4w8H0vW3vIEc=,tag:kVUtRV1w5xI8UIgA5QGwZA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL1ZSSWNDbjFyTldZeDNB
            R3EramVvN3A0dVRZODB4MklzODU4eTVvSVFBCkRzQXZLTUY1dy93M3BhOWFuQk5X
            cm9KNFJSTWhkZDRydDhQa01yekR2K3cKLS0tIDdaZ0VyeWx2aElXaW1XaEtMRlJY
            d1Q0MmNnc3VIVUVhTk1UTjBQZGwrcHMKIE5U1ukDFDqN4EeauS1JVU32OLdxN4J+
            QrA+j0K2bIRViVYBMUGXqavgbH3pcsh5qdun0j21KPfqUdH0Hleq+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T21:07:31Z"
    mac: ENC[AES256_GCM,data:pAr7fiRvsRUSwwITL3v+g5++GiYKq7SpKrcLTyofHhMUOQvMD3YlEm42Ra8aeyeYMfkMEtKpr7qorBNeAfRm0dNYDknu7uBQAksy7uxBLe7osJBY850Q89s5Q8D2/VNBmYUzs+aQeJ6Zk19RMf7lRJUEEptIwQqUXZfKZSW1MxQ=,iv:K18v4nXP5Ml19W81LEGh18VNINk2xwFgHDRsKjPCVGI=,tag:/K1Tb/34W3TURiZRTQzzLg==,type:str]
    version: 3.13.1
