apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-rpc-secret
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 9caac86c04b651b75b98ab5935a8658808231a2dbb345f6adb92b7b525c4efea
spec:
    secretTemplates:
        - name: garage-rpc-secret
          stringData:
            rpc-secret: ENC[AES256_GCM,data:SoRtrtqhtwa06Z0OB8M8tvpydD7/uGFfYJjVVUorZEfQ0axOD41PjpR5UHzU6Hf0SIckATbD5T+4cCgeU+gL0A==,iv:LD8IWNF9yi8UnYWZgxcNgsYOIV9dWV/+XoLJJydAeSA=,tag:L5XkRxr4DyGhFow2nhF1oA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZVhLOTR1T1VMRUZacllM
            dGRFcWgyY2E4RUtDUHd3UFRIVTNJR1lDQUZjCm5LR0I1UENNbURjZmxtY0kralZl
            bHBHT0Q3ekFoRzluaWZBUTlhd2k5aGsKLS0tIE1rVmgvRXY4ZElOZlM1VTV2KytS
            Yk4ySFgzMWVDM0g4TUpZK1pMYWtUQjgKrV3GXvJcpFNq9YZHvkTiKdG+ujvxHBvn
            l6p1mfyZ9dRLwxHgfXr3POyEaP38PCaiSdAUcvzUHN2eqPfLaXM66Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:54Z"
    mac: ENC[AES256_GCM,data:FpKl6bfttUYVsfpRRRdLsAAsKv8ez9tlS6XQ4pQsMoi8Y8DyRtQO4Ws0GauPGK5nBmrSWlTlIplLe/V6yhFVpuMmRqf5uNNuOxw/G7xk8wdv1e7zDBIFbhCTt34Iali5/AoO37ZTZD+mpao1ssiR83srpBDvcNcBiJqX0pUj9cE=,iv:qyrZki5ZLHnZbABNQCIpNYownFz7vCb0cB8llNLFC6U=,tag:tP/prlOSQRJhKJ4pTJRZ7Q==,type:str]
    version: 3.13.3
