apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: garage-ui
        app.kubernetes.io/name: garage-ui
    name: garage-ui-jwt-key
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: c27b0cf671aea1746f1bd1cbcbe477545ea3d074f14ecfcdf0646087c6b40e0a
spec:
    secretTemplates:
        - annotations:
            helm.sh/resource-policy: keep
          data:
            jwt-key.pem: ENC[AES256_GCM,data:Xlifv9KUp4nnCFouhnoOc4QBeTRTmfbdGTceqbcaM1/8zXrbVifIHnHrMZheZn6QS6ZhXnsSYoptf3g1yCRjhHG2OUJCliv7kAcOywvhL++w+jjEdP15xmL4S6ji3zbMW5qeKNgMmqOLnJ/8AZpb36LN9PmyYqT+JZH4xAT6wF9QI7QQ1wF1jndSdyB9kZDp9Qisv7eMhVwPgKz0WSR2lQ==,iv:uJA0xnZ1+qU0P4dd4B5x2K8f0h7hT41vaHK6DxsWxqs=,tag:V42fZ7c8J/+c49vEXCs9og==,type:str]
          name: garage-ui-jwt-key
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMXAzNEd1eW80MzhNTHhS
            WmRGUmp1bWZBL2oyVmpRM3UzUmdRZEcyekRnCkJLMGxqd1ZURWt1Mi9CTU9xbEVi
            ekkzRzRuNU01enBMM2g5MlpiNk5EckUKLS0tIGRZbXhjMEgwQ1k4ZzlNYmNQYlFU
            QUtpT1JodzAycXdySXhOeHR2U3B1bnMKiBfuxAsJ7/8nZGDEIxEi6CqfBfSkhun7
            ib/V7dCXeALynFsQs0VLvg+Un0Iczdj1wvyMJRtL11odbIAdsZTamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T21:58:31Z"
    mac: ENC[AES256_GCM,data:5e9FcxShZog4z0UTFQiumMqmIVJyNW2qejZjgrOckEl/ZGilIQaPKvXPGz0IGvduZ9WPS2nPdM8Z86P6MQiVDi4gJEm4Kvt4I7YgHfoF8cAqZxKJqO7z9lh5KmdP9KFgfZdNKf9ZsUbZgJVUPdx59SYpgYTmH5/UrN1Vo5EOeGk=,iv:0kUMzh/RUtqoee7CTsfDwPqnylNAas4paMQCeJpeSQg=,tag:XWpmK9tj+S/ZSHcTAbA4Tg==,type:str]
    version: 3.13.3
