apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: garage-ui
        app.kubernetes.io/name: garage-ui
    name: garage-ui-jwt-key
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 4c64ce7923e77507ba12881dc8232f4f2f6d35bf0dd00c448d2549826763dd73
spec:
    secretTemplates:
        - annotations:
            helm.sh/resource-policy: keep
          data:
            jwt-key.pem: ENC[AES256_GCM,data:wKbaK9krgqfwC7MXfZpjVhL9XuE0PfyeXw6H3RdBacWEZnDjUNTIbDqnrFDZKRzwY38KTGyRGUiCVUxdkEaC7e7uw3gIc3aIQwyfhcReR04opOvHhz3UYoe/DMHFDTefpdcxCrEX5hlEgE0D5PbwDhli7XSi4ls1Ua09u1+CHYEZYD/m7XXcpNBw9H1gJiVlOLTMAhZFxBq06mXFC7eiVA==,iv:17HqcvWdgDODQestblnN4Uc+HaghPtVzSN4JEIDEbWk=,tag:QH0F7jwVTl63I/Or4KrH9Q==,type:str]
          name: garage-ui-jwt-key
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YkRpcHN2TE9xSE9Rcmg2
            MVBSTDhQb2RvaExDQXFnaExROVhEenZ6aWtrClVYMmdKZUY5NFlGM25BQnFUZHhw
            bUN2RFhZT2FjVVkyS0dYRWxpOVhRNkUKLS0tIGkwZUdjOVZwTUpoYWNiTnptUm8v
            a2p4KzhkS0ltdHlaRitKYmNnY1hjc1EKhOOpxw3iLq79dYHe8+1u8UMk82AV+Rhi
            1FwbXcypkB9E2TQXlXfJdnG1yRFFJx6o0wEGTl/aSFKnbpJjqyWxOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T21:07:31Z"
    mac: ENC[AES256_GCM,data:dXS8ReyvpPb19L/Yxsyjb0lUlXZJGrmTQpIZhPdXuJ1ttvqoD8XxpD6TrQUXrBj7IVTGOHFFZRPOf/X2U8YewfTFvDL9WllDuwl/H4K4Dpzfy+tc3lzo1p5HvFJHoWxcE8ggyo/2+YaQDxADlQnmGoXPsZOTWIcbwDcYtSsSh00=,iv:yz1ezpgHbeZyacbSNyJQgNN9JXtmwMcO7hba0rKNNAM=,tag:vfEeglSyhd9iVQ0/oCec8Q==,type:str]
    version: 3.13.1
