apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-admin-token
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 8266d5cc096d30f73ec70e4ec2adc68cd422a8a6c6bcd3700e5c48b3b143cef4
spec:
    secretTemplates:
        - name: garage-admin-token
          stringData:
            admin-token: ENC[AES256_GCM,data:JWkW+o621JAAQoej9/9HKg5YOc1KQPqyhtbLCULTjfefyTdGYPp0kY+KLfwdhNxCnnqvGB7038JoNAA1W/F2Og==,iv:DlQZVvHPF1OsPXDQT+Tunp7SF7FAM8xw4uYU00NvwV4=,tag:YbeVJ5O9obwpQRT3/ha/ew==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVnNoMFJXMWxYcmFRaitn
            QXpwSm9uUFZWdFZUZVZxSFNHc0lmV2tHaWdVCitGOXZVK0lLb0g4TTdUT0ZqaXpC
            K1JZei9mM096M0cyKzF1Qk8rYWhqa00KLS0tIDIybFlJYTlUaDJBeFpJbGxZalFW
            R2pyd1JOcXVVa0F3aU14UzYzMkFFQnMKU+NYte0imTP1VSyQCnvovRyCZqjmkljV
            OdvJHzHYRx9WvhO5RYhIXUWTRGEdsnyX4sdxZIhV1dxrDFDUK68Wow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T21:07:31Z"
    mac: ENC[AES256_GCM,data:LZ05hgktShUQLlOXiLEMIS3qYx722sODYA46nD9Ks1MJemybLSBdnPjRBEdpaNGTQOePVGuFIqnuWcDcyCxANjbWWMpTzS+vRRniDzwJzGsDDOMWfYZr+jt5aE8r0BEbrGMffQR23gDB/UYz20MWotLraWeYfoWASBAyGtOIMJQ=,iv:aFV6y/DUjcw9RPHFm/1m9cD04wt2DEB6veQZCwTQ2rk=,tag:7tcPANsZMOOo8kdyvFOusA==,type:str]
    version: 3.13.1
