apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-admin-token
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 8266d5cc096d30f73ec70e4ec2adc68cd422a8a6c6bcd3700e5c48b3b143cef4
spec:
    secretTemplates:
        - name: garage-admin-token
          stringData:
            admin-token: ENC[AES256_GCM,data:MTGJW7A6cD6QI5yLrc7T2ZbZIcnDOzZ6Y9WQOu975dLRCbDgEtH7ASp3LY710ya/d2ORW2qLjOSsIZ0PA+Z29g==,iv:FYT9kkXbG2hBCEl7h/Ne/vJoFp/97EFlG+zgwqMvSqA=,tag:7wNjJg43crqwwxPAmJ/nmw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L1krQmdJdXpXdGFwVkNM
            a3hrZzVjY011Rm5kT1R2U2VlQ0JTNW1qdXhNCjdXT29Oc1RWNFFvTCtETW1hYVhQ
            cmp0ZEl6L3FSdGJCNHZmT1I0VWZubWMKLS0tIGpWbk1majNxbGhwYlJWNlB2YWdG
            dWZ4SERBTE1lbTRONmtqbkJBL3FHNTQKbL8SV8aw/LqnQ0tKF1pXaPd4q6h0lylY
            +rdNXJswuyer41dRkBWdL3uPibgbwRTBWW1X9XwCc7k4vyR2nUeeSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:54Z"
    mac: ENC[AES256_GCM,data:JQJKTSsfjnwvNdMW4MiEcrH1a7seNBXnaXMSgoJJ6OxzPinPo+bjNjdtNowVq6sIKmp+E4vn8k7w6WXldngVcVxK0TQbt64p3QluAbYOVjJntUyKgGca8utSToHhOQzyQeZAWdlG0gEB2SxnpvA8TGKpJVSbZoTQfjttSzUOzvA=,iv:tKFln0aAgUbnlzYrzfMmfTxTekRTJ/6ckPMvR8vsjN0=,tag:CZO8jvS79cS9xIKisr+yIQ==,type:str]
    version: 3.13.3
