apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-ui-oidc-client-secret
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 2149d109041492b752a7ee3d3a1b6fb1b55b92625fd8408e5d3f58dac8c7c579
spec:
    secretTemplates:
        - name: garage-ui-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:bvbjas/UG1gCRZZuSM7O6EsvCVOQnLOuFNECn/Cs5hJogc0by2OWmoMlurtfSNV3ioIGoyBA+ZNF6pzRV7J+20CaNf+J3Q5m,iv:f3TwLxmEeKRu8s+EQ7+Tqi00jFz0L8trCPKHfv26cK0=,tag:H7y6t/4Mri5SGvvY4ThYOw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSjE5MnJiRllLc2FITHI1
            RG9NTHpkeUcra0R4MlA0ZndCWXhvUXBrVGh3CnpPRjVURXc1R2puVE9pcW1WTmcz
            MUEwRHN3eUVIaUxVYVdGNnIwR0s3WTQKLS0tIHZ0d3V5aVJGSlZTQk55dFlLOHVv
            V1Y4VE8vTjV2T0Z4QmJ4OFh0T3lmcVEKE6jOZAO+4OVRvMEccugDsMDQqdjZtuRk
            3TvjIJiNSsr9knN4Ieyx78iXely3m4f9RKB01jUdeaTpQWQWp3Khuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:54Z"
    mac: ENC[AES256_GCM,data:ZHF22l3q4Y7+CFCXlByzjt8JEzwpK6/tcX6ZJ9E8jqpi6d1FSQublB504CqzEGyCFjw8YhzMX1m6QokqEE5rpp3zFLyvwtROKgezF0jwH+dOBP9+JsDKyHLI7i0nRlV8xXqvGCMTXOkqL/RQAgB3doC+eDHVg+0YfvlfZHKubD0=,iv:qJESTVP0Rs3AlzZyjiRwlnnSGwlmsfy7GHTIQwyMmQA=,tag:BC3xSwgQhTUCtVZtDdt7LQ==,type:str]
    version: 3.13.3
