apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-rpc-secret
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: 9caac86c04b651b75b98ab5935a8658808231a2dbb345f6adb92b7b525c4efea
spec:
    secretTemplates:
        - name: garage-rpc-secret
          stringData:
            rpc-secret: ENC[AES256_GCM,data:+g5vPqigdoQ5LNszDFjNVG8YfJhDcbEhPR6zgcpF9eZJDwUWBmI9zAmXf6CqNvgamgxPmCtwqEtW41YpM2iIaw==,iv:XInGy0l2pii2AMrLBF/gGHLbyF2t8lTPnvGNUdCT/u8=,tag:O1p5WSoF2bhWWGXQ90BrFQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDZiQmtvelhsekZsRGtD
            T0kvWG5XOWF2TXl0UFB6NnBSUHNVUUpGY1dRCjBmbVhYcWpmMFRrbkJPYW5VcXR4
            YlAxZXIzUkhmSytKRUIyNDRCbHovMjgKLS0tIFhWYUlNMnRoV1V4VXkwTjNIOEUz
            RFEzOCtaOG5KdzRXc0NTQ3RJZFdZQkUKT6pVFeIyMWLQFrXwahV5zhyN2qGp/KAn
            cqIoKwfIe1C11u/Zq6il6j2u+/tgYOOEqx257zBeIpeAUGLk3Iu7QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T21:07:31Z"
    mac: ENC[AES256_GCM,data:BT60dyr7GZVPELYrQMNbkROOqqv9zsquPNe2PJaXJJgC1wQv0nnbR055jcmMnmVFiBOni91/hBCRp7/GFxo6gYCTyXQrsAhsz/8Qek9X0g3fAPV4g1YSiH3BjVTvMiH1vmeP+/3T4kC0+KTT/LDbYAZmhrh6uTuZmgbRYvxXg4g=,iv:io94My52K9c5O/gU0Q+J/GzdLhrf1xTdtOuuKGAFUvY=,tag:TgYWAxvp0D5nTAWq86bLXA==,type:str]
    version: 3.13.1
