apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: garage-ui
        app.kubernetes.io/name: garage-ui
    name: garage-ui-jwt-key
    namespace: garage
    annotations:
        secrets.json64.dev/plaintext-sha256: f712624eaf3d2323dae3a669066e2912ad557d2291f76e2fbad98b4629a98369
spec:
    secretTemplates:
        - annotations:
            helm.sh/resource-policy: keep
          data:
            jwt-key.pem: ENC[AES256_GCM,data:8KpjC7wxH75qdli4vk3zYTreF7+eIc3CyF6OQ0mBnph2Q/Z18T06uF56SAzI9fqxtf0UGdjjOdIJOGz6wyxduok0ChSoW0OUiaIdUF+5L69BstOL1HBvwXJzao0q3WMgLzAHJKX/u5hDY5mNuLZshDsuNPSMJyBkzEr+drMz1ht8EjID9MSCZ7GNyZh0vQyHSojRY2OiErIgMWG6rJZwzg==,iv:GedqjLa31hVCQLPA20gxAybT06Uj+kUcMtvofV5aYFU=,tag:ztXEKB5LXXRa03GgI4IzYA==,type:str]
          name: garage-ui-jwt-key
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdkZSdnRuYTlQZ2lwNXVl
            bG5ucW9wUGY2MXRZWGE4bDdFT0tvRmJzNjM4ClVwaFo4MzNWZHYyL2ExTmVVTzFx
            NSs5MVBLT1l4eHFXWHRsc3p2eE82aEkKLS0tIDFEdUF3ejAzZHRrSElOeEIyblJR
            TVh0VUxSQXcySVdZcjhSVTNNNVA3Wm8KlSgU5tk9aiLSgZfI/T0LjhLQu2P9CrA9
            xefbi6OK1HkbDxyuzUfqrJXR4wCyk4BEcp8V50GDji8TQpq0n1nZlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:26:54Z"
    mac: ENC[AES256_GCM,data:T3jIc+/akWqn4835OqnabpKagmJnfPQ2Mun4DNEn6e4G6nebvOc9jssXEVyqSsbrPEWjSUh/gP6e901LOnuwA5Boz6IGiC9nYIjnSi2BF4qnOwfKuHnmRnrmPWA3NJn+tf3UOyeTDNDMzHBNraksS8QMjM0S3/iFEibbTaiU/u0=,iv:EBi4gMolcgCrIs7WzUNkrGDq7m7AIxw+7gdumPZpEWA=,tag:2uaPXb5Q05YrQuk3qGpTCw==,type:str]
    version: 3.13.3
