apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qbittorrent
  namespace: media
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
