apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: qbittorrent-oidc
  namespace: media
spec:
  oidc:
    clientID: qbittorrent
    clientSecret:
      name: qbittorrent-oidc-client-secret
    forwardAccessToken: false
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/qbittorrent
    scopes:
      - email
      - openid
      - profile
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: qbittorrent
