apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: a2bebefa460bc679d0d139a459b197928494558942db935471c99045d52334a4
spec:
    secretTemplates:
        - name: qbittorrent-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:1JrPWYEywlp+yW6fgy5VkKv+qzbtIFw7NDVRrsghyhgaDICOec2Wd+8QeVqJ9sMoGKByhVvI4tZm/ZoR7WmyJnOfFlpN9l8J,iv:8Hc4tRSbT5XnVx4HF79K3/5Zpt6WwexGDyvTEBYx85g=,tag:azs1jjX0tDu+GoGh5UScdA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkY1bGdXM0lnUUlkS3VN
            U3B2NEJsQ2JCQ0FxVzhjd2svTGJtOVpnZ1JNCnBqbi9LMkU1SzZ5NGgyaHBWZy9K
            WnZLNTA5ODJPaXY0UitPTXUyanhqU0EKLS0tIHZKeDRJRFVwSHdTNjd0cFJLUzYy
            K0xQcGs1OUNRSFV4aVhDV0lKb2lUS3cKmXHS3T61oFfRBveGBiV5/AP5ZrFU6kDt
            8j0cwmaXfjyg5qq4O2Sw1rriKAZccXlupwTyA1iuYsof8aVqQwpxUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:47Z"
    mac: ENC[AES256_GCM,data:clXe48AXrbd21LTLge589cjzj+IY48pKoXJIqWVWMTMP39uGN8rTL6DTy8A6Vy2C4gk5/Y5UqkYRg/1VbaELWU6/7GCFr8mdzsg4OhdsaZFzUY8A3uvFp4A7oCB0F2jERC8RCJTek8JTOLaGe/uppGdjFEFepdBY/CE33zp3Kng=,iv:a1xUTukCo4BUlPpmHT75LPchy9FvKiJOF89a1ygKCLQ=,tag:1ys5db7hkwE9HpDb2Hb9Vg==,type:str]
    version: 3.13.1
