apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-vpn
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f90dc4fff75958839b6b27427979f49d1befbed5703a14b91e1bf3c23ca1cf75
spec:
    secretTemplates:
        - name: media-vpn
          stringData:
            addresses: ENC[AES256_GCM,data:ZbHRJhz1YioSybA=,iv:iBANzyqayc5y6lanXEzB4FM8suFb6UERpnSsrtiv8U0=,tag:vllriJemUhmpsBAw3DZlsw==,type:str]
            endpoint-ip: ENC[AES256_GCM,data:dIw6iBUjZr/+rOyhCkw=,iv:ua0zz8j06EOIWiOwjQb5Z9Oxit7m3jI7HR6INyz9gjM=,tag:rHmH1+QFVjhR2lNFDSiZNA==,type:str]
            endpoint-port: ENC[AES256_GCM,data:ysyyQS0=,iv:glnt2nTN8Y2pfOBnkeirgl7cJEcq78TjiNxiyi9eR0Y=,tag:rG+BdAHluZ5h2hJL2W8g5g==,type:str]
            peer-public-key: ENC[AES256_GCM,data:tuwvUD8HLkKtd2S6zvpq93jZnH3mSgd+xDmE/Ox+7Q0YEzGR4q1eepmwvZ8=,iv:HPo3VJzop9z3j+taMS5+v2vfNfUhhqIoiHKQQ4kQBNw=,tag:xi7i/FLsG2fPy6uG8o6HAA==,type:str]
            private-key: ENC[AES256_GCM,data:0fqECashgMuu8tn/PMOJUEGHjiD/z0YZK/xHibyBm1uP1JrXFZ77ILor2Oc=,iv:JWVQbX61IX3v+zNDpd6QjBj3YnERbLc9QqgS6UcdK78=,tag:enEHUbCGMHm5Dtk8XJjNtg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZGtUc2I0V3MvVFRXZDFC
            YmowdDJWTFZTSDdrMThDdmFMak9CWjg2SHh3Cld4STF1OG1FczQrVmZ6MU1DMWI1
            UXhTRTF6SEd1SDFLTUtuNVUybjd4QkEKLS0tIFZkd25pM3V3RFo3MklIdEk4cEZm
            dGYwbS9Rb3pVSDZoNEMwWGtWVitkZUkKn3p9p8FL6a894TPULdJM+kVQTv0zw2xd
            BRWZbVbgQ3wZqfZgbcEHgWOsE5oXx6qdCcptVHqBAqEiktxD6yIH8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:47Z"
    mac: ENC[AES256_GCM,data:84AG+9tlnAz0ovNmDytUdr533vF3tokSJfN8rkxXg7DTrZHL0yenlhRa/DJeAXmQrfGV0Hq/GR5HNlHHzyq8zEnDRwtuk832NRYcI8JZ3+TzPgjTBhsVba09LxB5jWUxBww+3tX4gwaXegmW0x5yKzyP781YJx0vQxvzy8S0XAk=,iv:mUf3xqPe9hsbeuN8fp1jOPHeUjBwx5MEqz5EkXF7710=,tag:Dvs7h3fbT1G1dPzTFlPe7A==,type:str]
    version: 3.13.1
