apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: a2bebefa460bc679d0d139a459b197928494558942db935471c99045d52334a4
spec:
    secretTemplates:
        - name: qbittorrent-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:l0reDPhu6WCSzRfUPvXUHa8JS1OQak8ukn0HvMhzmrW+/Rks3/q38zcJyfVNCRc82fQfi/kq6EDUPaQ0l+qALoECh6eW3VAx,iv:7r9/ga0DHaKnrEI+DQ7ygY7A4vLKBX4cK/qvY/1CQkw=,tag:EG0gMqnv6WSRbmm0E6VTCw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOFFPaWxqMktBVnlmWm1O
            bDU4aU15Qm1XNUlEeDJFTG1VRWp0UW13Y2dJCnYzUTN6Ni8xVEZlUTBVRFdrMEg5
            ZGZuWVcxUUpHbXZlT3craVR6dkxjTlEKLS0tIHhtQ05lSDdQTHpXaUoxZFVGZ3lq
            czJNSU5VZXRta253azJjWHcvcUQ5Tk0KMqSGkcAJ7LSNIf+7jVLXozUgywp10ZmX
            Sz5l8peGBwyxHJ14bvp43MlJnpIPnoQyJu0hgEeqJE38IP2NCAMfJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:58Z"
    mac: ENC[AES256_GCM,data:seMIXVEJZqBGtgDmrEZAbDb1QZeo7O+voCpjmZ+hzrY93jjUh9K5kPedV9LPUS7QqZRnjFv+FZ3Ykc1EkNlormTDsxmspbB4h9NdMzX9FVNyYhB6mpPuNa1+/isszeUCkRLu5xzX97EcXuUt1Qv8Fhx/y5aSA1eoMIheJe+LC/w=,iv:XmDBz+CjXfbFseEALoccLxuIm0hzs5UEkRyvexFfNoA=,tag:onK88uxDIhyy/Md6J6vxPw==,type:str]
    version: 3.13.3
