apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: media-vpn
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: f90dc4fff75958839b6b27427979f49d1befbed5703a14b91e1bf3c23ca1cf75
spec:
    secretTemplates:
        - name: media-vpn
          stringData:
            addresses: ENC[AES256_GCM,data:bDuW3YDuxvMalEY=,iv:64tK7vDSR1B2dODh8tPA517HmNPvooZnZ4sll3Qkpv0=,tag:gRHoVQEmdcOs+a/p+7orbQ==,type:str]
            endpoint-ip: ENC[AES256_GCM,data:U+NNJMPfKJUYpXnL8Fk=,iv:3w+kssaJs/J3iZq/h3pSAsv2ziv8YuVjfLx0g9QH46k=,tag:1KMQMBFrFJmcvitADiTYuQ==,type:str]
            endpoint-port: ENC[AES256_GCM,data:eC5j4BI=,iv:D6V+McshaO0mt1GCrXIB9FgGhw9kfCM2cUOKT1IOUxI=,tag:vdDM7V52acrIDS6eWNs/Cw==,type:str]
            peer-public-key: ENC[AES256_GCM,data:98L/TMmJMcbSPC4RkzX+bhhkcsqxV+XXEP/XGBKarFVJsxA6vWrSJL2+5co=,iv:zsLKqX3d4aBI/inEH7B8hXJkvmf+goKaeCe+MiQ8TXk=,tag:HgDUyvkXH5EtPXJ50BaCEA==,type:str]
            private-key: ENC[AES256_GCM,data:J3h7ZmuKGIlVyw3c51dCkva6Ndd7SP9jhgEy8XGCGq7yRstsXlKFwuxUqk0=,iv:g7s/kqTrOksRkjQIYAk/7bgRfbGi9k/uk+4r8H79snk=,tag:IWcEVgcXZmcFPOcbkukinw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSndoZHNyenpiZ0FoWU9J
            OW5hK1Z3YXZYQlMzMG13OGhMYVROK0xVZUV3CkxRQmRmRkJxNHkvbjkzcmo3YmZV
            bXJyU0VNRU9SZTBZcElwcS81S1daYkkKLS0tIEl2QmdPR1ZVbGZISC91S25INTlX
            dm5lcFZYMlBjVENsWFlXUVJrMStXN0EKfPEbEhsdaBlQ71XbDQmN8753L/zAzojF
            Nq8bv1Hot6ngksVGPLK+mHZBk3ed6d2n4DinokUMNJdyszdCIKmSdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:58Z"
    mac: ENC[AES256_GCM,data:UMyBUqFO40vg59fmy8ETQLZOFy9xRKU4VFGad2aYIatrvF/4sy+A9u1rz4AOYQzIe+p2PFXuhGxc2bClCoRWxaIlRyUDbUYocpTWCJJ9mYjU/DCoJZVFmR+MPnLNfIBbGWGjJlC2MAGlulhLFX8QW8RvAl4tbTpiKh7BVa4eNHA=,iv:1y0ySqR/pGcYbooHRWsgHBSJ+V+iwOJGs4YUIbyLkSE=,tag:+1QGpkjbxoEpu24kBG2Fvg==,type:str]
    version: 3.13.3
