# The environment's public DNS records, as a terranix module (infra/dns/README.md).
#
# One proxied A record to dns.publicIPv4 per apex domain (plus www) and per
# service-domains host, kept to the environment's dns.managedZones. Hostnames in
# dns.unproxied are grey-cloud. Records already in a zone are adopted through
# infra/dns/imports.tf.json (dns-adopt), never duplicated.
{
  den.aspects.dns-records.terranix =
    {
      environment,
      service-domains ? [ ],
      lib,
      ...
    }:
    let
      inherit (environment) dns;

      apexHosts = lib.concatMap (d: [
        d
        "www.${d}"
      ]) (builtins.attrNames (lib.filterAttrs (_: d: d.apex) environment.certificates.domains));
      serviceHosts = map environment.getDomainFor (lib.unique (lib.flatten service-domains));

      # Longest managed zone that is the host or a parent of it.
      zones = lib.sort (a: b: lib.stringLength a > lib.stringLength b) dns.managedZones;
      zoneOf = host: lib.findFirst (z: host == z || lib.hasSuffix ".${z}" host) null zones;

      key = lib.replaceStrings [ "." "*" ] [ "_" "wildcard" ];

      records = lib.listToAttrs (
        map (host: lib.nameValuePair (key host) host) (
          builtins.filter (h: zoneOf h != null) (lib.unique (apexHosts ++ serviceHosts))
        )
      );
    in
    {
      terraform = {
        required_providers.cloudflare = {
          source = "cloudflare/cloudflare";
          version = "5.26.0";
        };
        backend.local.path = "terraform.tfstate";
        encryption = {
          key_provider.pbkdf2.state.passphrase = "\${var.state_passphrase}";
          method.aes_gcm.state.keys = "\${key_provider.pbkdf2.state}";
          state = {
            method = "method.aes_gcm.state"; # a bare reference, not an interpolation
            enforced = true;
          };
          plan = {
            method = "method.aes_gcm.state"; # a bare reference, not an interpolation
            enforced = true;
          };
        };
      };

      variable.state_passphrase = {
        type = "string";
        sensitive = true;
        description = "State and plan encryption passphrase (TF_VAR_state_passphrase)";
      };

      # Token from CLOUDFLARE_API_TOKEN.
      provider.cloudflare = { };

      data.cloudflare_zone = lib.listToAttrs (
        map (z: lib.nameValuePair (key z) { filter.name = z; }) dns.managedZones
      );

      resource.cloudflare_dns_record = lib.mapAttrs (_: host: {
        zone_id = "\${data.cloudflare_zone.${key (zoneOf host)}.id}";
        name = host;
        type = "A";
        content = dns.publicIPv4;
        proxied = !(builtins.elem host dns.unproxied);
        ttl = 1;
      }) records;

      # Read by dns-adopt to match live records to resource addresses.
      _meta.records = lib.mapAttrsToList (k: host: {
        address = "cloudflare_dns_record.${k}";
        name = host;
        type = "A";
        zone = zoneOf host;
      }) records;
    };

  # The OpenTofu state passphrase (TF_VAR_state_passphrase). Generated by
  # `agenix generate` onto the master identities; intermediary, so it is never
  # rekeyed to or decrypted on the host that declares it (uplink, the prod edge).
  den.aspects.dns-state-passphrase.age-secrets =
    { environment, ... }:
    {
      age.secrets.tofu-state-passphrase = {
        rekeyFile = environment.secretPath + "/tofu-state-passphrase.age";
        intermediary = true;
        generator.script = "rfc3986-secret";
      };
    };
}
