# Public DNS records for every managed zone, as a terranix module
# (infra/dns/README.md), instantiated at the edge environment (the one with
# dns.publicIPv4).
#
# The zones are the domains with dns.cloudflare (dns-zones). The records are the
# domains' own (dns-records: web.apex, pages.github, mail.protonmail, ...), plus
# an A record to the serving environment's public address for each served-domains
# name, from every environment; served-domains `public.proxied` sets the cloud.
# Each record lands in the longest zone that contains it. Records already in a
# zone are adopted through infra/dns/imports.tf.json (dns-adopt), never duplicated.
{
  den.aspects.dns-records.terranix =
    {
      environment,
      dns-zones ? [ ],
      dns-records ? [ ],
      served-domains ? [ ],
      lib,
      ...
    }:
    let
      inherit (import ../../den/domains/_lib.nix { inherit lib; }) longestSuffix recordKey;

      # A record routes to the longest managed zone containing it, from any
      # environment; a sub-zone without its own zone is hosted in its parent.
      zones = map (z: z.zone) dns-zones;
      zoneOf = longestSuffix zones;
      edge = environment.dns.publicIPv4;

      declared = map (
        r:
        {
          proxied = false;
          priority = null;
          ttl = 1;
          comment = null;
        }
        // r
        // {
          content = if r.content or null == null then edge else r.content;
        }
      ) dns-records;
      declaredNames = map (r: r.name) declared;

      # A served name gets an A record to its environment's public address,
      # unless the zone declares that name itself (hs, jellyfin: CNAMEs).
      served = lib.concatMap (
        s:
        map (name: {
          inherit name;
          type = "A";
          content = s.public.address;
          inherit (s.public) proxied;
          priority = null;
          ttl = 1;
          comment = null;
        }) (builtins.filter (n: !builtins.elem n declaredNames) s.domains)
      ) (builtins.filter (s: s.public or null != null) served-domains);

      records = lib.listToAttrs (
        map (r: lib.nameValuePair (recordKey r) (r // { zone = zoneOf r.name; })) (
          builtins.filter (r: zoneOf r.name != null) (declared ++ served)
        )
      );

      key = lib.replaceStrings [ "." "*" ] [ "_" "wildcard" ];

      accounts = lib.unique (map (z: z.account) dns-zones);
    in
    assert lib.assertMsg (
      builtins.length accounts == 1
    ) "dns: one Cloudflare account per workspace (got: ${toString accounts})";
    {
      terraform = {
        required_providers.cloudflare = {
          source = "cloudflare/cloudflare";
          version = "5.26.0";
        };
        backend.local.path = "terraform.tfstate";
        encryption = {
          key_provider.pbkdf2.state.passphrase = "\${var.state_passphrase}";
          method.aes_gcm.state.keys = "\${key_provider.pbkdf2.state}";
          state = {
            method = "method.aes_gcm.state"; # a bare reference, not an interpolation
            enforced = true;
          };
          plan = {
            method = "method.aes_gcm.state"; # a bare reference, not an interpolation
            enforced = true;
          };
        };
      };

      variable.state_passphrase = {
        type = "string";
        sensitive = true;
        description = "State and plan encryption passphrase (TF_VAR_state_passphrase)";
      };

      # Token from CLOUDFLARE_API_TOKEN.
      provider.cloudflare = { };

      data.cloudflare_zone = lib.listToAttrs (
        map (z: lib.nameValuePair (key z) { filter.name = z; }) zones
      );

      resource.cloudflare_dns_record = lib.mapAttrs (
        _: r:
        {
          zone_id = "\${data.cloudflare_zone.${key r.zone}.id}";
          inherit (r)
            name
            type
            content
            proxied
            ttl
            ;
        }
        // lib.filterAttrs (_: v: v != null) { inherit (r) priority comment; }
      ) records;

      # Read by the devshell commands: dns-adopt matches live records to
      # resource addresses; the account and environment select the secrets.
      _meta = {
        records = lib.mapAttrsToList (k: r: {
          address = "cloudflare_dns_record.${k}";
          inherit (r)
            name
            type
            content
            zone
            ;
        }) records;
        account = builtins.head accounts;
        environment = environment.name;
      };
    };

  # The OpenTofu state passphrase (TF_VAR_state_passphrase). Generated by
  # `agenix generate` onto the master identities; intermediary, so it is never
  # rekeyed to or decrypted on the host that declares it (uplink, the prod edge).
  den.aspects.dns-state-passphrase.age-secrets =
    { environment, ... }:
    {
      age.secrets.tofu-state-passphrase = {
        rekeyFile = environment.secretPath + "/tofu-state-passphrase.age";
        intermediary = true;
        generator.script = "rfc3986-secret";
      };
    };
}
