apiVersion: v1
data:
  default-resource.yaml: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
  name: longhorn-default-resource
  namespace: longhorn-system
