apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 5e26f4699576154d8d4dcd43fe20f5b08f837a9a27ce6b09f5ea1b4933c1e259
  name: longhorn-oidc-client-secret
  namespace: longhorn-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRjFHa1lvNlRSOTVBSmRi

      cm03ekUrRmVBNzlsek0zZTVmakt2alhxMVZZCmliZjBrTUJpeE9RaS8rOFc1MHky

      N1F0bllYNnBMV2pJK3RtaUhYSE43N0EKLS0tIE1TY0JqN0JGYk9IM3E5a0xtUXht

      SjZaL3F6K2JXZ2Q5dzlOTnFaNmtZOTQKRuyuDcwsMJ4T2aLEdjW4+Ma0bUU0gJkF

      xR1sApkEe898IhuMeNah948s0JxxqeKoKA3zVq8iTIKjzgHUyJMwpw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-05-30T20:30:36Z'
  mac: ENC[AES256_GCM,data:wduDaMMwwT+XikgjBNxbngi09vXKVkYu4K3qycGg27bBjow36QhV/JihOI1MM7l6dyD7uEq81/9yQT1c8/fdN6BhfVLiJoXQQarwDp9HWzlaaIwoBosbYvywNAGMRBRyX9O2/npSIHJ6t0aSGbAQyj9jJ+wXGqcWAHId22QAOwA=,iv:dsFWoBWA+emd1P3DGOIw03Mwp4eOxkR8ulQCZSljT9c=,tag:2PnqPMUt9Qk+lNY/HneY6g==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - name: longhorn-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:wnjDDqv/RcjxJapy8omQaWn4cLsSKrKaNbrxeYf6h89ulOg=,iv:8dmQcS8wX8nF+6dQo8w2uPFPQcoNymkbf9ylfXmig1Q=,tag:/XTzQOsBaBcfdou65j95yQ==,type:str]
    type: Opaque
