apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-oidc-client-secret
    namespace: longhorn-system
    annotations:
        secrets.json64.dev/plaintext-sha256: a63f1d2a10506bd5268b64ed8a5f4604329bbcb9ad2036729f50be8a9fae73da
spec:
    secretTemplates:
        - name: longhorn-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:I/CPcihT+aEYBWAv2zOWaZSIpK9c97GHliKJM1T57kCodjPRgsJMy0KPgxvcrbBNq0/jEcFGlz6cyXxBkwVRo1wb3FTjaQZ7,iv:BNz+w9EyX3cw48KE4fFYXkbNw/1BW2ExMNFE/HwCFfg=,tag:cqQlO89mxKzAwLbBUAgOYw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VDNXQkxmcWw0ZGcrZTc3
            c29abmx5SDVQN1d6aU85SDVPTUJ5UmRxdndNCkQwbHVPSXV0ZGxJNTF6SVM4eEFP
            V29xZjd1RURFYnZQb0NEOWNYK09QNEkKLS0tIEluODFPM0FRTHFSRllJbFQvVFBh
            WVRnN0dMQ05heHNkaXhuN1NjOUZzcG8KZJlJqS2vdA6AV1zOXsB7zxf3oXmliqaV
            0SJTZ7fpE/5flo3BEU0WMJGLI+fINnpywGfqp7yVPT1njW/i0lZ8Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:56Z"
    mac: ENC[AES256_GCM,data:60T27QGo+sv4LFxVrKJTJUx0vlwe1jK0AmuU6Netpeh6Pf03HykU3MbhSFv352qOwMI7HX6oyYatHLhNGWrXlAyxZ2PTXLL3F3APU7E92x5FvNJG4sPK08PyGnXnpPThQ50nt0OArU5LjUhwwtkVLuFqdshfjvErX7X9N4U+FgU=,iv:qJ55KlYG1P06Gc4yOo34q4vFaN3p8h7APkLNP2Ltgk0=,tag:aJmYMYxigGZh/G+/ssPAQw==,type:str]
    version: 3.13.3
