apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 7b957bd5bc1e67f38c7359804683813a84d9e2bc936eeb7f494430ac1942b00a
  name: longhorn-oidc-client-secret
  namespace: longhorn-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WittLy80Nm11c05Ccy96

      RGVMWTJPbW9oOWZhNUgrM2JDQkNvNlJRQ0dFCkFBcU1TcDBhU1l6S0ppQ2VPWi8r

      THNreHRxYjN3NGI5MzJxU2tyd1RKVDgKLS0tIGRLMGN2ME1EeUE3ZWVhQjhEU2ty

      UDJyeFhTVlp2THNOTXYveDRlZjBsUGsKwfPoEBSDhp4N9e8ly4N4dIf+M1q8Ivyc

      SKvqK+JPlgEEFeII4IdASrE+lc/ybEK8VTAPummPyRB47ljMVDKfMA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-03-20T21:31:51Z'
  mac: ENC[AES256_GCM,data:dclxGS31BBbOkCJWTQ7bq7W1lvxx2biYtQrAEr1oqpchIn2g1d6aWkXvmA6ahlQ/apv6oSgbvWdwT1okeSmh/xITso2wVv4V0rCB9As5rUZgd97Cb0lYJZCeWdu0GD2fF7FvdcZUxTJdqqNaZWoMOS/LhZD9SRo5Y0KuqwkUpuc=,iv:Wig2Ghs9vyX/Y7kv5XDWBRDPsLI7o+pE4W4YxlgEnCg=,tag:JkPTqO7pQYS+hpJQ348TvA==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: longhorn-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:wlQLXOaY4CrnjBGIEnC5NGOLYgSeB1ImfkoI49IJDC2AOLdU81Vtd3MUyQjgFPSJumhkjPEtAshnzeVToSxngMsqYS5zTpe0,iv:IgBubfNzcl3hoXuHsC1Jf3P+L/ogh+KFg9dhu2mrH6s=,tag:bc9qOQhhv+bZBYf69c7dQw==,type:str]
    type: Opaque
