apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-metrics-ingress-tdarr
  namespace: media
spec:
  description: Allow Prometheus to scrape tdarr's exporter sidecar (9090).
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tdarr
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            k8s:io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP
