apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/name: tdarr
    recurring-job-group.longhorn.io/media-config: enabled
  name: tdarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
