apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tdarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: ddeae01def98db7ccd83b804b3272ab9f4c573a5e132ec4be214ae777882c692
spec:
    secretTemplates:
        - name: tdarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:S4JOmN8dhs3eXYDO67QxB6lYbvXhNHkmHnUnBCqMmgYKBcE+Aa1xbGT9ga9YO/2zZ4tLx4ea0s5YWYMb9pzEXV4KvzxOAwFL,iv:BiCBXatMCLaWvRXepWZ3S3aeiPSt0ikzjcdi3lywzdk=,tag:bPMJn02/9GUyF4dxjRj9/Q==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3VPRGR1L3pxTlVua1hY
            VnpLUHVvcFA4OHRQZTh1Vy9xM3Fsc3dJV3dnCmJobFF6ZDV5aTFFSjdHNlB4ZkNa
            WE9aenpySHI4bEUya1pGelNXODhaVk0KLS0tIEhzQXVzenkyOVVwNmYyRXhidlJN
            MzhVYjB4SmpubmFoQ2IrTk9UZC9BT3MKPhDt0MRjtf3N1CYvLCmwhyjLuVnyT8we
            Rzn5eVeop0eYUVi/MtOHxtrcshfVSH9wAmTJwH3t7GplAyPs5Y0xdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:33:00Z"
    mac: ENC[AES256_GCM,data:9womvENxPVwoqHPDBZapR2FZIjGaLlHQmaMW2Aj56ls9XFAZoPTUG8EOqEoOMzU3DicOVY7wNrlzNjeSoAACixrWNlkjmb9QiJpSADBCL6THScyZ7CTeWhrCrkpOQU4U54CGM5Jz973ka74ekq75o1XX8Nayz9OWDfi7diJ1mdc=,iv:/eLKw7GaLRTzfOXD2NB0Wcnjei/LqdjOssSbAwuAghM=,tag:TFR7zPMY+SHbYSqK5kDb7g==,type:str]
    version: 3.13.3
