apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tdarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: ddeae01def98db7ccd83b804b3272ab9f4c573a5e132ec4be214ae777882c692
spec:
    secretTemplates:
        - name: tdarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:WT6qW1zGNwTlU+qBW3Cr/eNjjmmERxv1ugtkw9WuNT1cS4A2FCoUMe8L01cn4K5Pz0VEjs0keHU0iFFJsiafgwQ8Ms02/u9+,iv:EF50w0IzkJ0OiaOw8pHaypSjpVq3dVNyw3wbEghJofM=,tag:PHKTTqcgWiU723JyE8t8tQ==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnF0bFI1bEVhVU90VGwv
            NnJmUDUraStudERnODlSNE1pYXJsZ2RtNW5BCnZWcWxQckMrdU5ta0lyOWFpWHZY
            YWFHekJzY21tT3dBeGFvY3NMOGQzRk0KLS0tIDVleXpsc1h0ZHJ6K3ZCeUt5WmFC
            SVVldlAzSjE3dGhSYVZvaFM2TFhHRG8KT7MREmEj1xIDmXlCyxNXwTMrzjJfJI2n
            ecXnKEmg/zU1duXnOlGmvFvfB/66CvgCZr9PD8ErVc8tFrki1Mg7cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T21:35:59Z"
    mac: ENC[AES256_GCM,data:3vKTfHYrda4CKc9WCzuQ05l86KIs60/EYhlMvigTskqtdToRwcu9+ci4I33c9xW53KFM32JOAZxtBsRbqT091NBkTJW36N5JWczx1XcsLt/AhtkLt6FXUsf7wjAEz5Wb9p19T6loJonHK3cvZZgAP1Zm6EToj9F6y/gX4fIWBiU=,iv:rvgaMo3SKHupiX0I8m5nHsKLWq3+5QJifcB58rVWlEY=,tag:QrCfL47Lij6lixuX0/Z3Hg==,type:str]
    version: 3.13.1
