apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dash-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 08507fc65573594775d184a682be942e91ce6ad71837af4f25df14435c33f098
spec:
    secretTemplates:
        - name: dash-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:9zKYssKaorW12VEVVLA1pnYAfhvYHQTU3UZG7ZsPdGjpHVgHqndwXp4lkTpjL+HeFtbJCOYM7rOhfsCDyJVuBVBd6HvE0sXN,iv:DaRf1HhwlzDd4TEH6kfVF3MTb0llf9sIDHeYze8eeMY=,tag:NeJQkpWe9AKwI0MLjkf3nw==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SjlSY1FOb2RNVW80OUJL
            RFVKa3FNSFJrVmNaVjFnQmk2RDdWTld2RUg4CjFobW1oajJObmlVNHdIbTQwbTN1
            c0N4a1liYXd2amNTMSs2dmZCejRIMDgKLS0tIEhEdlkyMlN1TkNJYmt5VnZCMEZy
            Z1hKMFlQMkpWN1NIODZrTjNTc2VQUVkKuq/HaC6g5Z9ucwLz+3Gzn9pi3qqw7FzF
            oCrWKwbgf8Yc74ZpXoQWeCxiv4ChWQ4wuQ5Zb3+gD5LPUPRga/N8ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:44Z"
    mac: ENC[AES256_GCM,data:leBJhza7lUmCE5hr9jAHo6CRpkYJIRD6MuIo34Oj6ar8ABRCqz/gMdFcXuy0E2VhMK8ekQ5vlWMWzEWCQCMEo5bYCH2mEjAkI7NnyYBFyzTovCAwDK0+zyAeDQMJe5xvyqGZ8rnJ2qU66cuswAgrA8rMSWWQyJ9e51Tbxwr8QrI=,iv:F+hARghPl54mxMkQxdFSeO3hxWhTUvM/KbKQL2gf1rg=,tag:pygpaLvLabdWG5NeNBd4zA==,type:str]
    version: 3.13.1
