apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dash-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: 08507fc65573594775d184a682be942e91ce6ad71837af4f25df14435c33f098
spec:
    secretTemplates:
        - name: dash-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:iJZBXN3zL4uT2OC+ZIh3LO/0Hf7YxEYxqLUJbaHS8jm2y+rpAmdT/pk/DdYjUkiJu0IIWeDgkKKUHpUCdLoOW3ilNIDl/Lgy,iv:dJRSk953rHEuiR7UPkGIc5pB7u7NYP8gYSwMYbRg80k=,tag:BzwhaZEzLqZlRp47PQVY5Q==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHKzB3WTRGOStEV1VycE10
            aDJteDFPcEdpZXp5LzdFSVU4RG1lRGtKaHhJClJaK1VnUXNCZDhYUis1Tmt1VmxJ
            WFVoUW1vOUtiNU9FOFpLVkJiMjVDblUKLS0tIG94V0pUbXNlQjh2SmdWVGp1MDV1
            dW8zWkhlL0kwcERLb3hKUzA3ZnY0TlkKlZmzWfwjccVQwV9YkYSnrFdt639I4/D9
            8cErTgTISvroZBDnW5uH9aOqI9r9bJRPx5ZGt/EqReYi3pPhxUjshQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:53Z"
    mac: ENC[AES256_GCM,data:teZQhapSPMByuDYi1KJLwwTG8eTTSkxCHAlRX3k2LxPAZ4CNj6y1/nhQakzA7iMKVYKOCkb8CFq76ap/gBm7MaMF4+rEcmLNzUJ+0biJkGp06JZ1EClANbxK0DUBIajzHYPQyOyGLJgLEVjABrPuheQP80oWXE5KtWAkavRMenw=,iv:YLcQGBYnO3c+j1uO83/CyNVWMw5Z7PFCzrcq3EM7oEc=,tag:D4Eql5maf7lr8tUCmbKu9A==,type:str]
    version: 3.13.3
