apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: radarr-oidc
  namespace: media
spec:
  oidc:
    clientID: radarr
    clientSecret:
      name: radarr-oidc-client-secret
    forwardAccessToken: true
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/radarr
    scopes:
      - email
      - openid
      - profile
      - offline_access
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: radarr
