apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: bc5800b152c11fdd25483efb1c1e5d32ebcdb924ee7bc17de3c52f9900342cbb
spec:
    secretTemplates:
        - name: radarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:fIqE6MhGn3OutG6lTpLK8RbLq7Vs3AI8JiqQpr9PGMxqxlPatlNCWhu1mQ2zQmDQ2EsWBkQQiPLWU9C2SB+NywPePbx37GEa,iv:d5I3gc2Bfqi+dWWxUN1cSHD9E/ptzm9rpX2SKMtnzU0=,tag:uvNBSHd24yBYiM9GFJ11yg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQXFUTkdJYnZENkhMclk1
            MUdkTktQQmdxZk5qeTd2TXVRZ25rdFZ0TVdVClBVL3lxVjlBbHh2TTBTSmlSZXBi
            SjhxK3V0SE1NZjh3cUVzZEN0MjNocUkKLS0tIGJ5NlgweGw5Vm1oSWxWTUoyYkdZ
            Y1QzWDdGTk85Q0M4am9ZbG9qY1Fyd0EKXs+ZgV5NHC9dD0q8FGYWU5w+Vm6lbTHP
            64F4gUrLfaAj8eZcEuxRsjIC6/Ja9KcsvgaBc43yFLCmdchsoqKMAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:47Z"
    mac: ENC[AES256_GCM,data:nHBOmhw5SfE7sQQTPhiZF2R8AUQRnUDMtu/bhZWzBubBIjAQ/2YqngW+Ua+i2Bxf+JMfeidxWmFfCFM8u5w85uGnS8qx136TpN/U5D+O8CyLRGRY/Z4Cpq1zUS6I5+SPZc+wAykcD1VjIZcVkwOWi5ldH7gZwst8CxMqDzGLMPI=,iv:L/jaYeYz/UD0C4Rld4h9BT9Bm9Xbs14MQib5giNUMao=,tag:1fBfS4n4tnR+akAmn1dIRQ==,type:str]
    version: 3.13.1
