apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: bc5800b152c11fdd25483efb1c1e5d32ebcdb924ee7bc17de3c52f9900342cbb
spec:
    secretTemplates:
        - name: radarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:y2SqJU1H7paztsfdjfE+c1slN+7fn0Zr1k8I0MlTTrZ7XzJODKNeWK0Rp8nLNvvfDDXP+eUfup62jbYMOKZSBfcAKspVbvcc,iv:o68DUTMLgI7a580I8OXiRhiq+A/9zuiRAFW3GRUNGbk=,tag:cwp4n3kHDej19Qvd0shCog==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOS80ckQvcS9CS1Bic0RO
            aGNJTCtSRFpad0RzSXppWHQ0THlJUWRwYldzCmNmM0FpK211eXh0b0hUR0h0eDJ5
            TDJyYisycGd2Vjc5bFREalZTZTFmRXMKLS0tIENXZk1Qckd2c0dQUnNXRW44OGs4
            b0ZWMnRwb1BEOFNxeStva0UxVEhvSncKtv8wWpI/xORmMWWOhiKYjpfd35iCKvVL
            X5xX6hGOohvQYJRQ934noUDqBUtOfyzIXyr+rYivQ7/NHYW7KAE29g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:59Z"
    mac: ENC[AES256_GCM,data:x+pofXvPEA5CisSmLx9bzNDBDLn7WflzvBhIjraDc7WK6z8hGNQU8PWwxgVLtk90NO/BcxnQYfrZ1Gw9c8eLDfq9fScGqviy4sv+1qkc1Wy0Fp8h1pkTl2CT2lP3hzE0wnUt1F+OloWHYPjm2OrusOu84xz4t8DtT+FEzIW6p+U=,iv:SwJnpf7ZFrxRdGEA02SnDFWTGj++3NI+pK1GyuEWjj4=,tag:UJCeqRW9i4sWW5XG1Em9RA==,type:str]
    version: 3.13.3
