apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: d82f2bb3e954e2077db5670d3c127e9567d3fe16c4ed7dd3c46a8cae7104b679
spec:
    secretTemplates:
        - name: prowlarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:fhAFzujWgZ6bwxWoLgAehimx3QdCuB/43yCf382P6BJgsZjtsACjUmjpAs6vNzMU7hchhhUUicBwrRQgwzmSA/97bJi6yte8,iv:XW/LoH0n/sdMge9LOjQEML5+uZ5yeV5r9VnVM6Z7Gi4=,tag:/le1XQjSqZSNpzFWfKbMLg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYlFlbm84N2QxV3hpb3Vh
            bTBQamRoSmVLSUx1UDFnVnpPQnJSemUzYmgwCmpUd0RhZ2NRN1JwM0p0NU1wbTF3
            TjBMY2NXYittR1UrSmpPMklIOVMrMk0KLS0tIENaR2V4bHR2SVZadVBQSzZYeFNY
            RkhKemhOK3dia1Y3YU14RGlNMEVBKzgKn9KvaNk+hTlZdrASkdWAqwb00ZObe2Um
            e0qh2WwV8UUkUBn3AIneK1hQGNkC7kgoQ5PcXJaI15Sq+eVQj3c5dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:47Z"
    mac: ENC[AES256_GCM,data:gi1NgoV6l4ShZyBuNHd6Ru6lU5ZIjdZ589OYGrSvt3rsEBr6sE+ZVk9nzaG/OU85nN8U4T1x/TcnltT5urSqJJEF8dglYOQr7IVZBlYa+v72HnuRMEvekreXKaEdHR8NObS/ZFDW7Fx88ih4PA5QWoe32KkI5fv1cYtlSh+W8LI=,iv:Frz9MySS4qypetbKs1f1KJOkqaJ3Sb9SupNWZRCNesk=,tag:jvI92j4ToPI2pxwqXLzbMg==,type:str]
    version: 3.13.1
