apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr-oidc-client-secret
    namespace: media
    annotations:
        secrets.json64.dev/plaintext-sha256: d82f2bb3e954e2077db5670d3c127e9567d3fe16c4ed7dd3c46a8cae7104b679
spec:
    secretTemplates:
        - name: prowlarr-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:CHCLCDRQHwAKhRHw2Z0YN8dyKbZ/TF7kPaUGjLpGULFusPS4wzBCMPztxq5YORwpUgaNmWuHm4KX7PoHVE8L4/yWK+xtXPII,iv:AN7w/3aHT77yMbqa3cAfOBlbvJwHt8iu/ivsnSDVQrE=,tag:HvJW668KMcgO1goQP1g8CA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UmU3bXgwSDl5bVFyZzZX
            RXFJczlEZ3RDRVZCSUNaUDJCeDR4ZFV3NG5VCkVOdFkrQ01uQ2p5VDdwVkdaZE54
            L2NROTNMcUowMHhYVW02ZHZ6UVd3bVUKLS0tIEFzK2xqd2lKU3NwYkNxa3FpMnRj
            cDRXQkk5N21RN202ZlVpbk1XbG1ZemsKJRuqd9GwBn8WkE83TC1f2co/NnPuIfV6
            Hx345LX5RplDR5eapRXsRAN1H+NPOSYOHVl00iICDT27NNdqiUcwyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:58Z"
    mac: ENC[AES256_GCM,data:qxWqIMO1xa25kDSyJ9EkZVbn3PqLobshMRSz9jQAzjaSwoWfhD8YGtRC5uJxI2RlbiKC6FvLTftGPVVEd96hMwTs4yLsKWuvO+hCvhCAnW+57gcof7bHn+jMqRQMbIakF24oFYoD7GCkN5C1ipg/hbzfhcY0EkHMatHdxffLj4U=,iv:81DSkgF+3DdKj8AzB0TJXCh5Msg3T7pXU3egXtsP8CI=,tag:M3D7Ag6VDFHkDts2+P1QTg==,type:str]
    version: 3.13.3
