apiVersion: v1
data:
  default.conf: |-
    server {
      listen 8443 ssl;
      server_name ingest.json64.dev;
      ssl_certificate /tls/tls.crt;
      ssl_certificate_key /tls/tls.key;

      location = /api/v1/write {
      limit_except POST { deny all; }
      auth_basic "monitoring ingest";
      auth_basic_user_file /auth/htpasswd;
      client_max_body_size 32m;
      proxy_pass http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write;
    }

      location = /loki/api/v1/push {
      limit_except POST { deny all; }
      auth_basic "monitoring ingest";
      auth_basic_user_file /auth/htpasswd;
      client_max_body_size 32m;
      proxy_pass http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push;
    }

      location / { return 404; }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: monitoring-ingest
    app.kubernetes.io/name: monitoring-ingest
  name: monitoring-ingest
  namespace: monitoring
