apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: monitoring-ingest
    app.kubernetes.io/name: monitoring-ingest
  name: monitoring-ingest
  namespace: monitoring
