apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-ingest-htpasswd
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 1068e50f4ce28eb96f1dfda3a54e7b30c3f3d52c67373899d94dba5e912dd449
spec:
    secretTemplates:
        - name: monitoring-ingest-htpasswd
          stringData:
            htpasswd: ENC[AES256_GCM,data:gneXJDEyyHdfW3yvput5qG9GQ9h9BC2usNwyhK/2kGPPYOrdbM03zOFwmTZ82TID6FcvztDZF5n2UwQRskgvcdB5Lg==,iv:EcC5POLxIsNBNQ0Wh2aHOpYa6KI4Y/sDkomFN8hXuLc=,tag:2IGJm0zQOSD1ICWR8Tjn5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM0VGczVGQTVpTDhMTlVV
            czU5VXl6UUxZWWVHcmMyc0ZnM3ZldnhxK0RBClNPdERjR1N0b2ZWYWNmTnJCeHI1
            Smt3NnoyMXd1bXNBMlJLSU9uZTM3QVEKLS0tIDNyMkFYalBVWnV6dVBuZVlselpn
            YUJxNFJoRnVwQ25IYWZzbzNuUkhMeDQKuWzXfcB7GtTjOq+iXh9wLgxmm1PkhwPl
            iCqUlQjzMgEsZufi+OqKQOadTUcQI3AcLdE6W+qA2ZIH3HVhYLhe/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T00:13:40Z"
    mac: ENC[AES256_GCM,data:s2Lk0fTcAL1b40CBw/e/TIUHb1lLOmp4sRlirEEdzMzPn3MM2NlzyoG3xz1iezIGD8H/rWI70ydt/yLMy0V96vvQqLDUqfrgTVSAFQCrm11/R5uAgbI1E9e3+jVyhLgfj+4V4hKrPYNmBP/NyOr6OLrKGPK+pqqQ09uKHhc48VM=,iv:74fLjGahQBpy/5I3sltaCOj4/XO02YBt/HQUNuHsjW4=,tag:digtHnXai+mAK84iTNJukw==,type:str]
    version: 3.13.3
