apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prometheus-oidc-client-secret
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 1bc0e404e5bef623efef40488a2280c7e128a329e5a6347cfa2c57166e622202
spec:
    secretTemplates:
        - name: prometheus-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:adYgf5vrrRyryvnNyhLqMEvEypQDrt524dK7Z5oQ6IH1fEeNTHID+SCl3qoKwusxmRflgKIj+ckdbLbjDAnxJARR29OG8D8K,iv:P96fbqozKHu15AQ3aKv/8B/YYu6YZb5V3aZpwRtTrF4=,tag:mZklf1KDsnazska/WNo8SA==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TW1wam1RMGhHRkZ4dktw
            M0pQVGIrK0grZXNmdHYveHFSQ1M4UEJLNWdzCmNOVGxVSGUzOEhvd2t2K2lJdi9D
            WE56ZmZtbERUSWJYQ0FCRVpsVzFYWXcKLS0tIFVDcWdVOTBSaWFncVZrdnpkWEJ2
            SmRVMk9aVUhNQkJwMUxIc2tuaElHZkUKdt8//A4oesU8WIWZDOH+CjaYdHwT6ZWO
            BdznxrN7j6bcSErFcwGAFxhtKXuoC15Fkb1LjcPQ6Smx78SsKRIfJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:22:09Z"
    mac: ENC[AES256_GCM,data:yE/V8wtKZBueNrMoGwMqn6MhFITJWgW9WRTviwmbmG/O0TpE9fdMJUdW2/xpnKInyDwG4bmsro+QklixlDRDZ4djrF7O5NKVl62Fn9rLeFhGyYpVcaqNnH57umgCJeglERBPX0ztUc/ZLSrK6o2Uef/L/EdG2pi95EFq4YGqaRw=,iv:A7TYIX2d5WaEqjuhJFu4LFT+opGUsB+rXFNzx+qa6lA=,tag:iYw4b3PkjFV9p5YVJUIw4g==,type:str]
    version: 3.13.3
