apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/component: prometheus
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: kube-prometheus-stack-prometheus
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus-token
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 1c0b1ab314245cb03a8c471995807297f1bac619d2af5d01aad26d55d5ab3219
spec:
    secretTemplates:
        - annotations:
            kubernetes.io/service-account.name: kube-prometheus-stack-prometheus
          labels:
            app: kube-prometheus-stack-prometheus
            chart: kube-prometheus-stack-91.9.0
            heritage: Helm
            release: kube-prometheus-stack
          name: kube-prometheus-stack-prometheus-token
          type: kubernetes.io/service-account-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMm5LT1ZJam5ERmpxMG1h
            ZjZhMG9CMnlqTnJqVmNqRmk2SnFuZzdyN21jCnVDYXVmV212SHZYazFleFh6a1NS
            UDFZUlpmUzA0dENZMDVGOWFuNW9QRFkKLS0tIEtjZXczak1NT09XbmoyOUpuem1w
            TzZGanEvMHVkaDBEaUJYcldNaEE0VjQKTDejJmKVGOBH9S5emsDXlPBjnGeIZRux
            ixjp3LyffAvvPbq7SwnRp7xkLIsvecZkNE7YuS6rZrip6Dr0vtW9uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T17:21:31Z"
    mac: ENC[AES256_GCM,data:FQ3ekMFJobIPpDeiiENWL5M0DrRoxqzM4gt6yzwJ6ekFUWPboUvuJREMuOqbA2n5JB8GY8GK7NHovwUg8LkhcGcpVuRyvIDS/exWjq4L5QlhPKqlD+hoZDwmCEX9+l168/2ji8nCDtSQMfLmHvE67f0JH+76D3m4QzkBx8NTWKk=,iv:SYury8cWupbpTNMF5eijMdPi00tHn9fPbtCWOZb/CMM=,tag:62fc9N7MjWnhZt8Hh8v9SA==,type:str]
    version: 3.13.3
