apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: alertmanager-kube-prometheus-stack-alertmanager
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 9c148df3f6f4d05de589b2cd86014919db55d3a503fd40b3c81303b84b1b0568
spec:
    secretTemplates:
        - data:
            alertmanager.yaml: ENC[AES256_GCM,data:DFgsN9SfTpZLPhkSkp91Ftkr9qq3JUuRgT9+9mQw2GavhRHUrTbElKQVx55lZgz0Um6ZPNQQqwYHAZIsIdV0maIk4lL7qdnt4sFzgmjduhLGsqAi2PZLDeQFirih9e+BuVZJ09mTVaVHJ9QE+lBpzbVtcqwj1ykwnJJI94jIyeko3ExIJrtlYbzSXlEbqtPL6YycJ0KTOklPqtVWEPY2dha4vxahx+ztvLMLPE1Ty0TUKF2sv2cztDNv1NmInOXjtW83KU3gCtzDtrW1yzDp9+6/jQiA4i1MONjNJxOgwMC/h1ssWyS1WEaFLytpfjgCxhhK1TwRaJr3DqUkzRTjazERxYXyscIwUJLBMFodrZFwhX8sj+0mXkC+9imaGXQEzDDvao1IU3Jj1ODRy2bvH0S+pPtm6EVJZKGHBUfZPR56m4J0i0nOdsBUeC7kkQq8zqi7dc3zCo0EcALQ/lJaz6J3FKUcX9pkC8qrTveHMvtZzby98M2WomOJMhQUR8Rjm7pwjizSHnHn1ScJjPuyTB6eGKKcONFYfO/gPPbOcQjm8SMfNv4DYidsr2t0XADbv1C5+YPpp4yJwaqitSrDstJzSWqSz8Q2TgOj6/FBND+lkBEAV0oGlWcIw67x+T8AUvAua6G78lBvKqF26RWVxOlFIk+oEiJNqkK4pqHRKD9MgH2rTXeZxAiBKEtDtQ+jltnxKqaLpB/y1Yo/tUSQK5VQisrlpZmBiUV/NykyZXYvNEb49OeodfKzvBVGRBxPHaL0AwNJCrySl969CmknQY2poPCJcyOrrffxGdfHe/7XwqM/T/ef8LtsqmvVqqLHhpI0skXU4EKbl0vXIg5CISlroH9+ZD50eMiN96GQj8hj97LvmJ07h86sufDhWejtWLB+RNtrcjDgOBz+dNzxBLzFARVhojL9kCxeAQw9J4bgWYm+wmswSHzzVmvwi21CGtQ8raeJfEtJY1g8VMHZjwAdZ5cbdDaH1o9Du30uaTDlEYkIlo7sJxj7s091Y7J5cBAomi9f96d7X/oSsFw+e58JpxJRF6udmVzkXz1Kkd5eOMsxrNT6ijhb1gBs+GTBBEH2FD8V80WqrcWgEV4ShvsxMobGuY5yq6a5lQu2q/G2HGziuhHDMu3Vd9P/Kq5UXeFzfRgrXzQRFTfMwAzLcmv/Qj9VUDq4H770GyuDmzjg3zNAmUJAJ/GxMcBN8xzTQxlk3Ue0w+mwE65uDy4CWWZfCDclqO3HSzO4VugRBzrE3IUJ,iv:Zs/ZFYcHnDpIF86fxNSOtYdCHaf18TDgFQdenOM448s=,tag:Jpr8C9gNNRYIYKzitWdYfg==,type:str]
          labels:
            app: kube-prometheus-stack-alertmanager
            chart: kube-prometheus-stack-86.2.0
            heritage: Helm
            release: kube-prometheus-stack
          name: alertmanager-kube-prometheus-stack-alertmanager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUVlTWEpLN2kvYklVbVZt
            MlVXdlh4SXFuSE5ZQ2JBRVJLUzczS29pS0hZCjR3TzlzSmUzcHRFMEg4bGZKdTRZ
            VGE2aDlSVlExYk1ud014WnRGYlpMekkKLS0tIHQvRGxXWFNFc3g0endhSkV6cXU4
            SnFVbWFDbytBNjhLVGFyQzRHRDRwMzgK/HBDu9YAB1+XuLTGprw4zmmIcbYdR+Je
            7r2esUbMUJj1C0z7jAvG/p1h8IKd/omcteFtYe5I96D2i60sapQxkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T18:37:45Z"
    mac: ENC[AES256_GCM,data:PKTJAvsz2v1gXiTwHRXas536RrWur1EBBRE6jFsaBpoNvb16r29YZ+EqtAvfEvTmtE5xFePzbKrkfTz9YSWzXtc8JwSqDnPJXysBUYOJB3koD7bXTKS9moNG4vNDgXV8h1mKYvhekNcCgJorHuxSvpkyEr7fi1IEh+YdNfgVG8c=,iv:nJXoJ01hS4vUBeMsgeCTgu3dTwXjADCRhPcvn6id0t4=,tag:w+PGIjtGO16YQntXLrVgRg==,type:str]
    version: 3.13.1
