apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus-am-confg
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: bfb08e0d18740127736df8acad97aa89863b6ff73b110ee1b2065388d0b1132e
spec:
    secretTemplates:
        - data:
            additional-alertmanager-configs.yaml: ENC[AES256_GCM,data:J/KxxGWDK5id1jF+ahiPHJdErkiy8r2XhNq4jwg7WhhlVWjg1K74Xv/v0Htfw3rbFvDxiLkTd/RhZbe+r1XZKhmGZy75FAS2YPjT+4I4hyptHPXymDTT4tDp6RehPllR90I++fYoLQ0aM0/WTc1mWSRWyqmz8m3CjPIzWL/ciWBi9or4DG9T5XbpzUvvRTS4542BjuPFBhif8Y00FK/UrDgr78qVRydULEX0rCIgbQP0fFpZPBHSbigLsoBeM2zbkdR0Mf3BRas=,iv:tIeS3yGvKRBmbI6fbQPJ/+v2SMLmGRBSupk88jSVcv4=,tag:eZgCuqeresqUCGcjtCpX0w==,type:str]
          labels:
            app: kube-prometheus-stack-prometheus-am-confg
            chart: kube-prometheus-stack-92.0.0
            heritage: Helm
            release: kube-prometheus-stack
          name: kube-prometheus-stack-prometheus-am-confg
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWZYZkFoWVRDMHJwWmNB
            b3BuR09CUnUzMkJJNUVRSUdqQXJVT2grVjJnCjRHVCtjZmE5ZC9BS2NvTWtoYTV1
            aFNHcjlqdm04VjZwOWRIUmhYMUI4OHcKLS0tIDV4UHhsREl1VktqOWx5bytEcFY1
            QWNwOXJLWFZuTU9sajNDcHVzeVA1MkUKDlYUS284EsS4yw/xu+LVA+LySKQ9Myfm
            ud7H0TVkFLdRvGQzYb+bFGhUzfuMwLRqvXNL61r7+Zsn2kArUi3voA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T23:48:38Z"
    mac: ENC[AES256_GCM,data:xlia64wAnqLrAe4U300I/Tcpo4i3m011wuHP9Pf/sOSAGJw9WCRL/DvrTUzePGinqvEm0zdFNXbShunqtJDobGiD2yjb0wjwAB/uRWUJxYa+hHwHshjoxgG+amgBn7ku4kEPw8tTP4sB8xMdEeY4t5Ze2VOVB7JN5Y4eKYBBHsY=,iv:Y6DZeBxFs1km9bFDWnRyKOZjr9zjyOCMqSs78Te4fgk=,tag:tdkueTtSgswKLVrm02e+Zg==,type:str]
    version: 3.13.3
