apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/component: prometheus
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: kube-prometheus-stack-prometheus
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus-token
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: c73f8d065b0ed12ca8d13574dbed2199f95e270b5de0e4c922fe5ad22c0a4f14
spec:
    secretTemplates:
        - annotations:
            kubernetes.io/service-account.name: kube-prometheus-stack-prometheus
          labels:
            app: kube-prometheus-stack-prometheus
            chart: kube-prometheus-stack-91.4.1
            heritage: Helm
            release: kube-prometheus-stack
          name: kube-prometheus-stack-prometheus-token
          type: kubernetes.io/service-account-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL0RWUVF6TUs2WWpYT0xr
            c2JMTzRLQkRNRWExM09rODUwV1M5REEwZ3prCnBhZ1RuY3o0MklvWEY2N20vV3B0
            bk5WbnJ2T1VQTUlmYUJDb1IxTDd5bm8KLS0tIGpTVnJXUjIxMzlUSkp6UWNxcFB3
            bXhoTDMvZTRKb0h1U0psd2FtMEJjM0UK3tjboh2V5GpPguQhGVoisGF1sSj6vvx/
            Z/Ybn20PFl+x/BRy/m7uDCCmZcsxMI1p/JeAl1M08qQjYVOmG3uckg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:46:16Z"
    mac: ENC[AES256_GCM,data:KV1oPuCP8fuempcJO5+AY7UQDQjLIpXfSPnk5fmT77Z56tbLAjoCEjLF6f/R+EM4muZX+cqGH7pcV5ya/iksKTm2+rbG+jpc6uY9gvpMDfgFPqECbyPiIkmaMuWT4cPiQyImc0NlCJasHwEx7DuerS4q0b1H9KWWdNUCrtyZQ8A=,iv:YuaoXU21YlhZiG9mfZ1SG/cPXjWCaiy1xdSOQ3r7AXU=,tag:6VopIMW/jzjHPIlvwGpjaQ==,type:str]
    version: 3.13.3
