apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: alertmanager-kube-prometheus-stack-alertmanager
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: cc4a936fd34b6f1c38dbe2f48b583b84e5586a61ffff42be59c1f63e0ddc6eb2
spec:
    secretTemplates:
        - data:
            alertmanager.yaml: ENC[AES256_GCM,data:tCv4wmNWE1E2FoelF4UUND4k4jb9bkdcrdhB3WA/Q8O2AThBU9kihJfemThNneA2eqPHd/HF5HlDbL682+wLeZMwiTToc1pinxcew8Rniss93fEmhZgDESYacjuEcFgvTZwFKKT/WuTr9CVoCKdLhzUQK3P5nQ0f7OS0bzBc8lTLJVg9pt94n/HphEUs7b1lCmDOKo6Dwam5jWpZcvozGrB7e3bHbjnyFbiZ6W+RQ7TRQk8xP605xzZfJsT61C2AHX23m6q8wznw+57QWjxhzmf6AX/G0p6ChyJIJJ8btd0HGiFRUqgXZDc6vILUf3h0URpRlYs5YLOgFdqt3HHIqGvwzgt0CI14hNhzdIVnSNvTP7mCxCbQ6QR9fal43Tez9onu8M6r1HFuKM7QsHnnQ6XHXEInsRBvYYHbVOfeZWgZMM0ujMMIiNbQOXTq06D8Ro59kbYfsnS+gtMImrcCZKRCmo3CamWKpABKy+9J7TpCjqbbg007Thp+FQy4mHoTg16OwQy7jfeYxVmCc/iQXavzTl2JaVtMQfUow7rwN46cxXlRsxrdWBrL6Pc3WA3z11NI6EnruC6y0+eApoFjVd02U/WVEEI8naf1Zdp8ua61m7agYfnDUzypv8UcOWyo1rm+K7uYwtQN42VPZUbddzzGwBKGxsplq6g2c9sgsfMHamtlm75t1zGtrjgmicJ0Q4pYu0ZZJB+7iyK4mySwGqPa+TPcCo/HAbKOXoyoeLcJfHBWVBBXqFpkKti7+I9aHrntqaL1l4WER6LaXPfhIhIl0cHDuo7d6AApRl0QL/e3jqoYTlsA5SSSKG66eaBTYXkZ2dXVJ9G8msI6tf8dRiJg5dc3J7OH3yZrwkkZpe4d67MKkDJck6dn2xdcjyn/NpbiuJqBEP8ERBMB6VKyzdSgdS3x/S3tuTQFWTHt9RzNmNot1BaUvwXTKuIAKTErRwdZweAQ2DpMarPo77AmPmn6pHILpeilu6WgOq+HZSgyr2q5bwpQRhR4hfqXPUXmpBS6KTn9Lo+EHVqlPbGeaVjPlsdcF9V2xWYGNlgVwVlBGBvGglaR8ZaNF5zojFdqokB2yIm9vgkRlg9SfeB3rjsRZjzQTzzaJdBXxaSBHq2cgEZ5i12i3ELXU6TNVBgsFNfQtPZ7OCvpoZCJ5OiUmXidYXmn5sAGSNJlVtB9AdZyC56t9ioZRpEs9MjhOCX1wnsh2g5tQbK3k2mzfy39aCOUb/4YNYhj5/RUzL5BOaNib3rM,iv:6VL6Ofn1ZZegJxhYPEXgSAL3/BtBMNRJaG8kPzNYhpM=,tag:yw94YdGmYExUVNFcBU4NIA==,type:str]
          labels:
            app: kube-prometheus-stack-alertmanager
            chart: kube-prometheus-stack-87.2.1
            heritage: Helm
            release: kube-prometheus-stack
          name: alertmanager-kube-prometheus-stack-alertmanager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSlFEYlJmOVFDZDE3NU9G
            ODBYbjhveVU0YjZ1N0djTVpXdGRBLzBFRDIwCkxsTFkwSFFwYmVDQUxBc25pWTB3
            YzB5OGQ1ODB4QlBPZG8zTy8xY0xlTmcKLS0tIFl3WlZ4Uk9kYjE2UGtFd25DaFdO
            a3d5ZFlyVFQyRC9GbmxtUk5XTmZlKzQKB5ihDSRyIchICQEHWt0meN0P83JA8hSY
            6qjcwo8gCcRWOm+Iahw+qrIXzNJOGVTj9qxvJzGS26jYNgYhza9qVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T00:06:22Z"
    mac: ENC[AES256_GCM,data:F0LBinymzRGE9FN6slT2QjmFgzCWPqr2excsSm7KBP7RgmKiyj8ColOBm7r7/ZR6MlZfbLPrPVTNmae3bVlW8VZo6KMOO+PZtMHpRCEMFUQGzJuOuVuURIJKmHOfTdcXEgBK+o6mPbLM2I5UFAbne+boWFI7u0eOd67yog3zLbM=,iv:XCXI2d2LPmtekN95Wj/Wrs/un2AOdCJURL6mLq1Ypow=,tag:lwfjL2EpbSnNHXjAcAcC0g==,type:str]
    version: 3.13.1
