apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: alertmanager-kube-prometheus-stack-alertmanager
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 60df06f02f12c993e715c40d2083f03dcc87b20ff4e894dd08e4488508cdc4a9
spec:
    secretTemplates:
        - data:
            alertmanager.yaml: ENC[AES256_GCM,data:Up7BbgDM4ojC+RC79jQj7PxRmmrBcl5tvkuP1dB0lzyjp4ddLb43c5koGiGrmaooumBskiYDyPOwf2bwh4EfdHDhd+A5Yj4WpnVCD/p0Aq/7JV8FeMhMQ26JCsy8fdDUjUISOt1dmJpIm97U0LNrB5dUSFNUu2CnomBBaAW1TWJ8jH4TRvMYoZjPXP/ZfowcqaOS+MaU62qWJO6OVmq2bwPd7/7qf0fdURXFYNVjDMn/vjqiaE0EGFd8hv6ZId4k+PGvvEpytNvEQ9ZyXmdHgF+prFqrzR1IMI1hZ0n2N1Mg3ZK4ZqJ4ltDREMZrl8TarJoz1XWlIAkEYDBOy9YULd7ohurX8gFJSOmLvEcaiAvl/yKVQU2MfAdK8FyMJg1XPJEHnVv4ry0TqJJBfLzqYKIolCqxL0imyxh1wbivSnFov4hJQ2/fAHaM5N+X/IsArPigcZdvVJ7+XTqH3JF7N7JqwVTdPIt7TB5DoG2PhshURUeI22iwKvzhcdgYh92CLWwtBTsC9qADtYCg2V0BfUwwEAnWEEE+ab+/3UGr+NlDLYL02kthVH1mYoVU9zQoP/8ODfR8NUlnMe7xgX0htheSCzstGlu5nPoNb7ORcWqE/57H9zhNTD/kog0i3t1ZyooeTJo8bxu21LtFNAo5unXR8CKaY1EmZot4u0IL5EKKA9wzdn8w8EnuL6BIkTSGNcfck58T+48uylKGaDLzAWb6NteMckqoujHsPTJmtop+hO5pvIrWZv5taI6gSStuRG9j0mA38Z/Oc2x9K9ZT7BBwdXOtKSxtsObU68dPb9735BZzWfXpBTLM5JUxJCVuHS/Ng+jvaNCFubd94YTL7THgn68W2WQOQgFxDzq9SMeNJ8coj5cSOe5BT9oW7von1JLyLO0wNf89fcUJIdX8WNMsHyY/hPCidp9p99SuAHRjgrD9U2iWvVKaP4OXc421KZ0bqnuopAuN7fGu+ap9qE5mYbS/zSGl8+RewaCjYFlIfMbMOfku/FbQB1sP4ux+zR4ZDYcMNNQIFmyRAhLwcrvicxF+UHq6pTDeELUeRR+ACIUeSvDpdDgotIi7EFIMqSDGBhBAN9jKVtgh81VMA6KrgpmIZqFwJ0OVMYngXEw3gZYbUtUnqqK5v0yrXi9pEQqZ9kpNm13Q4fvabed9BfS8yxv+GsLt4n2Cd6hDAoxBTwCHLSsh1XVuRQt8h2SkdPaMVYnIXGs1maz9bQQX5epHwUKM21G6h+Ap0wyG4p79enfv,iv:fZ6FtA6D6JPuzFI2DdX4dsCJpX3t33iG7R1myG2VQN0=,tag:7emvFpl8CvxnokP2FqROfg==,type:str]
          labels:
            app: kube-prometheus-stack-alertmanager
            chart: kube-prometheus-stack-91.4.1
            heritage: Helm
            release: kube-prometheus-stack
          name: alertmanager-kube-prometheus-stack-alertmanager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MzlLK256YldBUVIveHFD
            UFovMVVDU1VCb2RyQ3B0Tm84bUQ3TDVLMGgwCklXOHlpN0NML1ptSmJUaGlMR1p0
            eTZ2YUl3ZzlIdkkwd0lFTDdZVmRGdFEKLS0tIHZUY3d1NDh5NldEdG9PSEoxWGg3
            SklLdzlOTkZHWEZOOEE2Q0htdEpHQ3MKulyhcTBu7/bOdIA4P7S7UtyW5Ekiuf9h
            ukqesqvLe1qHYOmW5bc4oauxO/cvTG67SdSXoP9uSojlGIXPVz3cKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:46:16Z"
    mac: ENC[AES256_GCM,data:q7d7BvpAeVj+hlzzXMW1DwKM3ok3QRU8bRS2e2fHup4zQqWWYiMMjZVF0oqNxZC7DCnkZWo451oD5+ML5WymdrpbfeeBP1HWnFO0Hp58i3FPbRCabdR9S2dYWhW71zzOV8BD4d1DgNxj/seyLgcY8pixvMfLPWCaf7eB832RfWw=,iv:W/4I6O8Z/UFZb4huhh8fJ9M3A6u4wODl9crMexOconQ=,tag:v8OVzPXfdzSoLwNy0G8u7g==,type:str]
    version: 3.13.3
