apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/component: prometheus
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: kube-prometheus-stack-prometheus
        app.kubernetes.io/part-of: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus-token
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 590bef100bd27d9b5c51388333f0f538c618ad30d09d3bf7df38b80ed5c10d27
spec:
    secretTemplates:
        - annotations:
            kubernetes.io/service-account.name: kube-prometheus-stack-prometheus
          labels:
            app: kube-prometheus-stack-prometheus
            chart: kube-prometheus-stack-91.8.1
            heritage: Helm
            release: kube-prometheus-stack
          name: kube-prometheus-stack-prometheus-token
          type: kubernetes.io/service-account-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSTgwOVZOc1R4cVhlNTJv
            YkcrNzlKeDMrWXBnaWRFVnJNSTFxVVJ4a0VFCmIwdkNVb2Via2NNQ2NZcU5DeDR2
            aE9XWGtuZHJabGhjdGxlZlh6NE9PSG8KLS0tIHNJM1Bjb1FXZm5zTVVjbEJJbUhy
            UFVuZ0gxSzlDaFh5Y1E4ZlVVZmgvNG8Kn4HPiBc2blCG6zOP6kZS/BKfwd65mckA
            TSDmkFXvjJhMN2LTLDIEeTaDwHwxSpQ2mNadZW3SQqB0pIWlG2gV5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T01:01:16Z"
    mac: ENC[AES256_GCM,data:llTnt6ajFvxOi0ibnsW+jwJyhcSb1se1yGJu4NqQaWIgKfW519KI7dLuwKLu5wNMOO3gIrXd2mVciFAeuQeh0zXiABONmITDQtHB4qi1MMZDXkchM9OVo5eSXIx+SGS3KcICwwBzdH2R9CNOOEm881NXg5dvIdOHE0ld7x61gms=,iv:cWpl5cH4ccuiAdzMQDANUrnwkCJCooFeHP9cgRE5DcY=,tag:z01BJaLa8KqTRTk9fB77jw==,type:str]
    version: 3.13.3
