apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-oidc-client-secret
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 17c553b4be17b782152234c7892d02075352677ec3493131c158a2d7e9b47736
spec:
    secretTemplates:
        - name: alertmanager-oidc-client-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:hSS0vW1+zW0sS0krMgXhbKGcl9RNm29iEfcJc0FOSJoCEmYOFif7n17DhmG+waH1GF8Sla1uV/6q+bzy1jE8uOM4SW8T0bKx,iv:D65sfjCGNixGYsr15wMWeWcu/iWINBWcyaJwgf4mxqc=,tag:nfrBUxYIZ8MgCyr8dOKLGg==,type:str]
          type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSmFkdXY1eDRnRkUzS3J6
            MWk0dEJlcWVqZ2V3SkZ2SVJOS3FkdE8vaFNrCkt1ZjFrelA4WXhxYUJuWVdGNTVD
            VTc5N2k4ZGFUejE4dDVBNEkxMnlqRUEKLS0tIEZPMnlSUzBGNTlGWkcyMjBIK2Fw
            VmhOcTI2T3A4V1JqbzM5d1dyVHVIZ1UKqLJ+pUumELpHfyM/5/unox2B8vbUY0VU
            K3uzDjpO55Ed9VAuQfsHnx/F83zCQJ3BkGzOXF1uYQARMOqy9kBpNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:22:09Z"
    mac: ENC[AES256_GCM,data:3pNPIXv755b+rR5w+0milrxpo89gPhayesIYoYr9BJ1fAR9XarzqYdrBf1/wmY4f263PzNCeKvt3UL1p6QNUBzSwzQ+c+YDK+JgnlpzXIp8ASGrSdD89ZOP7UTz5c6gpQlh1vt13k73GJkF6X5xwG3K9ZkCCiyVXvqbbpXjvBlM=,iv:XLIr+UC90hZ9CpPzqJlbp13ofmbBQKTQP0pEoeAAIxY=,tag:bZn2arsHpXe+P3F54VWvAw==,type:str]
    version: 3.13.3
