apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-pg-grafana-password
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 5a4b71e3911d87b814944ab9ead043056ce9aed6e23b320a2f348745b0dd87c3
spec:
    secretTemplates:
        - name: monitoring-pg-grafana-password
          stringData:
            password: ENC[AES256_GCM,data:A0VjpDYsUrucHKKW/h2El+NXvYs1Ws8j82NsUmTSVNFVdZjxVDgXzfes1mlXpnbUOhVM6WofiuWUVQ1GyIz9b2NfdHygnyah,iv:0nQwSciS3RqDZtPZnZMjfv/Dmrqi/FTkigr1Jz6rAtI=,tag:uW1yTlS5mIaFgz/ExI+aoQ==,type:str]
            username: ENC[AES256_GCM,data:8t43sLvGvA==,iv:X/iwjxFsEwxGIEETTCE8QCe7REX03DU1TqV9mjhpphc=,tag:Zg9EAqucWR49k//6w1XkoQ==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNEpXNE9qWGZKdWFnNC9k
            bzhCMHN1ckcrSUlEUFdmbVV1Sk9WZlFtZFQ0Cll6OVFKMmM3YWwxSlErODR2ZFNB
            L2ZQWUJaMlRrNURXeEpYVkRIOG00eVUKLS0tIHY2ZmNjbThhL1JtcFYxWnltazdr
            MVh1RlNxSmExSHY4T2VLRlc3NDVaMU0KJIGNlhBfaPVW97VfoOoUeMM7M4CrlaDy
            CHd7NP6qqRSPV5UlskOBWJ83k+211AKLUlwA2iABWeOoB5OZXYAfhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T21:22:09Z"
    mac: ENC[AES256_GCM,data:PIRvmrGVKdFdLXqcpm8vyFgvhQWGMgqElGh1q2Iy0tF9JSiFOJ75Js+nCiJUwddqkkgkotDQFWaGg6O1gyi9vTtQ6IxC/9QTTMQRM0kHCWCSiyi/NfUMXA+RQN8FmemKx6v1Tm7HoOlHFGswEOCPfwFIuMDOcJU6BIlEJGkc1Po=,iv:KA2IadqB+tdX/wzlW0qFiD9osBLEDKZ+baVddib9Lkg=,tag:1PLsMvoLkz2eyqQAb+p3/A==,type:str]
    version: 3.13.1
