apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-pg-grafana-password
    namespace: monitoring
    annotations:
        secrets.json64.dev/plaintext-sha256: 5a4b71e3911d87b814944ab9ead043056ce9aed6e23b320a2f348745b0dd87c3
spec:
    secretTemplates:
        - name: monitoring-pg-grafana-password
          stringData:
            password: ENC[AES256_GCM,data:t333PoAhNEM/xxs7sNJ5Vmag/ZnTENA+Akbw61dVJHN9H/jZVWIEooxC8uaIiIuECMQSwKrs5vPCOxI4V5yo45du2mreV37m,iv:OuYXllBjzBN0P0teEhHQ3VTrEpC+vNP7EvzjKxaB14o=,tag:okXVZ/GdUKBif+8ElKuDIA==,type:str]
            username: ENC[AES256_GCM,data:Jdp4xkBbfg==,iv:bWwyM+p8oPhPg1D+We7/p4ynmAl3zS11vd3nMcEOtWI=,tag:DMZdUCzn3fWdnNGJUvyBfw==,type:str]
          type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeVRIeHRPcVlqMXhFbnVU
            dnlIOWJTekplVGlza1pEMGFDcGpFSnJTUms4ClRHS3lPcU9VTEVNeEZqTE5md3oy
            UTAzeE9yOTBYcWxJSmsydzFFWlJySUUKLS0tIGRhMU5uei94bENjY3ZmMUlUSmow
            S1VNam1RNm9oNjYrejZ4aXZQSVhEalUK18lGyfm2ZBit1ojk1Ao01CJUu6oeA0HQ
            0xS17bcDw4m3FZjla7vTscVa8RbEihlxZI7oQimF/VRYv+mFuOt28g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T22:32:57Z"
    mac: ENC[AES256_GCM,data:gogKlUd26HoWuUtG6K7/EF3oXlGNkdAS+q8NFhGH35C36eD1zmvxaFTwtC2z8zAgZIu+trbUzuE6aPxxL7cT6owuGvK6PBwsY6L9bPZIfQoVB3xx2lQl50rSar3kMCTzXJI4E1YDrUzm3Ae8A/I+qSCh6Zq2Taz3jH+9NtWMbTQ=,iv:0Uoyn3LrhiuyENhTMpqRGXmGzHhq3dnT9dS+ax0dA9Y=,tag:m62AmJ2i4CpHmALDeH/uXA==,type:str]
    version: 3.13.3
