name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update helm charts
        run: nix run github:nix-community/nixhelm#helmupdater -- update-all --commit
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-labels: |
            merge-queue
