apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: kube-system
spec:
  gatewayClassName: envoy
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-proxy-config
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.com'
      name: json64-com-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.com'
      name: json64-com-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: json64-com-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.dev'
      name: json64-dev-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.dev'
      name: json64-dev-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: json64-dev-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.net'
      name: json64-net-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.json64.net'
      name: json64-net-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: json64-net-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.sinistar.io'
      name: sinistar-io-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.sinistar.io'
      name: sinistar-io-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: sinistar-io-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.sinistar.org'
      name: sinistar-org-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.sinistar.org'
      name: sinistar-org-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: sinistar-org-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.zeroday.pub'
      name: zeroday-pub-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.zeroday.pub'
      name: zeroday-pub-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: zeroday-pub-wildcard-tls
            namespace: certs
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.zeroday.run'
      name: zeroday-run-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: '*.zeroday.run'
      name: zeroday-run-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: zeroday-run-wildcard-tls
            namespace: certs
        mode: Terminate
